import { Project } from "@/types/domain/project";
import { Client } from "@/types/domain/client";
import { Enquiry } from "@/types/domain/enquiry";

export const DEV_CLIENTS: Client[] = [
  {
    id: "cli-101",
    workspaceId: "ws-default",
    type: "individual",
    name: "Anoop Kumar",
    organisationName: "Kumar Residences",
    primaryContact: {
      name: "Anoop Kumar",
      email: "anoop@kumargroup.com",
      phone: "+91 98470 12345",
    },
    additionalContacts: [
      {
        name: "Lekha Menon",
        role: "Co-owner",
        email: "lekha@menongroup.com",
        phone: "+91 98470 12346",
      },
    ],
    contactDetails: {
      email: "anoop@menongroup.com",
      phone: "+91 98470 12345",
    },
    billingDetails: {
      taxId: "GSTIN32ABCDE1234F1Z5",
      billingAddress: "42 Marine Drive, Kochi, Kerala - 682031",
      paymentTerms: "Net 15 days upon milestone milestone completion",
      currency: "INR",
    },
    siteAddresses: [
      { label: "Site 1", address: "Plot 24, Panampilly Nagar, Kochi, Kerala" },
    ],
    billingAddress: "42 Marine Drive, Kochi, Kerala - 682031",
    communicationPreference: "whatsapp",
    clientNotes: "Prefers morning reviews. Sensitive to structural timber details.",
    clientApprovals: [
      {
        id: "app-01",
        deliverableName: "Concept Drawing Package Rev 02",
        version: "v2.1",
        decision: "approved",
        actorName: "Anoop Menon",
        actorRole: "Client Representative",
        timestamp: "2026-07-10T14:30:00.000Z",
        comments: "Approved with updated balcony width.",
      },
    ],
    clientDecisions: [
      {
        id: "dec-01",
        title: "Selected Italian Marble for Flooring",
        decisionDate: "2026-07-12",
        status: "confirmed",
        summary: "Selected Botticino Fiorito marble for ground floor living spaces.",
      },
    ],
    createdAt: "2026-01-15T09:00:00.000Z",
    updatedAt: "2026-07-15T11:20:00.000Z",
  },
  {
    id: "cli-102",
    workspaceId: "ws-default",
    type: "organisation",
    name: "Riya Thomas",
    organisationName: "Thomas Retail Ventures",
    primaryContact: {
      name: "Riya Thomas",
      email: "riya@thomasretail.com",
      phone: "+91 98950 67890",
    },
    contactDetails: {
      email: "riya@thomasretail.com",
      phone: "+91 98950 67890",
    },
    billingDetails: {
      taxId: "GSTIN32XYZW9876Q1Z9",
      billingAddress: "Thomas Tower, Collectorate P.O., Kottayam, Kerala",
      paymentTerms: "Net 30 days",
      currency: "INR",
    },
    siteAddresses: [
      { label: "Greenfield Site", address: "Greenfield Estate, Kottayam, Kerala" },
    ],
    billingAddress: "Thomas Tower, Collectorate P.O., Kottayam, Kerala",
    communicationPreference: "email",
    clientNotes: "Requires formal structural sign-offs before BOQ approval.",
    createdAt: "2026-02-10T10:00:00.000Z",
    updatedAt: "2026-07-18T16:45:00.000Z",
  },
  {
    id: "cli-103",
    workspaceId: "ws-default",
    type: "individual",
    name: "Nikhil Varma",
    organisationName: "Varma Living",
    primaryContact: {
      name: "Nikhil Varma",
      email: "nikhil@varmaliving.com",
      phone: "+91 94470 54321",
    },
    contactDetails: {
      email: "nikhil@varmaliving.com",
      phone: "+91 94470 54321",
    },
    billingDetails: {
      taxId: "GSTIN32LMNOP5432K1Z2",
      billingAddress: "Swaraj Round North, Thrissur, Kerala",
      paymentTerms: "Net 15 days",
    },
    siteAddresses: [
      { label: "Oak House Site", address: "Hill View Colony, Thrissur, Kerala" },
    ],
    billingAddress: "Swaraj Round North, Thrissur, Kerala",
    communicationPreference: "phone",
    createdAt: "2026-03-01T08:30:00.000Z",
    updatedAt: "2026-07-14T09:15:00.000Z",
  },
  {
    id: "cli-104",
    workspaceId: "ws-default",
    type: "organisation",
    name: "Ananya Sharma",
    organisationName: "Sharma Estates",
    primaryContact: {
      name: "Ananya Sharma",
      email: "ananya@sharmaestates.com",
      phone: "+91 91234 56789",
    },
    contactDetails: {
      email: "ananya@sharmaestates.com",
      phone: "+91 91234 56789",
    },
    billingDetails: {
      taxId: "GSTIN36AAACS1234R1ZP",
      billingAddress: "Jubilee Hills Road No. 36, Hyderabad, Telangana",
      paymentTerms: "Net 30 days",
    },
    siteAddresses: [
      { label: "Palm Springs Suite", address: "Plot 42, Jubilee Hills Phase 3, Hyderabad" },
    ],
    billingAddress: "Jubilee Hills Road No. 36, Hyderabad, Telangana",
    communicationPreference: "email",
    createdAt: "2026-04-12T11:00:00.000Z",
    updatedAt: "2026-07-05T14:10:00.000Z",
  },
  {
    id: "cli-105",
    workspaceId: "ws-default",
    type: "organisation",
    name: "Rajesh Gupta",
    organisationName: "Apex Realty Group",
    primaryContact: {
      name: "Rajesh Gupta",
      email: "rajesh@apexrealty.com",
      phone: "+91 99887 65432",
    },
    contactDetails: {
      email: "rajesh@apexrealty.com",
      phone: "+91 99887 65432",
    },
    billingDetails: {
      taxId: "GSTIN29AAACA4321Q1ZV",
      billingAddress: "Apex Tower, MG Road, Bangalore, Karnataka",
      paymentTerms: "Net 30 days",
    },
    siteAddresses: [
      { label: "Commercial Site", address: "Outer Ring Road, Bangalore" },
    ],
    billingAddress: "Apex Tower, MG Road, Bangalore, Karnataka",
    communicationPreference: "email",
    createdAt: "2025-11-20T12:00:00.000Z",
    updatedAt: "2026-06-30T17:00:00.000Z",
  },
];

export const DEV_PROJECTS: Project[] = [
  {
    id: "proj-001",
    workspaceId: "ws-default",
    clientId: "cli-101",
    enquiryId: "enq-070",
    name: "Nila Residence",
    projectCode: "KAL-2024-001",
    projectType: "Luxury Residential Villa",
    status: "active",
    phase: "Construction",
    ownerId: "user-current",
    ownerName: "Arjun Mehta",
    location: "Trivandrum, Kerala",
    category: "RESIDENTIAL",
    description: "Nila Residence is a premium luxury villa project designed to combine modern architecture, sustainable living, and functional spaces. The project is currently progressing through the structural construction phase with continuous milestone tracking and real-time project updates.",
    budget: "₹ 12,0000",
    startDate: "2026-01-15",
    targetCompletionDate: "Dec 30, 2024",
    nextRequiredAction: "Client approval for joinery revision",
    upcomingDeadline: "Due in 2 days",
    paymentStatus: "Milestone 3 Paid · Milestone 4 Advance Pending",
    coverImageUrl: "/assets/projectbg.webp",
    thumbnailImageUrl: "/assets/projectbg.webp",
    progressPercent: 68,
    managerAvatarUrl:
      "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    teamMembers: [
      { id: "team-rk", name: "Ravi Kumar", initials: "RK" },
      { id: "team-ps", name: "Priya Shah", initials: "PS" },
      { id: "team-nl", name: "Nikhil Lal", initials: "NL" },
      { id: "team-dv", name: "Divya Varma", initials: "DV" },
    ],
    teamAdditionalCount: 12,
    milestones: [
      {
        id: "milestone-roof-slab",
        title: "Roof Slab Casting",
        dueDate: "2026-07-30",
        status: "pending",
        phase: "Construction",
      },
    ],
    recentActivity: [
      {
        id: "act-001",
        timestamp: "2026-07-21T10:15:00.000Z",
        actor: "Arjun Nair",
        actorRole: "Lead Architect",
        action: "Uploaded Structural Detail Rev 04",
        details: "Modified joinery details for master bedroom balcony.",
      },
    ],
    createdAt: "2026-01-15T10:00:00.000Z",
    updatedAt: "2026-07-21T10:15:00.000Z",
  },
  {
    id: "proj-002",
    workspaceId: "ws-default",
    clientId: "cli-102",
    enquiryId: "enq-075",
    name: "Azure Villa",
    projectCode: "KAL-2024-002",
    projectType: "Contemporary Beach Villa",
    status: "active",
    phase: "Construction",
    ownerId: "user-002",
    ownerName: "Priya Menon",
    location: "Calicut, Kerala",
    startDate: "2026-02-01",
    targetCompletionDate: "2026-12-15",
    nextRequiredAction: "Structural engineer site inspection report",
    upcomingDeadline: "Overdue 3 days",
    paymentStatus: "Phase 2 Paid · Pending Inspection",
    recentActivity: [
      {
        id: "act-002",
        timestamp: "2026-07-20T14:20:00.000Z",
        actor: "Priya Menon",
        actorRole: "Project Manager",
        action: "Logged Blocked Status",
        details: "Awaiting site engineer structural sign-off for foundation column load test.",
      },
    ],
    createdAt: "2026-02-01T09:00:00.000Z",
    updatedAt: "2026-07-20T14:20:00.000Z",
  },
  {
    id: "proj-003",
    workspaceId: "ws-default",
    clientId: "cli-103",
    enquiryId: "enq-081",
    name: "Greenfield Apartment",
    projectCode: "KAL-2024-003",
    projectType: "Residential Apartment Design",
    status: "active",
    phase: "Design development",
    ownerId: "user-003",
    ownerName: "Rahul Krishnan",
    location: "Thrissur, Kerala",
    startDate: "2026-03-10",
    targetCompletionDate: "2026-10-31",
    nextRequiredAction: "Finalize electrical & lighting drawing set",
    upcomingDeadline: "Due in 5 days",
    paymentStatus: "Phase 1 Paid",
    recentActivity: [
      {
        id: "act-003",
        timestamp: "2026-07-19T11:00:00.000Z",
        actor: "Rahul Krishnan",
        actorRole: "Senior Designer",
        action: "Updated Electrical Layout Draft",
        details: "Incorporated smart lighting switches.",
      },
    ],
    createdAt: "2026-03-10T10:00:00.000Z",
    updatedAt: "2026-07-19T11:00:00.000Z",
  },
  {
    id: "proj-004",
    workspaceId: "ws-default",
    clientId: "cli-102",
    enquiryId: "enq-089",
    name: "Calicut Retail Interior",
    projectCode: "KAL-2024-004",
    projectType: "Commercial Retail Store",
    status: "active",
    phase: "BOQ and procurement",
    ownerId: "user-004",
    ownerName: "Vikram R",
    location: "Calicut, Kerala",
    startDate: "2026-04-01",
    targetCompletionDate: "2026-09-30",
    nextRequiredAction: "Vendor quotation approval for HVAC",
    upcomingDeadline: "Due tomorrow",
    paymentStatus: "BOQ Advance Released",
    recentActivity: [
      {
        id: "act-004",
        timestamp: "2026-07-22T09:30:00.000Z",
        actor: "Vikram R",
        actorRole: "Estimator",
        action: "Submitted HVAC Vendor BOQ",
        details: "Obtained 3 competitive quotes.",
      },
    ],
    createdAt: "2026-04-01T10:00:00.000Z",
    updatedAt: "2026-07-22T09:30:00.000Z",
  },
  {
    id: "proj-005",
    workspaceId: "ws-default",
    clientId: "cli-104",
    enquiryId: "enq-094",
    name: "Harbour View Office",
    projectCode: "KAL-2024-005",
    projectType: "Commercial Office",
    status: "active",
    phase: "Approvals",
    ownerId: "user-current",
    ownerName: "Arjun Nair",
    location: "Kochi, Kerala",
    startDate: "2026-05-15",
    targetCompletionDate: "2026-12-31",
    nextRequiredAction: "Municipal sanction document filing",
    upcomingDeadline: "Due in 1 day",
    paymentStatus: "Retainer Paid",
    recentActivity: [
      {
        id: "act-005",
        timestamp: "2026-07-22T15:00:00.000Z",
        actor: "Arjun Nair",
        actorRole: "Lead Architect",
        action: "Prepared Corporation Sanction File",
        details: "Compiled fire clearance certificates.",
      },
    ],
    createdAt: "2026-05-15T11:00:00.000Z",
    updatedAt: "2026-07-22T15:00:00.000Z",
  },
  {
    id: "proj-006",
    workspaceId: "ws-default",
    clientId: "cli-101",
    enquiryId: "enq-070",
    name: "Palm Heights Penthouse",
    projectCode: "KAL-2024-006",
    projectType: "Luxury Penthouse",
    status: "completed",
    phase: "Handover",
    ownerId: "user-002",
    ownerName: "Priya Menon",
    location: "Thiruvananthapuram, Kerala",
    startDate: "2025-08-01",
    targetCompletionDate: "2026-06-30",
    nextRequiredAction: "Handover sign-off certificate",
    upcomingDeadline: "Completed June 2026",
    paymentStatus: "100% Settled",
    recentActivity: [
      {
        id: "act-006",
        timestamp: "2026-06-30T10:00:00.000Z",
        actor: "Priya Menon",
        actorRole: "Project Manager",
        action: "Final Handover Sign-off Completed",
        details: "Keys handed over to client.",
      },
    ],
    createdAt: "2025-08-01T10:00:00.000Z",
    updatedAt: "2026-06-30T10:00:00.000Z",
  },
  {
    id: "proj-007",
    name: "Skyline Heights Phase II",
    workspaceId: "ws-default",
    clientId: "cli-103",
    enquiryId: "enq-081",
    projectCode: "KAL-2024-007",
    projectType: "Residential Tower",
    status: "upcoming",
    phase: "Briefing",
    ownerId: "user-003",
    ownerName: "Anitha Das",
    location: "Thiruvananthapuram, Kerala",
    startDate: "2026-08-01",
    targetCompletionDate: "2027-04-30",
    nextRequiredAction: "Initial client requirement brief",
    upcomingDeadline: "Scheduled next week",
    paymentStatus: "Proposal Accepted",
    recentActivity: [],
    createdAt: "2026-07-01T10:00:00.000Z",
    updatedAt: "2026-07-01T10:00:00.000Z",
  },
  {
    id: "proj-008",
    name: "Marina Bay Suites",
    workspaceId: "ws-default",
    clientId: "cli-105",
    enquiryId: "enq-050",
    projectCode: "KAL-2024-008",
    projectType: "Hospitality Suites",
    status: "completed",
    phase: "Post-handover",
    ownerId: "user-current",
    ownerName: "Arjun Nair",
    location: "Kochi, Kerala",
    startDate: "2025-06-01",
    targetCompletionDate: "2026-05-15",
    nextRequiredAction: "Defect liability inspection",
    upcomingDeadline: "Completed May 2026",
    paymentStatus: "100% Settled",
    recentActivity: [],
    createdAt: "2025-06-01T10:00:00.000Z",
    updatedAt: "2026-05-15T10:00:00.000Z",
  },
  {
    id: "proj-009",
    name: "Highland Villa",
    workspaceId: "ws-default",
    clientId: "cli-101",
    enquiryId: "enq-070",
    projectCode: "KAL-2024-009",
    projectType: "Hillside Residence",
    status: "upcoming",
    phase: "Site verification",
    ownerId: "user-003",
    ownerName: "Anitha Das",
    location: "Munnar, Kerala",
    startDate: "2026-08-15",
    targetCompletionDate: "2027-03-31",
    nextRequiredAction: "Topographical survey team dispatch",
    upcomingDeadline: "Due in 4 days",
    paymentStatus: "Deposit Received",
    recentActivity: [],
    createdAt: "2026-07-10T10:00:00.000Z",
    updatedAt: "2026-07-10T10:00:00.000Z",
  },
  {
    id: "proj-010",
    name: "Coastal Resort Pavilion",
    workspaceId: "ws-default",
    clientId: "cli-105",
    enquiryId: "enq-050",
    projectCode: "KAL-2024-010",
    projectType: "Resort Pavilion",
    status: "on_hold",
    phase: "Approvals",
    ownerId: "user-004",
    ownerName: "Vikram R",
    location: "Bekal, Kerala",
    startDate: "2026-05-01",
    targetCompletionDate: "2026-11-30",
    nextRequiredAction: "Client requested project hold",
    upcomingDeadline: "On hold",
    paymentStatus: "Phase 1 Settled",
    recentActivity: [],
    createdAt: "2026-05-01T10:00:00.000Z",
    updatedAt: "2026-07-01T10:00:00.000Z",
  },
  {
    id: "proj-1",
    workspaceId: "ws-default",
    clientId: "cli-101",
    enquiryId: "enq-070",
    name: "Residence 24",
    projectCode: "PRJ-RES-24",
    projectType: "Luxury Contemporary Residence",
    status: "active",
    phase: "Concept approval",
    ownerId: "user-current",
    ownerName: "Arjun",
    location: "Panampilly Nagar, Kochi",
    startDate: "2026-02-01",
    targetCompletionDate: "2026-11-30",
    nextRequiredAction: "Client decision required on Concept Revision 03",
    upcomingDeadline: "Overdue 2 days",
    paymentStatus: "Milestone 1 Paid · Milestone 2 Advance Pending",
    recentActivity: [
      {
        id: "act-101",
        timestamp: "2026-07-18T10:15:00.000Z",
        actor: "Arjun",
        actorRole: "Lead Architect",
        action: "Uploaded Concept Revision 03 Drawing Set",
        details: "Includes modified structural layout for cantilevered terrace.",
      },
    ],
    createdAt: "2026-02-01T10:00:00.000Z",
    updatedAt: "2026-07-18T10:15:00.000Z",
  },
  {
    id: "proj-2",
    workspaceId: "ws-default",
    clientId: "cli-102",
    enquiryId: "enq-075",
    name: "Greenfield Villa",
    projectCode: "PRJ-GFV-02",
    projectType: "Tropical Villa Residence",
    status: "active",
    phase: "BOQ preparation",
    ownerId: "user-002",
    ownerName: "Rohit",
    location: "Greenfield Estate, Kottayam",
    startDate: "2026-03-15",
    targetCompletionDate: "2026-12-15",
    nextRequiredAction: "Complete missing material rates in structural BOQ",
    upcomingDeadline: "Today 5:00 PM",
    paymentStatus: "Advance Received",
    recentActivity: [
      {
        id: "act-102",
        timestamp: "2026-07-19T14:20:00.000Z",
        actor: "Rohit",
        actorRole: "Senior Designer",
        action: "Updated BOQ Revision 02 draft",
        details: "Added stone cladding specifications.",
      },
    ],
    createdAt: "2026-03-15T09:00:00.000Z",
    updatedAt: "2026-07-19T14:20:00.000Z",
  },
  {
    id: "proj-3",
    workspaceId: "ws-default",
    clientId: "cli-103",
    enquiryId: "enq-081",
    name: "Oak House",
    projectCode: "PRJ-OAK-03",
    projectType: "Heritage Residence Renovation",
    status: "upcoming",
    phase: "Feasibility & Kickoff",
    ownerId: "user-003",
    ownerName: "Vivek",
    location: "Hill View Colony, Thrissur",
    startDate: "2026-08-01",
    targetCompletionDate: "2027-01-31",
    nextRequiredAction: "Site feasibility inspection & boundary survey",
    upcomingDeadline: "Tomorrow 10:30 AM",
    paymentStatus: "Retainer Verified",
    recentActivity: [
      {
        id: "act-103",
        timestamp: "2026-07-19T11:00:00.000Z",
        actor: "Vivek",
        actorRole: "Site Engineer",
        action: "Scheduled Feasibility Site Visit",
        details: "Coordinated with client site engineer.",
      },
    ],
    createdAt: "2026-07-01T10:00:00.000Z",
    updatedAt: "2026-07-19T11:00:00.000Z",
  },
  {
    id: "proj-4",
    workspaceId: "ws-default",
    clientId: "cli-104",
    enquiryId: "enq-085",
    name: "Palm Springs Suite",
    projectCode: "PRJ-PSS-04",
    projectType: "Boutique Penthouse Interior",
    status: "on_hold",
    phase: "Working drawings",
    ownerId: "user-004",
    ownerName: "Priya",
    location: "Jubilee Hills, Hyderabad",
    startDate: "2026-04-10",
    targetCompletionDate: "2026-10-30",
    nextRequiredAction: "Structural sign-off pending owner review",
    upcomingDeadline: "Paused by Client",
    paymentStatus: "Phase 1 Paid",
    recentActivity: [
      {
        id: "act-104",
        timestamp: "2026-07-05T16:00:00.000Z",
        actor: "Priya",
        actorRole: "Architect",
        action: "Paused Project Status",
        details: "Client requested 2-week pause for municipal approval clarification.",
      },
    ],
    createdAt: "2026-04-10T11:00:00.000Z",
    updatedAt: "2026-07-05T16:00:00.000Z",
  },
  {
    id: "proj-5",
    workspaceId: "ws-default",
    clientId: "cli-105",
    enquiryId: "enq-050",
    name: "Skyline Corporate HQ Suite",
    projectCode: "PRJ-SCH-05",
    projectType: "Commercial Office Interior",
    status: "completed",
    phase: "Handover Complete",
    ownerId: "user-current",
    ownerName: "Arjun",
    location: "Apex Tower, Bangalore",
    startDate: "2025-11-01",
    targetCompletionDate: "2026-05-31",
    nextRequiredAction: "Warranty & snag list final audit complete",
    upcomingDeadline: "Handed Over May 2026",
    paymentStatus: "100% Settled",
    recentActivity: [
      {
        id: "act-105",
        timestamp: "2026-06-01T09:00:00.000Z",
        actor: "Arjun",
        actorRole: "Lead Architect",
        action: "Project Handover Certified",
        details: "Handover Certificate signed by Apex Realty Group.",
      },
    ],
    createdAt: "2025-11-01T10:00:00.000Z",
    updatedAt: "2026-06-01T09:00:00.000Z",
  },
];

export const DEV_ENQUIRIES: Enquiry[] = [
  {
    id: "enq-089",
    workspaceId: "ws-default",
    title: "ENQ-2026-089 Studio Villa Consultation",
    code: "ENQ-089",
    clientName: "Rahul Mehta",
    clientEmail: "rahul.mehta@gmail.com",
    clientPhone: "+91 98200 11223",
    organisationName: "Mehta Estates",
    projectType: "Residential Villa",
    location: "Calicut, Kerala",
    budget: "₹1.5 - ₹2.0 Cr",
    requirementsSummary: "Modern 4-bedroom villa with sustainable solar energy and courtyard design.",
    status: "qualified",
    createdAt: "2026-07-10T09:30:00.000Z",
    updatedAt: "2026-07-15T14:00:00.000Z",
  },
  {
    id: "enq-094",
    workspaceId: "ws-default",
    title: "ENQ-2026-094 Penthouse Interior Refresh",
    code: "ENQ-094",
    clientName: "Priya Sundaram",
    clientEmail: "priya.s@sundaram.org",
    clientPhone: "+91 97440 33445",
    organisationName: "Sundaram Holdings",
    projectType: "Penthouse Interior",
    location: "Kochi, Kerala",
    budget: "₹75 Lakhs",
    requirementsSummary: "Complete interior makeover for 3500 sq ft luxury penthouse suite.",
    status: "new",
    createdAt: "2026-07-18T16:00:00.000Z",
    updatedAt: "2026-07-18T16:00:00.000Z",
  },
];
