import {
  ActiveProjectItem,
  ApprovalRequestItem,
  CommitmentItem,
  HomeSchedulePreviewItem,
  PipelineItem,
  PriorityPreview,
  RecentActivityItem,
  RecentWorkItem,
} from "@/types/domain/home";

export const MOCK_NEEDS_ATTENTION_ITEMS: PriorityPreview[] = [
  {
    id: "na-1",
    tag: "Client approval overdue",
    projectName: "Skyline Heights",
    subtitle: "Concept Design Revision 03 awaiting client sign-off (2 days overdue)",
    state: "overdue",
    priorityLevel: "critical",
    dueText: "2 days overdue",
    dueDate: new Date(Date.now() - 2 * 86400000).toISOString(),
    assignedTo: "Arjun",
    actionLabel: "Review",
    destination: { availability: "available", route: "/projects" },
    financialExposure: 450000,
    isClientBlocking: true,
    isProjectBlocking: true,
    updatedAt: "2026-07-21T09:00:00Z",
  },
  {
    id: "na-2",
    tag: "Site issue requiring a decision",
    projectName: "Nila Residence",
    subtitle: "Soil load bearing variation identified during foundation excavation",
    state: "overdue",
    priorityLevel: "critical",
    dueText: "Immediate",
    dueDate: new Date(Date.now() - 86400000).toISOString(),
    assignedTo: "Sreejith",
    actionLabel: "Resolve",
    destination: { availability: "available", route: "/projects" },
    financialExposure: 200000,
    isClientBlocking: false,
    isProjectBlocking: true,
    updatedAt: "2026-07-21T08:30:00Z",
  },
  {
    id: "na-3",
    tag: "New enquiry awaiting response",
    projectName: "Anand Estate Villa",
    subtitle: "Client request for 3BHK interior design quote & site visit consultation",
    state: "due-today",
    priorityLevel: "high",
    dueText: "Due today",
    dueDate: new Date().toISOString(),
    assignedTo: "Arjun",
    actionLabel: "Reply",
    destination: { availability: "available", route: "/enquiries" },
    financialExposure: 250000,
    isClientBlocking: true,
    isProjectBlocking: false,
    updatedAt: "2026-07-22T08:00:00Z",
  },
  {
    id: "na-4",
    tag: "BOQ revision requested",
    projectName: "Palm Grove Residence",
    subtitle: "Client requested structural material rate adjustments for BOQ Rev 02",
    state: "due-today",
    priorityLevel: "high",
    dueText: "Due today",
    dueDate: new Date().toISOString(),
    assignedTo: "Rohit",
    actionLabel: "Resolve",
    destination: { availability: "available", route: "/tools" },
    financialExposure: 180000,
    isClientBlocking: false,
    isProjectBlocking: true,
    updatedAt: "2026-07-22T09:15:00Z",
  },
  {
    id: "na-5",
    tag: "Drawing submission due today",
    projectName: "Lakeview Apartments",
    subtitle: "Ground-floor electrical & plumbing working drawing layout set",
    state: "due-today",
    priorityLevel: "high",
    dueText: "Due 5:00 PM",
    dueDate: new Date().toISOString(),
    assignedTo: "Vivek",
    actionLabel: "Continue",
    destination: { availability: "available", route: "/documents" },
    financialExposure: 50000,
    isClientBlocking: false,
    isProjectBlocking: false,
    updatedAt: "2026-07-22T10:00:00Z",
  },
  {
    id: "na-6",
    tag: "Payment milestone pending",
    projectName: "Villa Azure",
    subtitle: "Phase 2 foundation milestone ₹3,10,000 payment verification",
    state: "pending",
    priorityLevel: "high",
    dueText: "Due tomorrow",
    dueDate: new Date(Date.now() + 86400000).toISOString(),
    assignedTo: "Anjali",
    actionLabel: "Approve",
    destination: { availability: "available", route: "/payments" },
    financialExposure: 310000,
    isClientBlocking: true,
    isProjectBlocking: false,
    updatedAt: "2026-07-20T16:00:00Z",
  },
  {
    id: "na-7",
    tag: "Upcoming meeting requiring preparation",
    projectName: "Greenfield Villa",
    subtitle: "Client milestone review & structural sign-off meeting at 3:00 PM",
    state: "pending",
    priorityLevel: "medium",
    dueText: "Today 3:00 PM",
    dueDate: new Date().toISOString(),
    assignedTo: "Arjun",
    actionLabel: "Review",
    destination: { availability: "available", route: "/calendar" },
    financialExposure: 0,
    isClientBlocking: false,
    isProjectBlocking: false,
    updatedAt: "2026-07-22T11:00:00Z",
  },
];

export const MOCK_RECENT_WORK_ITEMS: RecentWorkItem[] = [
  {
    id: "rec-1",
    projectName: "Skyline Heights",
    category: "BOQ Draft",
    subTitle: "Structural BOQ Rev 02",
    status: "Drafting in progress",
    updatedAt: "Updated 15 mins ago",
    actionLabel: "Continue",
    destination: { availability: "available", route: "/tools" },
  },
  {
    id: "rec-2",
    projectName: "Villa Azure",
    category: "Proposal",
    subTitle: "Interior Design Proposal",
    status: "Awaiting client review",
    updatedAt: "Updated 2 hours ago",
    actionLabel: "View Proposal",
    destination: { availability: "available", route: "/enquiries" },
  },
  {
    id: "rec-3",
    projectName: "Nila Residence",
    category: "Site Report",
    subTitle: "Foundation Quality Inspection",
    status: "Review required",
    updatedAt: "Updated yesterday",
    actionLabel: "Open Report",
    destination: { availability: "available", route: "/documents" },
  },
  {
    id: "rec-4",
    projectName: "Lakeview Apartments",
    category: "Drawing Set",
    subTitle: "Ground Floor Electrical Layout",
    status: "Draft ready for upload",
    updatedAt: "Updated 2 days ago",
    actionLabel: "Upload Drawing",
    destination: { availability: "available", route: "/documents" },
  },
];

export const MOCK_ACTIVE_PROJECTS: ActiveProjectItem[] = [
  {
    id: "proj-1",
    name: "Skyline Heights",
    clientName: "Rahul Menon",
    location: "Thiruvananthapuram",
    city: "Thiruvananthapuram",
    phase: "Construction",
    progressPercent: 65,
    health: "delayed",
    nextMilestone: "Foundation inspection",
    nextDeadline: "Today, 3:00 PM",
    currentActivity: "Ground-floor column casting",
    nextMilestoneDetails: {
      title: "Foundation inspection",
      date: "24 Jul",
    },
    attentionCount: 2,
    pendingApprovalsCount: 2,
    overdueTasksCount: 1,
    expectedPayment: "₹3.10L payment expected",
    expectedPaymentRaw: 310000,
    owner: "Arjun",
    ownerAvatar: "A",
    thumbnailUrl: "/assets/projects/anitha-menon-residence.png",
    statusState: "overdue",
    destination: { availability: "available", route: "/projects" },
  },
  {
    id: "proj-2",
    name: "Nila Residence",
    clientName: "Anjali Nair",
    location: "Kochi",
    city: "Kochi",
    phase: "Construction",
    progressPercent: 62,
    health: "on_track",
    nextMilestone: "Quality check inspection",
    nextDeadline: "Today, 11:30 AM",
    currentActivity: "Roof slab preparation",
    nextMilestoneDetails: {
      title: "Structural inspection",
      date: "24 Jul",
    },
    attentionCount: 2,
    pendingApprovalsCount: 1,
    overdueTasksCount: 0,
    expectedPayment: "₹1.80L payment expected",
    expectedPaymentRaw: 180000,
    owner: "Sreejith",
    ownerAvatar: "S",
    thumbnailUrl: "/assets/projects/greenfield-villa.png",
    statusState: "due-today",
    destination: { availability: "available", route: "/projects" },
  },
  {
    id: "proj-3",
    name: "Villa Azure",
    clientName: "Vikram Seth",
    location: "Calicut",
    city: "Calicut",
    phase: "Interior works",
    progressPercent: 80,
    health: "on_track",
    nextMilestone: "Material quality review",
    nextDeadline: "Tomorrow, 10:00 AM",
    currentActivity: "Custom joinery & flooring",
    nextMilestoneDetails: {
      title: "Material quality review",
      date: "28 Jul",
    },
    attentionCount: 0,
    pendingApprovalsCount: 0,
    overdueTasksCount: 0,
    expectedPayment: "₹4.50L payment expected",
    expectedPaymentRaw: 450000,
    owner: "Anjali",
    ownerAvatar: "A",
    thumbnailUrl: "/assets/projects/oak-house.png",
    statusState: "scheduled",
    destination: { availability: "available", route: "/projects" },
  },
  {
    id: "proj-4",
    name: "Palm Grove Residence",
    clientName: "Deepa Varma",
    location: "Kottayam",
    city: "Kottayam",
    phase: "Planning",
    progressPercent: 25,
    health: "blocked",
    nextMilestone: "BOQ rate completion",
    nextDeadline: "22 July, 5:00 PM",
    currentActivity: "Structural material rate verification",
    nextMilestoneDetails: {
      title: "BOQ rate completion",
      date: "30 Jul",
    },
    attentionCount: 3,
    pendingApprovalsCount: 1,
    overdueTasksCount: 2,
    expectedPayment: "₹2.20L payment expected",
    expectedPaymentRaw: 220000,
    owner: "Rohit",
    ownerAvatar: "R",
    thumbnailUrl: "/assets/projects/residence-24.png",
    statusState: "blocked",
    destination: { availability: "available", route: "/projects" },
  },
];

export const MOCK_SCHEDULE_PREVIEW_ITEMS: HomeSchedulePreviewItem[] = [
  {
    id: "sched-1",
    timeOrDate: "09:00 AM",
    title: "Cement OPC 53 delivery — 350 bags",
    projectName: "Skyline Apartments",
    typeChip: "delivery",
    participants: ["Vishnu R."],
    route: "/calendar",
    isUpcoming: false,
  },
  {
    id: "sched-2",
    timeOrDate: "11:30 AM",
    title: "Material quality inspection — TMT bars",
    projectName: "Skyline Heights",
    typeChip: "site-visit",
    participants: ["Arjun", "Sreejith"],
    route: "/calendar",
    isUpcoming: false,
  },
  {
    id: "sched-3",
    timeOrDate: "03:00 PM",
    title: "Foundation quality review",
    projectName: "Nila Residence",
    typeChip: "inspection",
    participants: ["Arjun", "Anjali"],
    route: "/calendar",
    isUpcoming: false,
  },
  {
    id: "sched-4-private",
    timeOrDate: "04:30 PM",
    title: "Internal financial strategy sync",
    projectName: "Kallisto Studio",
    typeChip: "private",
    isPrivate: true,
    participants: ["Arjun"],
    route: "/calendar",
    isUpcoming: false,
  },
  {
    id: "sched-5",
    timeOrDate: "Tomorrow",
    title: "PO-2214 approval deadline — Steel PF550",
    projectName: "Skyline Apartments",
    typeChip: "approval",
    participants: ["Vishnu R."],
    route: "/calendar",
    isUpcoming: true,
  },
  {
    id: "sched-6",
    timeOrDate: "Wednesday",
    title: "Vendor coordination call — Dispatch schedule",
    projectName: "Villa Azure",
    typeChip: "meeting",
    participants: ["Anjali", "Vikram"],
    route: "/calendar",
    isUpcoming: true,
  },
  {
    id: "sched-7",
    timeOrDate: "Thursday",
    title: "Milestone payment expected — ₹3,10,000",
    projectName: "Skyline Heights",
    typeChip: "payment",
    participants: ["Rahul Menon"],
    route: "/calendar",
    isUpcoming: true,
  },
];

export const MOCK_APPROVAL_REQUESTS: ApprovalRequestItem[] = [
  {
    id: "req-101",
    requestId: "REQ-101",
    requestType: "procurement",
    category: "procurement",
    projectName: "Skyline Apartments",
    requestedBy: "Vishnu R.",
    requestedDate: "3 January 2026",
    itemsSummary: "Cement OPC 53 — 100 bags, Steel FE500 — 100 kg",
    amountOrQuantities: "100 bags / 100 kg",
    amountRaw: 150000,
    neededByDate: "22 July 2026",
    status: "Awaiting approval",
    version: 1,
    updatedAt: "2026-07-21T08:00:00Z",
  },
  {
    id: "req-102",
    requestId: "REQ-102",
    requestType: "boq",
    category: "boq",
    projectName: "Skyline Heights",
    requestedBy: "Mohammed S.",
    requestedDate: "15 July 2026",
    itemsSummary: "Electrical & Plumbing BOQ Revision 02",
    amountOrQuantities: "₹3,10,000 total revision",
    amountRaw: 310000,
    neededByDate: "21 July 2026",
    status: "Awaiting approval",
    version: 1,
    updatedAt: "2026-07-21T08:15:00Z",
  },
  {
    id: "req-103",
    requestId: "REQ-103",
    requestType: "payment",
    category: "payments",
    projectName: "Villa Azure",
    requestedBy: "Anjali N.",
    requestedDate: "18 July 2026",
    itemsSummary: "Phase 2 Milestone Payment ₹3,10,000",
    amountOrQuantities: "₹3,10,000",
    amountRaw: 310000,
    neededByDate: "21 July 2026",
    status: "Awaiting approval",
    version: 1,
    updatedAt: "2026-07-21T08:30:00Z",
  },
  {
    id: "req-104",
    requestId: "REQ-104",
    requestType: "document",
    category: "documents",
    projectName: "Nila Residence",
    requestedBy: "Sreejith K.",
    requestedDate: "19 July 2026",
    itemsSummary: "Ground Floor Structural Drawing Rev 04",
    amountOrQuantities: "1 Drawing Set PDF",
    neededByDate: "23 July 2026",
    status: "Awaiting approval",
    version: 1,
    updatedAt: "2026-07-21T08:45:00Z",
  },
  {
    id: "req-105",
    requestId: "REQ-105",
    requestType: "variation",
    category: "boq",
    projectName: "Palm Grove Residence",
    requestedBy: "Rahul M.",
    requestedDate: "20 July 2026",
    itemsSummary: "Extra Structural Column Reinforcement",
    amountOrQuantities: "₹85,000 scope variation",
    amountRaw: 85000,
    neededByDate: "25 July 2026",
    status: "Awaiting approval",
    version: 1,
    updatedAt: "2026-07-21T09:00:00Z",
  },
];

export const MOCK_RECENT_ACTIVITIES: RecentActivityItem[] = [
  {
    id: "act-1",
    title: "BOQ approved",
    projectName: "Skyline Heights",
    actor: "Approved by Mohammed",
    timeAgo: "2 hours ago",
    category: "BOQ",
    iconType: "boq",
    route: "/documents",
  },
  {
    id: "act-2",
    title: "Site visit scheduled",
    projectName: "Villa Azure",
    actor: "Scheduled by Anjali",
    timeAgo: "5 hours ago",
    category: "Site Visit",
    iconType: "site",
    route: "/calendar",
  },
  {
    id: "act-3",
    title: "Task assigned — Electrical work",
    projectName: "Palm Grove Residence",
    actor: "Assigned to Rahul",
    timeAgo: "Yesterday",
    category: "Task",
    iconType: "task",
    route: "/projects",
  },
  {
    id: "act-4",
    title: "Document uploaded — Structural drawing",
    projectName: "Nila Residence",
    actor: "Uploaded by Sreejith",
    timeAgo: "Yesterday",
    category: "Document",
    iconType: "document",
    route: "/documents",
  },
  {
    id: "act-5",
    title: "Payment milestone verified — ₹1,80,000",
    projectName: "Greenfield Villa",
    actor: "Verified by Finance",
    timeAgo: "2 days ago",
    category: "Payment",
    iconType: "payment",
    route: "/payments",
  },
  {
    id: "act-6",
    title: "Enquiry converted to project",
    projectName: "Lakeview Apartments",
    actor: "Converted by Arjun",
    timeAgo: "3 days ago",
    category: "Project",
    iconType: "document",
    route: "/projects",
  },
];

export const MOCK_PIPELINE_ITEMS: PipelineItem[] = [
  {
    id: "pipe-1",
    title: "New enquiries awaiting response",
    countLabel: "4 enquiries",
    category: "Enquiries",
    destination: { availability: "available", route: "/enquiries" },
  },
  {
    id: "pipe-2",
    title: "Proposals awaiting client decision",
    countLabel: "2 proposals",
    category: "Proposals",
    destination: { availability: "available", route: "/enquiries" },
  },
  {
    id: "pipe-3",
    title: "Confirmed projects starting soon",
    countLabel: "1 project",
    category: "Projects",
    destination: { availability: "available", route: "/projects" },
  },
];

export const MOCK_COMMITMENT_ITEMS: CommitmentItem[] = [
  {
    id: "comm-1",
    title: "Payment milestone requiring attention",
    subtitle: "Palm Springs Interiors · Milestone 2 advance",
    category: "payment",
    dueLabel: "Pending review",
    destination: { availability: "available", route: "/payments" },
  },
  {
    id: "comm-2",
    title: "Upcoming site visit tomorrow",
    subtitle: "Oak House · 10:30 AM · Kottayam",
    category: "meeting",
    dueLabel: "Tomorrow 10:30 AM",
    destination: { availability: "available", route: "/calendar" },
  },
  {
    id: "comm-3",
    title: "Municipal approval deadline",
    subtitle: "Greenfield Villa · Structural sign-off package",
    category: "deadline",
    dueLabel: "In 3 days",
    destination: { availability: "available", route: "/calendar" },
  },
];
