import type { BackendProject } from "@/types/domain/backend-project";

export const DUMMY_BACKEND_PROJECTS: BackendProject[] = [
  {
    id: 1,
    projectName: "Nila Luxury Residence",
    projectType: "Luxury Residential Villa",
    buildingType: "Residential Villa (G+2)",
    projectCharacter: "pr",
    newConstructionOrRenovation: "New Construction",
    purposeOfProject: "Primary family residence with tropical modern architecture and infinity pool.",
    briefDescription: "A bespoke 4,200 sq.ft contemporary tropical residence situated on a scenic hilltop plot in Trivandrum. Features passive cooling, double-height living areas, timber louvers, and sustainable rainwater harvesting systems.",
    overView: "The project combines traditional Kerala architectural elements with clean modernist lines. Structural works are 70% complete with MEP rough-ins and plastering actively in progress.",
    providerIds: ["SP-0001", "SP-0002"],
    coverImageUrl: "/assets/projectbg.webp",
    sqArea: 4200,
    clientExpectedTimeline: "14 months",
    clientName: "Anoop Kumar",
    place: "Trivandrum, Kerala",
    estimatedOverallBudget: 12000000,
    createdAt: "2026-01-15T10:00:00.000Z",
    updatedAt: "2026-07-21T10:15:00.000Z",
    viewed: true,
    siteImages: [
      "/assets/projectbg.webp",
      "/assets/nila-hero.jpg",
      "/assets/nila-thumb1.jpg",
      "/assets/nila-thumb2.jpg",
      "/assets/nila-thumb3.jpg",
    ],
    inspirationImages: [
      { url: "/assets/nila-hero.jpg", alt: "Modern tropical facade" },
      { url: "/assets/nila-hero-modern.jpg", alt: "Living room double height" },
      { url: "/assets/project-banner.jpg", alt: "Courtyard and water feature" },
    ],
    projectDocuments: [
      { id: 101, name: "Architectural Drawings Set Rev 03.pdf", docImageUrl: "/assets/kallisto-drawing-approval-record.png", docType: "drawing", status: true, updatedAt: 1721556900 },
      { id: 102, name: "Structural Calculation & Foundation Report.pdf", docImageUrl: "/assets/manual.webp", docType: "structural", status: true, updatedAt: 1721038500 },
      { id: 103, name: "Approved BOQ & Material Specifications.pdf", docImageUrl: "/assets/quotation-retyping-workflow.png", docType: "boq", status: true, updatedAt: 1720519200 },
    ],
    projectScopes: [
      { id: 1, scope_name: "Civil & Structural Works", items: ["Foundation RCC raft & columns", "Slab casting level 1 & 2", "AAC block masonry"] },
      { id: 2, scope_name: "Finishes & Interior Fitout", items: ["Italian marble flooring", "Teak wood joinery & paneling", "Custom kitchen cabinetry"] },
      { id: 3, scope_name: "MEP & Automation", items: ["Concealed plumbing & drainage", "HVAC VRV ducted system", "KNX home automation lighting"] },
    ],
    requirements: [
      {
        id: "req-1",
        requirement_name: "Spatial & Functional Requirements",
        items: ["4 Master Suites with en-suite walk-in closets", "Open layout show kitchen + wet kitchen", "Home theatre with acoustic treatment", "Covered parking for 3 vehicles"],
        statuses: [true, true, true, true],
      },
      {
        id: "req-2",
        requirement_name: "Sustainability & Energy Efficiency",
        items: ["10kW Rooftop Solar PV installation", "Rainwater harvesting with 20kL sump", "Low-E double glazed thermal windows"],
        statuses: [true, true, false],
      },
    ],
    priorities: [
      { id: "pri-1", priority_name: "Natural Ventilation & Courtyard Integration", details: ["Cross breezes through central courtyard", "Operable louvers for monsoons"], statuses: [true, true], tags: [["High Priority", "Architecture"], ["Design"]] },
      { id: "pri-2", priority_name: "Premium Material Palette", details: ["Natural stone finishes", "Weatherproof exterior cladding"], statuses: [true, null], tags: [["Finishes"]] },
    ],
    familyMembers: [
      { familyId: "fam-1", clientId: "cli-101", name: "Anoop Kumar", age: 48, job: "Tech Entrepreneur", phone: "+91 98470 12345", relation: "Primary Client", familyMemberImgUrl: "/assets/arjun-avatar.jpg", description: "Enjoys open spaces and quiet study area." },
      { familyId: "fam-2", clientId: "cli-101", name: "Lekha Menon", age: 44, job: "Physician", phone: "+91 98470 12346", relation: "Spouse", familyMemberImgUrl: "/assets/priya-avatar.jpg", description: "Focused on functional kitchen and herbal garden." },
    ],
    projectClients: {
      client_id: "cli-101",
      name: "Anoop Kumar",
      email: "anoop@kumargroup.com",
      phone: "+91 98470 12345",
      occupation: "Tech Entrepreneur",
      location: "Trivandrum, Kerala",
      notes: "Prefers milestone-based reviews and WhatsApp communication for on-site progress photos.",
    },
    projectLifestyle: {
      entertaining_frequency: "Bi-weekly weekend dinners",
      work_from_home: "Both partners work hybrid from home",
      pets: "1 Golden Retriever",
      hobbies: "Gardening, reading, music listening",
    },
    projectApprovalProcess: {
      decision_makers: ["Anoop Kumar", "Lekha Menon"],
      approval_stages: ["Concept Approval (Done)", "Detailed Drawing Approval (Done)", "Material Sampling (Active)", "Handover & Snagging (Pending)"],
    },
    projectTechnical: {
      soil_testing_status: "Completed (Hard rock foundation at 2.4m)",
      structural_specifications: "RCC framed structure with M25 grade concrete and Fe500D steel",
      sustainability_goals: "Targeting GRIHA 4-star green building rating",
    },
    projectStatus: "ACTIVE",
    teamMembers: [
      { provider_id: "SP-0001", role: "Principal Architect", status: "active", notes: "Lead design sign-off" },
      { provider_id: "SP-0002", role: "Structural Engineer", status: "active", notes: "Site inspection coordinator" },
    ],
  },
  {
    id: 2,
    projectName: "Azure Oceanfront Villa",
    projectType: "Contemporary Beach Villa",
    buildingType: "Coastal Residential Villa (G+1)",
    projectCharacter: "pr",
    newConstructionOrRenovation: "New Construction",
    purposeOfProject: "Luxury coastal vacation home with panoramic Arabian Sea views.",
    briefDescription: "A 5,800 sq.ft contemporary sea-facing residence in Calicut, featuring marine-grade corrosion-resistant structural materials, cantilevered viewing decks, and salt-tolerant landscape design.",
    overView: "Foundation and structural shell completed. Framing of coastal glazing and infinity pool structural casting underway.",
    providerIds: ["SP-0001", "SP-0002"],
    coverImageUrl: "/assets/nila-hero.jpg",
    sqArea: 5800,
    clientExpectedTimeline: "16 months",
    clientName: "Riya Thomas",
    place: "Calicut, Kerala",
    estimatedOverallBudget: 25000000,
    createdAt: "2026-02-01T09:00:00.000Z",
    updatedAt: "2026-07-20T14:20:00.000Z",
    viewed: true,
    siteImages: [
      "/assets/nila-hero.jpg",
      "/assets/nila-hero-modern.jpg",
      "/assets/projectbg.webp",
    ],
    inspirationImages: [
      { url: "/assets/nila-hero.jpg", alt: "Coastal terrace infinity pool" },
      { url: "/assets/kallisto-scattered-section.webp", alt: "Floor plan flow" },
    ],
    projectDocuments: [
      { id: 201, name: "CRZ Coastal Regulation Zone Clearance.pdf", docImageUrl: "/assets/manual.webp", docType: "regulatory", status: true, updatedAt: 1720800000 },
      { id: 202, name: "Structural Marine Grade Spec Sheet.pdf", docImageUrl: "/assets/kallisto-drawing-approval-record.png", docType: "structural", status: true, updatedAt: 1721100000 },
    ],
    projectScopes: [
      { id: 4, scope_name: "Civil & Marine Substructure", items: ["Deep pile foundation with sulfate-resistant cement", "Waterproof basement & pool tank"] },
      { id: 5, scope_name: "Glazing & Facade", items: ["Schüco marine-grade hurricane glazed sliding systems", "Pre-cast GFRC louvers"] },
    ],
    requirements: [
      {
        id: "req-201",
        requirement_name: "Resilience & Security",
        items: ["Corrosion-proof hardware throughout", "Automated storm shutters", "Perimeter smart security sensors"],
        statuses: [true, true, true],
      },
    ],
    projectClients: {
      client_id: "cli-102",
      name: "Riya Thomas",
      email: "riya@thomasretail.com",
      phone: "+91 98950 67890",
      location: "Calicut, Kerala",
    },
    projectStatus: "ACTIVE",
    teamMembers: [
      { provider_id: "SP-0001", role: "Design Lead", status: "active", notes: "Coastal architecture expert" },
    ],
  },
  {
    id: 3,
    projectName: "Greenfield Urban Apartments",
    projectType: "Residential Apartment Complex",
    buildingType: "Multi-Unit Housing (B+G+8)",
    projectCharacter: "pr",
    newConstructionOrRenovation: "New Construction",
    purposeOfProject: "High-density sustainable urban living complex with 24 premium residential units.",
    briefDescription: "An eco-conscious urban multi-family residential building in Thrissur with shared rooftop gardens, solar microgrid, and EV charging bays for every apartment unit.",
    overView: "Detailed MEP and lighting layout drafts finalized. Structural floor slabs 4 of 8 cast.",
    providerIds: ["SP-0001", "SP-0003"],
    coverImageUrl: "/assets/nila-hero-modern.jpg",
    sqArea: 12500,
    clientExpectedTimeline: "24 months",
    clientName: "Nikhil Varma",
    place: "Thrissur, Kerala",
    estimatedOverallBudget: 48000000,
    createdAt: "2026-03-10T10:00:00.000Z",
    updatedAt: "2026-07-19T11:00:00.000Z",
    viewed: true,
    siteImages: [
      "/assets/nila-hero-modern.jpg",
      "/assets/project-banner.jpg",
    ],
    inspirationImages: [
      { url: "/assets/nila-hero-modern.jpg", alt: "Facade rendering" },
    ],
    projectDocuments: [
      { id: 301, name: "Town Planning Permit & Environmental NOC.pdf", docImageUrl: "/assets/manual.webp", docType: "permit", status: true, updatedAt: 1720000000 },
    ],
    projectScopes: [
      { id: 6, scope_name: "High-rise Civil Construction", items: ["Shear wall structural framing", "Post-tensioned slab casting"] },
    ],
    requirements: [
      {
        id: "req-301",
        requirement_name: "Community Amenities",
        items: ["Rooftop infinity lap pool", "Co-working resident lounge", "Dedicated fitness center"],
        statuses: [true, true, true],
      },
    ],
    projectClients: {
      client_id: "cli-103",
      name: "Nikhil Varma",
      email: "nikhil@varmaliving.com",
      phone: "+91 94470 54321",
      location: "Thrissur, Kerala",
    },
    projectStatus: "ACTIVE",
    teamMembers: [
      { provider_id: "SP-0001", role: "Lead Architect", status: "active", notes: "Urban development specialist" },
    ],
  },
  {
    id: 4,
    projectName: "Harbour View Corporate Hub",
    projectType: "Commercial Office & Retail",
    buildingType: "Commercial Grade-A Building (2B+G+5)",
    projectCharacter: "pr",
    newConstructionOrRenovation: "New Construction",
    purposeOfProject: "Modern commercial workspace with ground-floor boutique retail and rooftop dining.",
    briefDescription: "A landmark commercial development located at Marine Drive, Kochi, designed for corporate headquarters, co-working spaces, and high-street lifestyle retail.",
    overView: "Statutory Corporation approvals and fire clearance obtained. Substructure excavation underway.",
    providerIds: ["SP-0001", "SP-0004"],
    coverImageUrl: "/assets/project-banner.jpg",
    sqArea: 9400,
    clientExpectedTimeline: "18 months",
    clientName: "Ananya Sharma",
    place: "Kochi, Kerala",
    estimatedOverallBudget: 35000000,
    createdAt: "2026-04-12T11:00:00.000Z",
    updatedAt: "2026-07-22T15:00:00.000Z",
    viewed: true,
    siteImages: [
      "/assets/project-banner.jpg",
      "/assets/kallisto-scattered-section.webp",
    ],
    inspirationImages: [
      { url: "/assets/project-banner.jpg", alt: "Atrium elevation" },
    ],
    projectDocuments: [
      { id: 401, name: "Corporation Sanction & Fire NOC.pdf", docImageUrl: "/assets/kallisto-drawing-approval-record.png", docType: "permit", status: true, updatedAt: 1721600000 },
    ],
    projectScopes: [
      { id: 7, scope_name: "Core & Shell Execution", items: ["Composite steel & concrete framing", "High-performance curtain wall glazing"] },
    ],
    requirements: [
      {
        id: "req-401",
        requirement_name: "Commercial Performance",
        items: ["LEED Gold certification compliance", "High-speed destination-dispatch elevators"],
        statuses: [true, true],
      },
    ],
    projectClients: {
      client_id: "cli-104",
      name: "Ananya Sharma",
      email: "ananya@sharmaestates.com",
      phone: "+91 91234 56789",
      location: "Kochi, Kerala",
    },
    projectStatus: "ACTIVE",
    teamMembers: [
      { provider_id: "SP-0001", role: "Commercial Lead", status: "active", notes: "Lead commercial coordinator" },
    ],
  },
  {
    id: 5,
    projectName: "Skyline Corporate HQ Suite",
    projectType: "Corporate Office Interior",
    buildingType: "Commercial Office Interior Fitout",
    projectCharacter: "pr",
    newConstructionOrRenovation: "Interior Renovation",
    purposeOfProject: "Turnkey interior fitout for an executive corporate headquarters suite.",
    briefDescription: "A 6,200 sq.ft executive interior transformation in Bangalore with ergonomic acoustic workspaces, boardrooms with video conferencing wall, and custom executive cafeteria.",
    overView: "Snag list audit and final client defect inspection in progress for final handover.",
    providerIds: ["SP-0001"],
    coverImageUrl: "/assets/kallisto-scattered-section.webp",
    sqArea: 6200,
    clientExpectedTimeline: "6 months",
    clientName: "Rajesh Gupta",
    place: "Bangalore, Karnataka",
    estimatedOverallBudget: 18000000,
    createdAt: "2025-11-20T12:00:00.000Z",
    updatedAt: "2026-07-22T09:30:00.000Z",
    viewed: true,
    siteImages: [
      "/assets/kallisto-scattered-section.webp",
      "/assets/scattered.webp",
    ],
    inspirationImages: [
      { url: "/assets/kallisto-scattered-section.webp", alt: "Executive Boardroom" },
    ],
    projectDocuments: [
      { id: 501, name: "As-Built Drawings & Handover Package.pdf", docImageUrl: "/assets/quotation-retyping-workflow.png", docType: "handover", status: true, updatedAt: 1721600000 },
    ],
    projectScopes: [
      { id: 8, scope_name: "Interior Architecture & Finishes", items: ["Acoustic wall paneling", "Demountable glass partitions", "Custom ergonomic workstations"] },
    ],
    requirements: [
      {
        id: "req-501",
        requirement_name: "Workplace Tech & Ergonomics",
        items: ["BIFMA certified ergonomic seating", "Integrated Crestron room schedulers"],
        statuses: [true, true],
      },
    ],
    projectClients: {
      client_id: "cli-105",
      name: "Rajesh Gupta",
      email: "rajesh@apexrealty.com",
      phone: "+91 99887 65432",
      location: "Bangalore, Karnataka",
    },
    projectStatus: "ACTIVE",
    teamMembers: [
      { provider_id: "SP-0001", role: "Interior Lead", status: "active", notes: "Corporate workspace specialist" },
    ],
  },
  {
    id: 6,
    projectName: "Oakridge Heritage Estate",
    projectType: "Heritage Villa Renovation",
    buildingType: "Traditional Heritage Nalukettu (G+1)",
    projectCharacter: "pr",
    newConstructionOrRenovation: "Heritage Restoration",
    purposeOfProject: "Restoration and modern revival of an ancestral 100-year-old wooden estate.",
    briefDescription: "Careful conservation of historic timber framing, terracotta tile roofing, and brass detailing, fused with modern luxury bathrooms and climate-controlled living zones.",
    overView: "Fully completed and certified handover. 100% payments settled and warranties issued.",
    providerIds: ["SP-0001", "SP-0002"],
    coverImageUrl: "/assets/scattered.webp",
    sqArea: 3800,
    clientExpectedTimeline: "12 months",
    clientName: "Dr. Jacob Mathew",
    place: "Kottayam, Kerala",
    estimatedOverallBudget: 15000000,
    createdAt: "2025-01-10T10:00:00.000Z",
    updatedAt: "2026-04-30T16:00:00.000Z",
    viewed: true,
    siteImages: [
      "/assets/scattered.webp",
      "/assets/projectbg.webp",
    ],
    inspirationImages: [
      { url: "/assets/scattered.webp", alt: "Heritage courtyard" },
    ],
    projectDocuments: [
      { id: 601, name: "Handover Certificate & Warranty Card.pdf", docImageUrl: "/assets/manual.webp", docType: "handover", status: true, updatedAt: 1714483200 },
    ],
    projectScopes: [
      { id: 9, scope_name: "Restoration & Modernization", items: ["Structural timber treatment", "Traditional clay tile waterproofing", "Modern plumbing & electrical rewiring"] },
    ],
    requirements: [
      {
        id: "req-601",
        requirement_name: "Heritage Preservation",
        items: ["Preserve original carved entrance doorway", "Restore central Ankanam courtyard"],
        statuses: [true, true],
      },
    ],
    projectClients: {
      client_id: "cli-101",
      name: "Dr. Jacob Mathew",
      email: "jacob@oakridge.in",
      phone: "+91 94471 99887",
      location: "Kottayam, Kerala",
    },
    projectStatus: "COMPLETED",
    teamMembers: [
      { provider_id: "SP-0001", role: "Conservation Architect", status: "completed", notes: "Lead conservationist" },
    ],
  },
  {
    id: 7,
    projectName: "Highland Eco Retreat & Resort",
    projectType: "Hillside Eco Hospitality",
    buildingType: "Resort Cottages & Clubhouse",
    projectCharacter: "pr",
    newConstructionOrRenovation: "New Construction",
    purposeOfProject: "Sustainable boutique mountain resort nestled amidst tea plantations.",
    briefDescription: "12 prefabricated timber cottages, a cliffside infinity restaurant, and wellness spa designed to leave zero ecological footprint on the Munnar mountain slope.",
    overView: "Kickoff and site soil stabilization analysis completed. Detailed architectural package ready for client review.",
    providerIds: ["SP-0001"],
    coverImageUrl: "/assets/projectbg.webp",
    sqArea: 18000,
    clientExpectedTimeline: "20 months",
    clientName: "Verdant Escapes Ltd",
    place: "Munnar, Kerala",
    estimatedOverallBudget: 52000000,
    createdAt: "2026-07-01T10:00:00.000Z",
    updatedAt: "2026-07-25T10:00:00.000Z",
    viewed: true,
    siteImages: [
      "/assets/projectbg.webp",
      "/assets/nila-hero.jpg",
    ],
    inspirationImages: [
      { url: "/assets/projectbg.webp", alt: "Hillside Chalet Elevation" },
    ],
    projectDocuments: [
      { id: 701, name: "Eco-Sensitivity Assessment & Slope Analysis.pdf", docImageUrl: "/assets/manual.webp", docType: "report", status: true, updatedAt: 1721800000 },
    ],
    projectScopes: [
      { id: 10, scope_name: "Sustainable Hospitality Construction", items: ["Light gauge steel framing", "Modular timber cladding", "Off-grid micro-hydro and solar setup"] },
    ],
    requirements: [
      {
        id: "req-701",
        requirement_name: "Eco Guidelines",
        items: ["Zero concrete pouring on steep slope", "100% natural water stream preservation"],
        statuses: [true, true],
      },
    ],
    projectClients: {
      client_id: "cli-104",
      name: "Verdant Escapes Ltd",
      email: "projects@verdantescapes.com",
      phone: "+91 97450 11223",
      location: "Munnar, Kerala",
    },
    projectStatus: "UPCOMING",
    teamMembers: [
      { provider_id: "SP-0001", role: "Lead Eco Architect", status: "active", notes: "Mountain architecture expert" },
    ],
  },
  {
    id: 8,
    projectName: "Palm Grove Boutique Suites",
    projectType: "Boutique Residential Suites",
    buildingType: "Waterfront Guest Suites (G+1)",
    projectCharacter: "enq",
    newConstructionOrRenovation: "New Construction",
    purposeOfProject: "Boutique luxury lakefront guest suites along the backwaters.",
    briefDescription: "A 4,900 sq.ft contemporary backwater retreat in Alappuzha featuring private boat docking, open-air rainwater showers, and traditional thatched cabanas.",
    overView: "New client enquiry received. Preliminary feasibility study and concept sketch prepared for presentation.",
    providerIds: ["SP-0001"],
    coverImageUrl: "/assets/nila-hero.jpg",
    sqArea: 4900,
    clientExpectedTimeline: "12 months",
    clientName: "Siddharth Nair",
    place: "Alappuzha, Kerala",
    estimatedOverallBudget: 21000000,
    createdAt: "2026-08-01T10:00:00.000Z",
    updatedAt: "2026-08-20T14:00:00.000Z",
    viewed: false,
    siteImages: [
      "/assets/nila-hero.jpg",
      "/assets/nila-thumb1.jpg",
    ],
    inspirationImages: [
      { url: "/assets/nila-hero.jpg", alt: "Backwater facing suites" },
    ],
    projectDocuments: [
      { id: 801, name: "Site Survey & Water Level Report.pdf", docImageUrl: "/assets/manual.webp", docType: "survey", status: true, updatedAt: 1723500000 },
    ],
    projectScopes: [
      { id: 11, scope_name: "Backwater Hospitality", items: ["Piling on soft clay soil", "Timber deck boardwalks"] },
    ],
    requirements: [
      {
        id: "req-801",
        requirement_name: "Client Vision",
        items: ["Direct water views from all bedrooms", "Integrated solar water heaters"],
        statuses: [null, null],
      },
    ],
    projectClients: {
      client_id: "cli-106",
      name: "Siddharth Nair",
      email: "siddharth@palmgrove.in",
      phone: "+91 98951 44332",
      location: "Alappuzha, Kerala",
    },
    projectStatus: "UPCOMING",
    teamMembers: [
      { provider_id: "SP-0001", role: "Principal Architect", status: "pending", notes: "Awaiting formal proposal sign-off" },
    ],
  },
  {
    id: 9,
    projectName: "Cedar Valley Studio & Residence",
    projectType: "Artist Studio & Hillside Residence",
    buildingType: "Hillside Split-level Villa",
    projectCharacter: "enq",
    newConstructionOrRenovation: "New Construction",
    purposeOfProject: "Integrated pottery & painting studio with private residential quarters.",
    briefDescription: "A 2,800 sq.ft artistic retreat in Wayanad utilizing exposed rammed earth walls, north-facing skylights for painter's studio, and native stone masonry.",
    overView: "Enquiry in discussion stage with client to finalize site survey and topography contours.",
    providerIds: ["SP-0001"],
    coverImageUrl: "/assets/nila-hero-modern.jpg",
    sqArea: 2800,
    clientExpectedTimeline: "10 months",
    clientName: "Kavita Pillai",
    place: "Wayanad, Kerala",
    estimatedOverallBudget: 9500000,
    createdAt: "2026-08-05T12:00:00.000Z",
    updatedAt: "2026-08-22T09:00:00.000Z",
    viewed: true,
    siteImages: [
      "/assets/nila-hero-modern.jpg",
    ],
    inspirationImages: [
      { url: "/assets/nila-hero-modern.jpg", alt: "Artist studio double height" },
    ],
    projectDocuments: [
      { id: 901, name: "Wayanad Soil & Contour Survey.pdf", docImageUrl: "/assets/manual.webp", docType: "survey", status: true, updatedAt: 1723800000 },
    ],
    projectScopes: [
      { id: 12, scope_name: "Sustainable Earth Construction", items: ["Stabilized rammed earth walls", "Reclaimed terracotta roofing"] },
    ],
    requirements: [
      {
        id: "req-901",
        requirement_name: "Studio Specifications",
        items: ["North light studio windows", "Dedicated kiln venting room"],
        statuses: [true, null],
      },
    ],
    projectClients: {
      client_id: "cli-107",
      name: "Kavita Pillai",
      email: "kavita@cedarvalleyart.com",
      phone: "+91 94460 77889",
      location: "Wayanad, Kerala",
    },
    projectStatus: "UPCOMING",
    teamMembers: [
      { provider_id: "SP-0001", role: "Design Lead", status: "pending", notes: "Initial concept review" },
    ],
  },
  {
    id: 10,
    projectName: "Zenith Tech Park Fitout",
    projectType: "Corporate IT Workspace",
    buildingType: "Commercial IT Office Floor (Level 4)",
    projectCharacter: "pr",
    newConstructionOrRenovation: "Commercial Fitout",
    purposeOfProject: "High-density agile tech campus floor for 180 software engineers.",
    briefDescription: "A 14,000 sq.ft state-of-the-art office fitout in Infopark Kochi featuring acoustic focus pods, agile collaboration zones, and automated bio-centric circadian lighting.",
    overView: "HVAC ducting and raised access flooring 85% completed. Glass partitions installation underway.",
    providerIds: ["SP-0001", "SP-0003"],
    coverImageUrl: "/assets/project-banner.jpg",
    sqArea: 14000,
    clientExpectedTimeline: "5 months",
    clientName: "InnovateLabs Inc",
    place: "Kochi, Kerala",
    estimatedOverallBudget: 32000000,
    createdAt: "2026-05-01T08:00:00.000Z",
    updatedAt: "2026-08-25T16:00:00.000Z",
    viewed: true,
    siteImages: [
      "/assets/project-banner.jpg",
      "/assets/kallisto-scattered-section.webp",
    ],
    inspirationImages: [
      { url: "/assets/project-banner.jpg", alt: "Tech office workspace" },
    ],
    projectDocuments: [
      { id: 1001, name: "Infopark Fitout Guidelines Approval.pdf", docImageUrl: "/assets/quotation-retyping-workflow.png", docType: "permit", status: true, updatedAt: 1724000000 },
    ],
    projectScopes: [
      { id: 13, scope_name: "IT Workplace Execution", items: ["Cat6A 10Gbps structured cabling", "Precision cooling server room", "Acoustic ceiling baffles"] },
    ],
    requirements: [
      {
        id: "req-1001",
        requirement_name: "Technology & Power Backup",
        items: ["N+1 Redundant UPS power infrastructure", "Access controlled biometric security turnstiles"],
        statuses: [true, true],
      },
    ],
    projectClients: {
      client_id: "cli-108",
      name: "InnovateLabs Inc",
      email: "facilities@innovatelabs.com",
      phone: "+91 98460 33445",
      location: "Kochi, Kerala",
    },
    projectStatus: "ACTIVE",
    teamMembers: [
      { provider_id: "SP-0001", role: "Commercial Lead", status: "active", notes: "Tech campus fitout specialist" },
    ],
  },
];
