import type { BackendProject } from "@/types/domain/backend-project";

export const DUMMY_BACKEND_PROJECTS: BackendProject[] = [
  {
    id: 1,
    projectName: "Nila Luxury Residence",
    projectType: "Luxury Residential Villa",
    buildingType: "Residential Villa (G+2)",
    projectCharacter: "pr",
    newConstructionOrRenovation: "New Construction",
    purposeOfProject: "Primary family residence with tropical modern architecture and infinity pool.",
    briefDescription: "A bespoke 4,200 sq.ft contemporary tropical residence situated on a scenic hilltop plot in Trivandrum. Features passive cooling, double-height living areas, timber louvers, and sustainable rainwater harvesting systems.",
    overView: "The project combines traditional Kerala architectural elements with clean modernist lines. Structural works are 70% complete with MEP rough-ins and plastering actively in progress.",
    providerIds: ["SP-0001", "SP-0002"],
    coverImageUrl: "/assets/projectbg.webp",
    sqArea: 4200,
    clientExpectedTimeline: "14 months",
    clientName: "Anoop Kumar",
    place: "Trivandrum, Kerala",
    estimatedOverallBudget: 12000000,
    createdAt: "2026-01-15T10:00:00.000Z",
    updatedAt: "2026-07-21T10:15:00.000Z",
    viewed: true,
    siteImages: [
      "/assets/projectbg.webp",
      "/assets/nila-hero.jpg",
      "/assets/nila-thumb1.jpg",
      "/assets/nila-thumb2.jpg",
      "/assets/nila-thumb3.jpg",
    ],
    inspirationImages: [
      { url: "/assets/nila-hero.jpg", alt: "Modern tropical facade" },
      { url: "/assets/nila-hero-modern.jpg", alt: "Living room double height" },
      { url: "/assets/project-banner.jpg", alt: "Courtyard and water feature" },
    ],
    projectDocuments: [
      { id: 101, name: "Architectural Drawings Set Rev 03.pdf", docImageUrl: "/assets/kallisto-drawing-approval-record.png", docType: "drawing", status: true, updatedAt: 1721556900 },
      { id: 102, name: "Structural Calculation & Foundation Report.pdf", docImageUrl: "/assets/manual.webp", docType: "structural", status: true, updatedAt: 1721038500 },
      { id: 103, name: "Approved BOQ & Material Specifications.pdf", docImageUrl: "/assets/quotation-retyping-workflow.png", docType: "boq", status: true, updatedAt: 1720519200 },
    ],
    projectScopes: [
      { id: 1, scope_name: "Civil & Structural Works", items: ["Foundation RCC raft & columns", "Slab casting level 1 & 2", "AAC block masonry"] },
      { id: 2, scope_name: "Finishes & Interior Fitout", items: ["Italian marble flooring", "Teak wood joinery & paneling", "Custom kitchen cabinetry"] },
      { id: 3, scope_name: "MEP & Automation", items: ["Concealed plumbing & drainage", "HVAC VRV ducted system", "KNX home automation lighting"] },
    ],
    requirements: [
      {
        id: "req-1",
        requirement_name: "Spatial & Functional Requirements",
        items: ["4 Master Suites with en-suite walk-in closets", "Open layout show kitchen + wet kitchen", "Home theatre with acoustic treatment", "Covered parking for 3 vehicles"],
        statuses: [true, true, true, true],
      },
      {
        id: "req-2",
        requirement_name: "Sustainability & Energy Efficiency",
        items: ["10kW Rooftop Solar PV installation", "Rainwater harvesting with 20kL sump", "Low-E double glazed thermal windows"],
        statuses: [true, true, false],
      },
    ],
    priorities: [
      { id: "pri-1", priority_name: "Natural Ventilation & Courtyard Integration", details: ["Cross breezes through central courtyard", "Operable louvers for monsoons"], statuses: [true, true], tags: [["High Priority", "Architecture"], ["Design"]] },
      { id: "pri-2", priority_name: "Premium Material Palette", details: ["Natural stone finishes", "Weatherproof exterior cladding"], statuses: [true, null], tags: [["Finishes"]] },
    ],
    familyMembers: [
      { familyId: "fam-1", clientId: "cli-101", name: "Anoop Kumar", age: 48, job: "Tech Entrepreneur", phone: "+91 98470 12345", relation: "Primary Client", familyMemberImgUrl: "/assets/arjun-avatar.jpg", description: "Enjoys open spaces and quiet study area." },
      { familyId: "fam-2", clientId: "cli-101", name: "Lekha Menon", age: 44, job: "Physician", phone: "+91 98470 12346", relation: "Spouse", familyMemberImgUrl: "/assets/priya-avatar.jpg", description: "Focused on functional kitchen and herbal garden." },
    ],
    projectClients: {
      client_id: "cli-101",
      name: "Anoop Kumar",
      email: "anoop@kumargroup.com",
      phone: "+91 98470 12345",
      occupation: "Tech Entrepreneur",
      location: "Trivandrum, Kerala",
      notes: "Prefers milestone-based reviews and WhatsApp communication for on-site progress photos.",
    },
    projectLifestyle: {
      entertaining_frequency: "Bi-weekly weekend dinners",
      work_from_home: "Both partners work hybrid from home",
      pets: "1 Golden Retriever",
      hobbies: "Gardening, reading, music listening",
    },
    projectApprovalProcess: {
      decision_makers: ["Anoop Kumar", "Lekha Menon"],
      approval_stages: ["Concept Approval (Done)", "Detailed Drawing Approval (Done)", "Material Sampling (Active)", "Handover & Snagging (Pending)"],
    },
    projectTechnical: {
      soil_testing_status: "Completed (Hard rock foundation at 2.4m)",
      structural_specifications: "RCC framed structure with M25 grade concrete and Fe500D steel",
      sustainability_goals: "Targeting GRIHA 4-star green building rating",
    },
    projectStatus: "ACTIVE",
    progressPercent: 70,
    teamMembers: [
      { provider_id: "SP-0001", role: "Principal Architect", status: "active", notes: "Lead design sign-off" },
      { provider_id: "SP-0002", role: "Structural Engineer", status: "active", notes: "Site inspection coordinator" },
    ],
  },
  {
    id: 2,
    projectName: "Azure Oceanfront Villa",
    projectType: "Contemporary Beach Villa",
    buildingType: "Coastal Residential Villa (G+1)",
    projectCharacter: "pr",
    newConstructionOrRenovation: "New Construction",
    purposeOfProject: "Luxury coastal vacation home with panoramic Arabian Sea views.",
    briefDescription: "A 5,800 sq.ft contemporary sea-facing residence in Calicut, featuring marine-grade corrosion-resistant structural materials, cantilevered viewing decks, and salt-tolerant landscape design.",
    overView: "Foundation and structural shell completed. Framing of coastal glazing and infinity pool structural casting underway.",
    providerIds: ["SP-0001", "SP-0002"],
    coverImageUrl: "/assets/nila-hero.jpg",
    sqArea: 5800,
    clientExpectedTimeline: "16 months",
    clientName: "Riya Thomas",
    place: "Calicut, Kerala",
    estimatedOverallBudget: 25000000,
    createdAt: "2026-02-01T09:00:00.000Z",
    updatedAt: "2026-07-20T14:20:00.000Z",
    viewed: true,
    siteImages: [
      "/assets/nila-hero.jpg",
      "/assets/nila-hero-modern.jpg",
      "/assets/projectbg.webp",
    ],
    inspirationImages: [
      { url: "/assets/nila-hero.jpg", alt: "Coastal terrace infinity pool" },
      { url: "/assets/kallisto-scattered-section.webp", alt: "Floor plan flow" },
    ],
    projectDocuments: [
      { id: 201, name: "CRZ Coastal Regulation Zone Clearance.pdf", docImageUrl: "/assets/manual.webp", docType: "regulatory", status: true, updatedAt: 1720800000 },
      { id: 202, name: "Structural Marine Grade Spec Sheet.pdf", docImageUrl: "/assets/kallisto-drawing-approval-record.png", docType: "structural", status: true, updatedAt: 1721100000 },
    ],
    projectScopes: [
      { id: 4, scope_name: "Civil & Marine Substructure", items: ["Deep pile foundation with sulfate-resistant cement", "Waterproof basement & pool tank"] },
      { id: 5, scope_name: "Glazing & Facade", items: ["Schüco marine-grade hurricane glazed sliding systems", "Pre-cast GFRC louvers"] },
    ],
    requirements: [
      {
        id: "req-201",
        requirement_name: "Resilience & Security",
        items: ["Corrosion-proof hardware throughout", "Automated storm shutters", "Perimeter smart security sensors"],
        statuses: [true, true, true],
      },
    ],
    projectClients: {
      client_id: "cli-102",
      name: "Riya Thomas",
      email: "riya@thomasretail.com",
      phone: "+91 98950 67890",
      location: "Calicut, Kerala",
    },
    projectStatus: "ACTIVE",
    progressPercent: 45,
    teamMembers: [
      { provider_id: "SP-0001", role: "Design Lead", status: "active", notes: "Coastal architecture expert" },
    ],
  },
  {
    id: 3,
    projectName: "Greenfield Urban Apartments",
    projectType: "Residential Apartment Complex",
    buildingType: "Multi-Unit Housing (B+G+8)",
    projectCharacter: "pr",
    newConstructionOrRenovation: "New Construction",
    purposeOfProject: "High-density sustainable urban living complex with 24 premium residential units.",
    briefDescription: "An eco-conscious urban multi-family residential building in Thrissur with shared rooftop gardens, solar microgrid, and EV charging bays for every apartment unit.",
    overView: "Detailed MEP and lighting layout drafts finalized. Structural floor slabs 4 of 8 cast.",
    providerIds: ["SP-0001", "SP-0003"],
    coverImageUrl: "/assets/nila-hero-modern.jpg",
    sqArea: 12500,
    clientExpectedTimeline: "24 months",
    clientName: "Nikhil Varma",
    place: "Thrissur, Kerala",
    estimatedOverallBudget: 48000000,
    createdAt: "2026-03-10T10:00:00.000Z",
    updatedAt: "2026-07-19T11:00:00.000Z",
    viewed: true,
    siteImages: [
      "/assets/nila-hero-modern.jpg",
      "/assets/project-banner.jpg",
    ],
    inspirationImages: [
      { url: "/assets/nila-hero-modern.jpg", alt: "Facade rendering" },
    ],
    projectDocuments: [
      { id: 301, name: "Town Planning Permit & Environmental NOC.pdf", docImageUrl: "/assets/manual.webp", docType: "permit", status: true, updatedAt: 1720000000 },
    ],
    projectScopes: [
      { id: 6, scope_name: "High-rise Civil Construction", items: ["Shear wall structural framing", "Post-tensioned slab casting"] },
    ],
    requirements: [
      {
        id: "req-301",
        requirement_name: "Community Amenities",
        items: ["Rooftop infinity lap pool", "Co-working resident lounge", "Dedicated fitness center"],
        statuses: [true, true, true],
      },
    ],
    projectClients: {
      client_id: "cli-103",
      name: "Nikhil Varma",
      email: "nikhil@varmaliving.com",
      phone: "+91 94470 54321",
      location: "Thrissur, Kerala",
    },
    projectStatus: "ACTIVE",
    progressPercent: 50,
    teamMembers: [
      { provider_id: "SP-0001", role: "Lead Architect", status: "active", notes: "Urban development specialist" },
    ],
  },
  {
    id: 4,
    projectName: "Harbour View Corporate Hub",
    projectType: "Commercial Office & Retail",
    buildingType: "Commercial Grade-A Building (2B+G+5)",
    projectCharacter: "pr",
    newConstructionOrRenovation: "New Construction",
    purposeOfProject: "Modern commercial workspace with ground-floor boutique retail and rooftop dining.",
    briefDescription: "A landmark commercial development located at Marine Drive, Kochi, designed for corporate headquarters, co-working spaces, and high-street lifestyle retail.",
    overView: "Statutory Corporation approvals and fire clearance obtained. Substructure excavation underway.",
    providerIds: ["SP-0001", "SP-0004"],
    coverImageUrl: "/assets/project-banner.jpg",
    sqArea: 9400,
    clientExpectedTimeline: "18 months",
    clientName: "Ananya Sharma",
    place: "Kochi, Kerala",
    estimatedOverallBudget: 35000000,
    createdAt: "2026-04-12T11:00:00.000Z",
    updatedAt: "2026-07-22T15:00:00.000Z",
    viewed: true,
    siteImages: [
      "/assets/project-banner.jpg",
      "/assets/kallisto-scattered-section.webp",
    ],
    inspirationImages: [
      { url: "/assets/project-banner.jpg", alt: "Atrium elevation" },
    ],
    projectDocuments: [
      { id: 401, name: "Corporation Sanction & Fire NOC.pdf", docImageUrl: "/assets/kallisto-drawing-approval-record.png", docType: "permit", status: true, updatedAt: 1721600000 },
    ],
    projectScopes: [
      { id: 7, scope_name: "Core & Shell Execution", items: ["Composite steel & concrete framing", "High-performance curtain wall glazing"] },
    ],
    requirements: [
      {
        id: "req-401",
        requirement_name: "Commercial Performance",
        items: ["LEED Gold certification compliance", "High-speed destination-dispatch elevators"],
        statuses: [true, true],
      },
    ],
    projectClients: {
      client_id: "cli-104",
      name: "Ananya Sharma",
      email: "ananya@sharmaestates.com",
      phone: "+91 91234 56789",
      location: "Kochi, Kerala",
    },
    projectStatus: "ACTIVE",
    progressPercent: 28,
    teamMembers: [
      { provider_id: "SP-0001", role: "Commercial Lead", status: "active", notes: "Lead commercial coordinator" },
    ],
  },
  {
    id: 5,
    projectName: "Skyline Corporate HQ Suite",
    projectType: "Corporate Office Interior",
    buildingType: "Commercial Office Interior Fitout",
    projectCharacter: "pr",
    newConstructionOrRenovation: "Interior Renovation",
    purposeOfProject: "Turnkey interior fitout for an executive corporate headquarters suite.",
    briefDescription: "A 6,200 sq.ft executive interior transformation in Bangalore with ergonomic acoustic workspaces, boardrooms with video conferencing wall, and custom executive cafeteria.",
    overView: "Snag list audit and final client defect inspection in progress for final handover.",
    providerIds: ["SP-0001"],
    coverImageUrl: "/assets/kallisto-scattered-section.webp",
    sqArea: 6200,
    clientExpectedTimeline: "6 months",
    clientName: "Rajesh Gupta",
    place: "Bangalore, Karnataka",
    estimatedOverallBudget: 18000000,
    createdAt: "2025-11-20T12:00:00.000Z",
    updatedAt: "2026-07-22T09:30:00.000Z",
    viewed: true,
    siteImages: [
      "/assets/kallisto-scattered-section.webp",
      "/assets/scattered.webp",
    ],
    inspirationImages: [
      { url: "/assets/kallisto-scattered-section.webp", alt: "Executive Boardroom" },
    ],
    projectDocuments: [
      { id: 501, name: "As-Built Drawings & Handover Package.pdf", docImageUrl: "/assets/quotation-retyping-workflow.png", docType: "handover", status: true, updatedAt: 1721600000 },
    ],
    projectScopes: [
      { id: 8, scope_name: "Interior Architecture & Finishes", items: ["Acoustic wall paneling", "Demountable glass partitions", "Custom ergonomic workstations"] },
    ],
    requirements: [
      {
        id: "req-501",
        requirement_name: "Workplace Tech & Ergonomics",
        items: ["BIFMA certified ergonomic seating", "Integrated Crestron room schedulers"],
        statuses: [true, true],
      },
    ],
    projectClients: {
      client_id: "cli-105",
      name: "Rajesh Gupta",
      email: "rajesh@apexrealty.com",
      phone: "+91 99887 65432",
      location: "Bangalore, Karnataka",
    },
    projectStatus: "ACTIVE",
    progressPercent: 92,
    teamMembers: [
      { provider_id: "SP-0001", role: "Interior Lead", status: "active", notes: "Corporate workspace specialist" },
    ],
  },
  {
    id: 6,
    projectName: "Oakridge Heritage Estate",
    projectType: "Heritage Villa Renovation",
    buildingType: "Traditional Heritage Nalukettu (G+1)",
    projectCharacter: "pr",
    newConstructionOrRenovation: "Heritage Restoration",
    purposeOfProject: "Restoration and modern revival of an ancestral 100-year-old wooden estate.",
    briefDescription: "Careful conservation of historic timber framing, terracotta tile roofing, and brass detailing, fused with modern luxury bathrooms and climate-controlled living zones.",
    overView: "Fully completed and certified handover. 100% payments settled and warranties issued.",
    providerIds: ["SP-0001", "SP-0002"],
    coverImageUrl: "/assets/scattered.webp",
    sqArea: 3800,
    clientExpectedTimeline: "12 months",
    clientName: "Dr. Jacob Mathew",
    place: "Kottayam, Kerala",
    estimatedOverallBudget: 15000000,
    createdAt: "2025-01-10T10:00:00.000Z",
    updatedAt: "2026-04-30T16:00:00.000Z",
    viewed: true,
    siteImages: [
      "/assets/scattered.webp",
      "/assets/projectbg.webp",
    ],
    inspirationImages: [
      { url: "/assets/scattered.webp", alt: "Heritage courtyard" },
    ],
    projectDocuments: [
      { id: 601, name: "Handover Certificate & Warranty Card.pdf", docImageUrl: "/assets/manual.webp", docType: "handover", status: true, updatedAt: 1714483200 },
    ],
    projectScopes: [
      { id: 9, scope_name: "Restoration & Modernization", items: ["Structural timber treatment", "Traditional clay tile waterproofing", "Modern plumbing & electrical rewiring"] },
    ],
    requirements: [
      {
        id: "req-601",
        requirement_name: "Heritage Preservation",
        items: ["Preserve original carved entrance doorway", "Restore central Ankanam courtyard"],
        statuses: [true, true],
      },
    ],
    projectClients: {
      client_id: "cli-101",
      name: "Dr. Jacob Mathew",
      email: "jacob@oakridge.in",
      phone: "+91 94471 99887",
      location: "Kottayam, Kerala",
    },
    projectStatus: "COMPLETED",
    progressPercent: 100,
    teamMembers: [
      { provider_id: "SP-0001", role: "Conservation Architect", status: "completed", notes: "Lead conservationist" },
    ],
  },
  {
    id: 7,
    projectName: "Highland Eco Retreat & Resort",
    projectType: "Hillside Eco Hospitality",
    buildingType: "Resort Cottages & Clubhouse",
    projectCharacter: "pr",
    newConstructionOrRenovation: "New Construction",
    purposeOfProject: "Sustainable boutique mountain resort nestled amidst tea plantations.",
    briefDescription: "12 prefabricated timber cottages, a cliffside infinity restaurant, and wellness spa designed to leave zero ecological footprint on the Munnar mountain slope.",
    overView: "Kickoff and site soil stabilization analysis completed. Detailed architectural package ready for client review.",
    providerIds: ["SP-0001"],
    coverImageUrl: "/assets/projectbg.webp",
    sqArea: 18000,
    clientExpectedTimeline: "20 months",
    clientName: "Verdant Escapes Ltd",
    place: "Munnar, Kerala",
    estimatedOverallBudget: 52000000,
    createdAt: "2026-07-01T10:00:00.000Z",
    updatedAt: "2026-07-25T10:00:00.000Z",
    viewed: true,
    siteImages: [
      "/assets/projectbg.webp",
      "/assets/nila-hero.jpg",
    ],
    inspirationImages: [
      { url: "/assets/projectbg.webp", alt: "Hillside Chalet Elevation" },
    ],
    projectDocuments: [
      { id: 701, name: "Eco-Sensitivity Assessment & Slope Analysis.pdf", docImageUrl: "/assets/manual.webp", docType: "report", status: true, updatedAt: 1721800000 },
    ],
    projectScopes: [
      { id: 10, scope_name: "Sustainable Hospitality Construction", items: ["Light gauge steel framing", "Modular timber cladding", "Off-grid micro-hydro and solar setup"] },
    ],
    requirements: [
      {
        id: "req-701",
        requirement_name: "Eco Guidelines",
        items: ["Zero concrete pouring on steep slope", "100% natural water stream preservation"],
        statuses: [true, true],
      },
    ],
    projectClients: {
      client_id: "cli-104",
      name: "Verdant Escapes Ltd",
      email: "projects@verdantescapes.com",
      phone: "+91 97450 11223",
      location: "Munnar, Kerala",
    },
    projectStatus: "UPCOMING",
    progressPercent: 15,
    teamMembers: [
      { provider_id: "SP-0001", role: "Lead Eco Architect", status: "active", notes: "Mountain architecture expert" },
    ],
  },
  {
    id: 8,
    projectName: "Palm Grove Boutique Suites",
    projectType: "Boutique Residential Suites",
    buildingType: "Waterfront Guest Suites (G+1)",
    projectCharacter: "enq",
    newConstructionOrRenovation: "New Construction",
    purposeOfProject: "Boutique luxury lakefront guest suites along the backwaters.",
    briefDescription: "A 4,900 sq.ft contemporary backwater retreat in Alappuzha featuring private boat docking, open-air rainwater showers, and traditional thatched cabanas.",
    overView: "New client enquiry received. Preliminary feasibility study and concept sketch prepared for presentation.",
    providerIds: ["SP-0001"],
    coverImageUrl: "/assets/nila-hero.jpg",
    sqArea: 4900,
    clientExpectedTimeline: "12 months",
    clientName: "Siddharth Nair",
    place: "Alappuzha, Kerala",
    estimatedOverallBudget: 21000000,
    createdAt: "2026-08-01T10:00:00.000Z",
    updatedAt: "2026-08-20T14:00:00.000Z",
    viewed: false,
    stage: "new",
    status: "needs_attention",
    source: "website",
    enquiryRef: "ENQ-2026-0486",
    priority: "high",
    isNew: true,
    owner: "Arjun",
    tags: ["hospitality", "waterfront", "alappuzha"],
    nextAction: {
      type: "review_enquiry",
      label: "Review enquiry",
      dueAt: "2026-08-25T18:00:00.000Z",
      state: "urgent",
    },
    siteImages: [
      "/assets/nila-hero.jpg",
      "/assets/nila-thumb1.jpg",
    ],
    inspirationImages: [
      { url: "/assets/nila-hero.jpg", alt: "Backwater facing suites" },
    ],
    projectDocuments: [
      { id: 801, name: "Site Survey & Water Level Report.pdf", docImageUrl: "/assets/manual.webp", docType: "survey", status: true, updatedAt: 1723500000 },
    ],
    projectScopes: [
      { id: 11, scope_name: "Backwater Hospitality", items: ["Piling on soft clay soil", "Timber deck boardwalks"] },
    ],
    requirements: [
      {
        id: "req-801",
        requirement_name: "Client Vision",
        items: ["Direct water views from all bedrooms", "Integrated solar water heaters"],
        statuses: [null, null],
      },
    ],
    projectClients: {
      client_id: "cli-106",
      name: "Siddharth Nair",
      email: "siddharth@palmgrove.in",
      phone: "+91 98951 44332",
      location: "Alappuzha, Kerala",
    },
    projectStatus: "UPCOMING",
    progressPercent: 0,
    teamMembers: [
      { provider_id: "SP-0001", role: "Principal Architect", status: "pending", notes: "Awaiting formal proposal sign-off" },
    ],
  },
  {
    id: 9,
    projectName: "Cedar Valley Studio & Residence",
    projectType: "Artist Studio & Hillside Residence",
    buildingType: "Hillside Split-level Villa",
    projectCharacter: "enq",
    newConstructionOrRenovation: "New Construction",
    purposeOfProject: "Integrated pottery & painting studio with private residential quarters.",
    briefDescription: "A 2,800 sq.ft artistic retreat in Wayanad utilizing exposed rammed earth walls, north-facing skylights for painter's studio, and native stone masonry.",
    overView: "Enquiry in discussion stage with client to finalize site survey and topography contours.",
    providerIds: ["SP-0001"],
    coverImageUrl: "/assets/nila-hero-modern.jpg",
    sqArea: 2800,
    clientExpectedTimeline: "10 months",
    clientName: "Kavita Pillai",
    place: "Wayanad, Kerala",
    estimatedOverallBudget: 9500000,
    createdAt: "2026-08-05T12:00:00.000Z",
    updatedAt: "2026-08-22T09:00:00.000Z",
    viewed: true,
    stage: "consultation",
    status: "active",
    source: "partner",
    enquiryRef: "ENQ-2026-0487",
    priority: "medium",
    isNew: false,
    owner: "Anjali",
    tags: ["residential", "eco", "wayanad"],
    nextAction: {
      type: "schedule_consultation",
      label: "Schedule consultation",
      dueAt: "2026-08-28T10:00:00.000Z",
      state: "scheduled",
    },
    siteImages: [
      "/assets/nila-hero-modern.jpg",
    ],
    inspirationImages: [
      { url: "/assets/nila-hero-modern.jpg", alt: "Artist studio double height" },
    ],
    projectDocuments: [
      { id: 901, name: "Wayanad Soil & Contour Survey.pdf", docImageUrl: "/assets/manual.webp", docType: "survey", status: true, updatedAt: 1723800000 },
    ],
    projectScopes: [
      { id: 12, scope_name: "Sustainable Earth Construction", items: ["Stabilized rammed earth walls", "Reclaimed terracotta roofing"] },
    ],
    requirements: [
      {
        id: "req-901",
        requirement_name: "Studio Specifications",
        items: ["North light studio windows", "Dedicated kiln venting room"],
        statuses: [true, null],
      },
    ],
    projectClients: {
      client_id: "cli-107",
      name: "Kavita Pillai",
      email: "kavita@cedarvalleyart.com",
      phone: "+91 94460 77889",
      location: "Wayanad, Kerala",
    },
    projectStatus: "UPCOMING",
    progressPercent: 0,
    teamMembers: [
      { provider_id: "SP-0001", role: "Design Lead", status: "pending", notes: "Initial concept review" },
    ],
  },
  {
    id: 11,
    projectName: "Villa Elegance Fit-out",
    projectType: "Residential",
    buildingType: "Luxury Villa (G+2)",
    projectCharacter: "enq",
    newConstructionOrRenovation: "Interior Fit-out",
    purposeOfProject: "Turnkey luxury residential fit-out with contemporary open layout.",
    briefDescription: "Comprehensive luxury fit-out for a 3,400 sq.ft private residence in Kochi. Includes double-height living room acoustic treatment, designer show kitchen, and automated climate control.",
    overView: "Client requested technical clarification regarding MEP trunking and marble flooring lead times.",
    providerIds: ["SP-0001"],
    coverImageUrl: "/assets/projects/greenfield-villa.png",
    sqArea: 3400,
    clientExpectedTimeline: "6 months",
    clientName: "Ananya Builders",
    place: "Kochi, Kerala",
    estimatedOverallBudget: 4500000,
    createdAt: "2026-08-10T10:45:00.000Z",
    updatedAt: "2026-08-21T16:20:00.000Z",
    viewed: true,
    stage: "clarification",
    status: "needs_attention",
    source: "website",
    enquiryRef: "ENQ-2026-0488",
    priority: "high",
    isNew: true,
    owner: "Arjun",
    tags: ["villa", "luxury", "kochi"],
    nextAction: {
      type: "request_clarification",
      label: "Request clarification",
      dueAt: "2026-08-24T17:00:00.000Z",
      state: "urgent",
    },
    siteImages: ["/assets/projects/greenfield-villa.png"],
    inspirationImages: [{ url: "/assets/nila-hero.jpg", alt: "Living room double height" }],
    projectDocuments: [
      { id: 1101, name: "Villa Floor Layouts Rev 01.pdf", docImageUrl: "/assets/kallisto-drawing-approval-record.png", docType: "drawing", status: true, updatedAt: 1723700000 },
    ],
    projectScopes: [
      { id: 14, scope_name: "Interior Architecture", items: ["Acoustic wall panelling", "Modular kitchen joinery", "Italian marble polishing"] },
    ],
    requirements: [
      {
        id: "req-1101",
        requirement_name: "Finishing Standards",
        items: ["Imported Statuario marble in living zone", "Concealed ducted VRV air conditioning"],
        statuses: [true, false],
      },
    ],
    projectClients: {
      client_id: "cli-111",
      name: "Ananya Builders",
      email: "projects@ananyabuilders.in",
      phone: "+91 98471 22334",
      location: "Kochi, Kerala",
    },
    projectStatus: "UPCOMING",
    progressPercent: 0,
    teamMembers: [
      { provider_id: "SP-0001", role: "Design Director", status: "pending", notes: "Clarification in review" },
    ],
  },
  {
    id: 12,
    projectName: "West Coast Eco Retreat & Cabins",
    projectType: "Hospitality",
    buildingType: "Resort Cottages & Clubhouse",
    projectCharacter: "enq",
    newConstructionOrRenovation: "New Construction",
    purposeOfProject: "Sustainable boutique mountain resort with hillside timber chalets.",
    briefDescription: "Masterplan design and architectural documentation for 8 modular timber cabins and central dining pavilion in Munnar with passive solar heating.",
    overView: "Draft proposal with preliminary milestone schedule submitted for client commercial evaluation.",
    providerIds: ["SP-0001"],
    coverImageUrl: "/assets/projectbg.webp",
    sqArea: 6500,
    clientExpectedTimeline: "14 months",
    clientName: "West Coast Retreats",
    place: "Munnar, Kerala",
    estimatedOverallBudget: 8500000,
    createdAt: "2026-08-11T11:00:00.000Z",
    updatedAt: "2026-08-22T14:30:00.000Z",
    viewed: true,
    stage: "proposal",
    status: "active",
    source: "referral",
    enquiryRef: "ENQ-2026-0489",
    priority: "high",
    isNew: false,
    owner: "Arjun",
    tags: ["resort", "timber", "munnar"],
    nextAction: {
      type: "prepare_proposal",
      label: "Prepare proposal",
      dueAt: "2026-08-29T12:00:00.000Z",
      state: "scheduled",
    },
    siteImages: ["/assets/projectbg.webp"],
    inspirationImages: [{ url: "/assets/projectbg.webp", alt: "Hillside cottage" }],
    projectDocuments: [
      { id: 1201, name: "Eco Sensitive Contour Plan.pdf", docImageUrl: "/assets/manual.webp", docType: "survey", status: true, updatedAt: 1723800000 },
    ],
    projectScopes: [
      { id: 15, scope_name: "Modular Prefab Assembly", items: ["Treated pine timber cladding", "Off-grid micro-solar grid"] },
    ],
    requirements: [
      {
        id: "req-1201",
        requirement_name: "Eco Footprint",
        items: ["Zero concrete pouring on steep slope", "Rainwater percolation trenches"],
        statuses: [true, true],
      },
    ],
    projectClients: {
      client_id: "cli-112",
      name: "West Coast Retreats",
      email: "invest@westcoastretreats.com",
      phone: "+91 97450 88990",
      location: "Munnar, Kerala",
    },
    projectStatus: "UPCOMING",
    progressPercent: 0,
    teamMembers: [
      { provider_id: "SP-0001", role: "Principal Architect", status: "pending", notes: "Proposal submitted" },
    ],
  },
  {
    id: 13,
    projectName: "Coastal Café & Artisan Roastery",
    projectType: "Hospitality",
    buildingType: "Commercial Café Fit-out",
    projectCharacter: "enq",
    newConstructionOrRenovation: "Interior Renovation",
    purposeOfProject: "Boutique beachside specialty coffee roastery and open-kitchen bakery.",
    briefDescription: "A 1,600 sq.ft beachfront café in Calicut featuring exposed micro-cement surfaces, reclaimed wood seating, and ocean-facing outdoor pergolas.",
    overView: "Feasibility and zoning clearance validated. Scope and commercial requirements confirmed.",
    providerIds: ["SP-0001"],
    coverImageUrl: "/assets/projects/anitha-menon-residence.png",
    sqArea: 1600,
    clientExpectedTimeline: "3 months",
    clientName: "Brew District",
    place: "Calicut, Kerala",
    estimatedOverallBudget: 1800000,
    createdAt: "2026-08-12T09:15:00.000Z",
    updatedAt: "2026-08-20T11:00:00.000Z",
    viewed: true,
    stage: "qualified",
    status: "active",
    source: "direct",
    enquiryRef: "ENQ-2026-0490",
    priority: "medium",
    isNew: false,
    owner: "Anjali",
    tags: ["hospitality", "cafe", "calicut"],
    nextAction: {
      type: "consultation",
      label: "Consultation",
      dueAt: "2026-08-26T11:00:00.000Z",
      state: "scheduled",
    },
    siteImages: ["/assets/projects/anitha-menon-residence.png"],
    inspirationImages: [{ url: "/assets/studio/boq-rate-analysis-flatlay.jpg", alt: "Cafe layout" }],
    projectDocuments: [
      { id: 1301, name: "Health & Fire Commercial Clearance.pdf", docImageUrl: "/assets/manual.webp", docType: "permit", status: true, updatedAt: 1723600000 },
    ],
    projectScopes: [
      { id: 16, scope_name: "Commercial Fit-out", items: ["Espresso bar counter joinery", "Exhaust hood ducting", "Acoustic ceiling baffles"] },
    ],
    requirements: [
      {
        id: "req-1301",
        requirement_name: "Customer Experience",
        items: ["Beachfront glass fold-away windows", "High-traffic slip-resistant flooring"],
        statuses: [true, true],
      },
    ],
    projectClients: {
      client_id: "cli-113",
      name: "Brew District",
      email: "hello@brewdistrict.in",
      phone: "+91 98461 44556",
      location: "Calicut, Kerala",
    },
    projectStatus: "UPCOMING",
    progressPercent: 0,
    teamMembers: [
      { provider_id: "SP-0001", role: "Interior Lead", status: "pending", notes: "Consultation scheduled" },
    ],
  },
  {
    id: 14,
    projectName: "Meridian Apartment Block Planning",
    projectType: "Multi-Family",
    buildingType: "Apartment Complex (G+4)",
    projectCharacter: "enq",
    newConstructionOrRenovation: "New Construction",
    purposeOfProject: "Mid-rise residential apartment block featuring 12 spacious 3BHK units.",
    briefDescription: "Comprehensive structural layout and town planning approval drawings for a residential apartment community in Trivandrum.",
    overView: "Initial zoning and FAR calculations approved. Awaiting client confirmation on amenity inclusions.",
    providerIds: ["SP-0001"],
    coverImageUrl: "/assets/projects/residence-24.png",
    sqArea: 12000,
    clientExpectedTimeline: "18 months",
    clientName: "Meridian Developers",
    place: "Trivandrum, Kerala",
    estimatedOverallBudget: 68000000,
    createdAt: "2026-08-13T14:20:00.000Z",
    updatedAt: "2026-08-23T09:40:00.000Z",
    viewed: true,
    stage: "qualified",
    status: "active",
    source: "franchise",
    enquiryRef: "ENQ-2026-0491",
    priority: "medium",
    isNew: false,
    owner: "Arjun",
    tags: ["multi_family", "housing", "trivandrum"],
    nextAction: {
      type: "follow_up",
      label: "Follow up",
      dueAt: "2026-08-27T15:00:00.000Z",
      state: "scheduled",
    },
    siteImages: ["/assets/projects/residence-24.png"],
    inspirationImages: [{ url: "/assets/nila-hero-modern.jpg", alt: "Multi-family facade" }],
    projectDocuments: [
      { id: 1401, name: "Town Planning Masterplan Rev 02.pdf", docImageUrl: "/assets/kallisto-drawing-approval-record.png", docType: "permit", status: true, updatedAt: 1723900000 },
    ],
    projectScopes: [
      { id: 17, scope_name: "Town Planning & Shell", items: ["FAR compliance study", "Lift shaft structural engineering"] },
    ],
    requirements: [
      {
        id: "req-1401",
        requirement_name: "Community Amenities",
        items: ["Covered ground-level stilt parking", "Rooftop common recreation room"],
        statuses: [true, false],
      },
    ],
    projectClients: {
      client_id: "cli-114",
      name: "Meridian Developers",
      email: "contact@meridiandevelopers.com",
      phone: "+91 94470 66778",
      location: "Trivandrum, Kerala",
    },
    projectStatus: "UPCOMING",
    progressPercent: 0,
    teamMembers: [
      { provider_id: "SP-0001", role: "Principal Architect", status: "pending", notes: "Follow up scheduled" },
    ],
  },
  {
    id: 15,
    projectName: "Lakeside Pavilion & Landscape Masterplan",
    projectType: "Landscape",
    buildingType: "Outdoor Living & Pavilion",
    projectCharacter: "enq",
    newConstructionOrRenovation: "New Construction",
    purposeOfProject: "Integrated landscape architecture with sunken seating and native water bio-pool.",
    briefDescription: "A 5,200 sq.ft private estate landscape design in Thrissur with permeable paving, micro-climate native plantation, and timber dining deck.",
    overView: "Proposal accepted by client. Contract executed and transitioned to active delivery.",
    providerIds: ["SP-0001"],
    coverImageUrl: "/assets/projects/oak-house.png",
    sqArea: 5200,
    clientExpectedTimeline: "4 months",
    clientName: "Lakeside Villas",
    place: "Thrissur, Kerala",
    estimatedOverallBudget: 1500000,
    createdAt: "2026-07-15T12:00:00.000Z",
    updatedAt: "2026-08-18T10:00:00.000Z",
    viewed: true,
    stage: "won",
    status: "active",
    source: "website",
    enquiryRef: "ENQ-2026-0492",
    priority: "low",
    isNew: false,
    owner: "Arjun",
    tags: ["landscape", "residential", "thrissur"],
    nextAction: {
      type: "convert_to_project",
      label: "Convert to project",
      state: "ready",
    },
    siteImages: ["/assets/projects/oak-house.png"],
    inspirationImages: [{ url: "/assets/projectbg.webp", alt: "Deck and garden" }],
    projectDocuments: [
      { id: 1501, name: "Approved Landscape Concept & BOQ.pdf", docImageUrl: "/assets/quotation-retyping-workflow.png", docType: "boq", status: true, updatedAt: 1722800000 },
    ],
    projectScopes: [
      { id: 18, scope_name: "Hardscape & Planting", items: ["Natural Kerala laterite stone walls", "Automated drip irrigation system"] },
    ],
    requirements: [
      {
        id: "req-1501",
        requirement_name: "Water Ecology",
        items: ["Zero chemical bio-filtration pond", "Indigenous fruit and butterfly garden"],
        statuses: [true, true],
      },
    ],
    projectClients: {
      client_id: "cli-115",
      name: "Lakeside Villas",
      email: "estate@lakesidevillas.in",
      phone: "+91 98475 33221",
      location: "Thrissur, Kerala",
    },
    projectStatus: "COMPLETED",
    progressPercent: 100,
    teamMembers: [
      { provider_id: "SP-0001", role: "Landscape Lead", status: "completed", notes: "Contract signed" },
    ],
  },
  {
    id: 16,
    projectName: "Heritage Nalukettu Courtyard Revival",
    projectType: "Residential",
    buildingType: "Traditional Heritage Courtyard",
    projectCharacter: "enq",
    newConstructionOrRenovation: "Heritage Restoration",
    purposeOfProject: "Ancestral courtyard restoration and modern MEP retrofit.",
    briefDescription: "Conservation of vintage timber work and copper roofing with modern concealed drainage in Kottayam.",
    overView: "All scope items negotiated, approved and signed off. Won and handed over to construction.",
    providerIds: ["SP-0001"],
    coverImageUrl: "/assets/scattered.webp",
    sqArea: 3400,
    clientExpectedTimeline: "8 months",
    clientName: "Dr. Jacob Mathew",
    place: "Kottayam, Kerala",
    estimatedOverallBudget: 2800000,
    createdAt: "2026-07-02T10:00:00.000Z",
    updatedAt: "2026-08-15T14:00:00.000Z",
    viewed: true,
    stage: "won",
    status: "completed",
    source: "partner",
    enquiryRef: "ENQ-2026-0493",
    priority: "low",
    isNew: false,
    owner: "Anjali",
    tags: ["heritage", "restoration", "kottayam"],
    nextAction: {
      type: "convert_to_project",
      label: "Completed sign-off",
      state: "completed",
    },
    siteImages: ["/assets/scattered.webp"],
    inspirationImages: [{ url: "/assets/scattered.webp", alt: "Traditional roof tile joinery" }],
    projectDocuments: [
      { id: 1601, name: "Structural Timber Restoration Guide.pdf", docImageUrl: "/assets/manual.webp", docType: "structural", status: true, updatedAt: 1722000000 },
    ],
    projectScopes: [
      { id: 19, scope_name: "Timber Treatment", items: ["Termite non-toxic fumigation", "Brass hardware restoration"] },
    ],
    requirements: [
      {
        id: "req-1601",
        requirement_name: "Preservation Rules",
        items: ["Keep central Ankanam rainwater flow", "Conceal all high-voltage cabling"],
        statuses: [true, true],
      },
    ],
    projectClients: {
      client_id: "cli-116",
      name: "Dr. Jacob Mathew",
      email: "jacob@naluketturevival.com",
      phone: "+91 94471 88223",
      location: "Kottayam, Kerala",
    },
    projectStatus: "COMPLETED",
    progressPercent: 100,
    teamMembers: [
      { provider_id: "SP-0001", role: "Conservationist", status: "completed", notes: "Handover executed" },
    ],
  },
  {
    id: 17,
    projectName: "Urban Thread Concept Boutique",
    projectType: "Retail",
    buildingType: "Retail Showroom",
    projectCharacter: "enq",
    newConstructionOrRenovation: "Commercial Fit-out",
    purposeOfProject: "High-street designer apparel flagship retail boutique.",
    briefDescription: "Concept design for a 2,100 sq.ft retail store in Chennai featuring bespoke brass display racks and custom track lighting.",
    overView: "Client decided to defer expansion due to mall lease renegotiation.",
    providerIds: ["SP-0001"],
    coverImageUrl: "/assets/project-banner.jpg",
    sqArea: 2100,
    clientExpectedTimeline: "3 months",
    clientName: "Urban Thread Apparel",
    place: "Chennai, Tamil Nadu",
    estimatedOverallBudget: 2200000,
    createdAt: "2026-06-20T11:00:00.000Z",
    updatedAt: "2026-07-28T16:00:00.000Z",
    viewed: true,
    stage: "lost",
    status: "completed",
    source: "referral",
    enquiryRef: "ENQ-2026-0494",
    priority: "low",
    isNew: false,
    owner: "Arjun",
    tags: ["retail", "fashion", "chennai"],
    nextAction: {
      type: "mark_as_lost",
      label: "Marked as lost",
      state: "completed",
    },
    siteImages: ["/assets/project-banner.jpg"],
    inspirationImages: [{ url: "/assets/studio/project-estimates-flatlay.jpg", alt: "Retail layout" }],
    projectDocuments: [
      { id: 1701, name: "Mall Guidelines & Space Allocation.pdf", docImageUrl: "/assets/manual.webp", docType: "permit", status: false, updatedAt: 1721500000 },
    ],
    projectScopes: [
      { id: 20, scope_name: "Store Interiors", items: ["Bespoke brass clothing display racks", "Fitting room acoustic drapes"] },
    ],
    requirements: [
      {
        id: "req-1701",
        requirement_name: "Commercial Brand Vibe",
        items: ["Monochrome terrazzo flooring", "High CRI 95 museum-grade lighting"],
        statuses: [true, false],
      },
    ],
    projectClients: {
      client_id: "cli-117",
      name: "Urban Thread Apparel",
      email: "retail@urbanthread.com",
      phone: "+91 99401 55667",
      location: "Chennai, Tamil Nadu",
    },
    projectStatus: "COMPLETED",
    progressPercent: 0,
    teamMembers: [
      { provider_id: "SP-0001", role: "Retail Architect", status: "completed", notes: "Closed - Lease postponed" },
    ],
  },
  {
    id: 18,
    projectName: "FlexiWork Tech Hub Floor II",
    projectType: "Commercial",
    buildingType: "Commercial IT Office",
    projectCharacter: "enq",
    newConstructionOrRenovation: "Commercial Fit-out",
    purposeOfProject: "Expansion floor with meeting pods and open hot-desks.",
    briefDescription: "A 4,800 sq.ft workspace interior in Bengaluru with acoustic ceiling baffles and access controlled doors.",
    overView: "Client opted for existing tenant space instead of new fit-out.",
    providerIds: ["SP-0001"],
    coverImageUrl: "/assets/nila-hero-modern.jpg",
    sqArea: 4800,
    clientExpectedTimeline: "4 months",
    clientName: "FlexiWork Systems",
    place: "Bengaluru, Karnataka",
    estimatedOverallBudget: 4200000,
    createdAt: "2026-06-15T09:30:00.000Z",
    updatedAt: "2026-07-25T11:20:00.000Z",
    viewed: true,
    stage: "lost",
    status: "archived",
    source: "direct",
    enquiryRef: "ENQ-2026-0495",
    priority: "low",
    isNew: false,
    owner: "Anjali",
    tags: ["commercial", "office", "bengaluru"],
    nextAction: {
      type: "mark_as_lost",
      label: "Archived",
      state: "completed",
    },
    siteImages: ["/assets/nila-hero-modern.jpg"],
    inspirationImages: [{ url: "/assets/studio/visualisations-flatlay.jpg", alt: "Office floor" }],
    projectDocuments: [
      { id: 1801, name: "Floorplate AutoCAD Drawing.pdf", docImageUrl: "/assets/kallisto-drawing-approval-record.png", docType: "drawing", status: true, updatedAt: 1721000000 },
    ],
    projectScopes: [
      { id: 21, scope_name: "Acoustic Partitioning", items: ["Double glazed soundproof meeting pods", "Modular raised flooring"] },
    ],
    requirements: [
      {
        id: "req-1801",
        requirement_name: "Agile Workspace",
        items: ["60 Sit-to-stand motorized desks", "High-speed Ethernet redundancy"],
        statuses: [true, true],
      },
    ],
    projectClients: {
      client_id: "cli-118",
      name: "FlexiWork Systems",
      email: "facilities@flexiwork.co",
      phone: "+91 98860 11223",
      location: "Bengaluru, Karnataka",
    },
    projectStatus: "COMPLETED",
    progressPercent: 0,
    teamMembers: [
      { provider_id: "SP-0001", role: "Commercial Lead", status: "completed", notes: "Closed - Space deferred" },
    ],
  },
  {
    id: 10,
    projectName: "Zenith Tech Park Fitout",
    projectType: "Corporate IT Workspace",
    buildingType: "Commercial IT Office Floor (Level 4)",
    projectCharacter: "pr",
    newConstructionOrRenovation: "Commercial Fitout",
    purposeOfProject: "High-density agile tech campus floor for 180 software engineers.",
    briefDescription: "A 14,000 sq.ft state-of-the-art office fitout in Infopark Kochi featuring acoustic focus pods, agile collaboration zones, and automated bio-centric circadian lighting.",
    overView: "HVAC ducting and raised access flooring 85% completed. Glass partitions installation underway.",
    providerIds: ["SP-0001", "SP-0003"],
    coverImageUrl: "/assets/project-banner.jpg",
    sqArea: 14000,
    clientExpectedTimeline: "5 months",
    clientName: "InnovateLabs Inc",
    place: "Kochi, Kerala",
    estimatedOverallBudget: 32000000,
    createdAt: "2026-05-01T08:00:00.000Z",
    updatedAt: "2026-08-25T16:00:00.000Z",
    viewed: true,
    siteImages: [
      "/assets/project-banner.jpg",
      "/assets/kallisto-scattered-section.webp",
    ],
    inspirationImages: [
      { url: "/assets/project-banner.jpg", alt: "Tech office workspace" },
    ],
    projectDocuments: [
      { id: 1001, name: "Infopark Fitout Guidelines Approval.pdf", docImageUrl: "/assets/quotation-retyping-workflow.png", docType: "permit", status: true, updatedAt: 1724000000 },
    ],
    projectScopes: [
      { id: 13, scope_name: "IT Workplace Execution", items: ["Cat6A 10Gbps structured cabling", "Precision cooling server room", "Acoustic ceiling baffles"] },
    ],
    requirements: [
      {
        id: "req-1001",
        requirement_name: "Technology & Power Backup",
        items: ["N+1 Redundant UPS power infrastructure", "Access controlled biometric security turnstiles"],
        statuses: [true, true],
      },
    ],
    projectClients: {
      client_id: "cli-108",
      name: "InnovateLabs Inc",
      email: "facilities@innovatelabs.com",
      phone: "+91 98460 33445",
      location: "Kochi, Kerala",
    },
    projectStatus: "ACTIVE",
    progressPercent: 75,
    teamMembers: [
      { provider_id: "SP-0001", role: "Commercial Lead", status: "active", notes: "Tech campus fitout specialist" },
    ],
  },
];
