import type { HubWorkspaceData } from "../types/hub.types";

export const HUB_MOCK_WORKSPACE_DATA: HubWorkspaceData = {
  projects: [
    { id: "nila-residence", name: "Nila Residence" },
    { id: "lake-house", name: "Lake House" },
  ],
  metrics: [
    { label: "Active requests", value: "4" },
    { label: "Quotes received", value: "11" },
    { label: "Orders in progress", value: "3" },
    { label: "Delivery issues", value: "1", tone: "warning" },
  ],
  pipeline: [
    {
      id: "requirements",
      label: "Requirements",
      countLabel: "4 requests",
      valueLabel: "₹8.4L",
    },
    {
      id: "quotations",
      label: "Quotations",
      countLabel: "11 quotes",
      valueLabel: "₹7.9L",
    },
    {
      id: "approval",
      label: "Approval",
      countLabel: "2 pending",
      valueLabel: "₹3.2L",
    },
    {
      id: "ordered",
      label: "Ordered",
      countLabel: "3 orders",
      valueLabel: "₹4.6L",
    },
    {
      id: "delivered",
      label: "Delivered",
      countLabel: "8 deliveries",
      valueLabel: "₹12.8L",
    },
  ],
  requests: [
    {
      id: "request-concrete",
      name: "Ground floor concrete",
      projectId: "nila-residence",
      projectName: "Nila Residence",
      categories: ["Cement", "M-Sand", "Aggregate"],
      categoryGroup: "cement",
      quoteCount: 4,
      requiredBy: "2026-08-02",
      requiredByLabel: "02 Aug",
      status: "quotes_received",
      stage: "quotations",
      actionLabel: "Review",
      needsAttention: true,
    },
    {
      id: "request-electrical",
      name: "Electrical first fix",
      projectId: "nila-residence",
      projectName: "Nila Residence",
      categories: ["Wires", "conduits", "boxes"],
      categoryGroup: "electrical",
      quoteCount: 2,
      requiredBy: "2026-08-08",
      requiredByLabel: "08 Aug",
      status: "awaiting_quotes",
      stage: "quotations",
      actionLabel: "View",
      needsAttention: true,
    },
    {
      id: "request-bathroom",
      name: "Bathroom fixtures",
      projectId: "lake-house",
      projectName: "Lake House",
      categories: ["Sanitaryware", "fittings"],
      categoryGroup: "sanitaryware",
      quoteCount: 5,
      requiredBy: "2026-08-14",
      requiredByLabel: "14 Aug",
      status: "approval_pending",
      stage: "approval",
      actionLabel: "Compare",
      needsAttention: true,
    },
    {
      id: "request-steel",
      name: "Structural steel",
      projectId: "nila-residence",
      projectName: "Nila Residence",
      categories: ["TMT steel"],
      categoryGroup: "steel",
      quoteCount: 3,
      requiredBy: "2026-07-29",
      requiredByLabel: "29 Jul",
      status: "ordered",
      stage: "ordered",
      actionLabel: "Track",
      needsAttention: false,
    },
  ],
  alerts: [
    {
      id: "alert-cement-expiry",
      severity: "critical",
      title: "Cement quotation expires today",
      metadata: "Nila Residence · 4 quotations",
      requestId: "request-concrete",
      targetStage: "quotations",
    },
    {
      id: "alert-tile-delay",
      severity: "warning",
      title: "Tile delivery delayed by two days",
      metadata: "Lake House · Supplier update",
      targetStage: "ordered",
    },
    {
      id: "alert-electrical-response",
      severity: "warning",
      title: "Electrical request has no supplier responses",
      metadata: "Nila Residence · Sent 23 Jul",
      requestId: "request-electrical",
      targetStage: "quotations",
    },
    {
      id: "alert-supplier-approval",
      severity: "info",
      title: "One supplier requires approval",
      metadata: "Bathroom fixtures · Lake House",
      requestId: "request-bathroom",
      targetStage: "approval",
    },
  ],
  deliveries: [
    {
      id: "delivery-steel",
      material: "Structural steel",
      dueLabel: "29 Jul",
      requestId: "request-steel",
    },
    {
      id: "delivery-cement",
      material: "Cement",
      dueLabel: "30 Jul",
      requestId: "request-concrete",
    },
    {
      id: "delivery-conduits",
      material: "Electrical conduits",
      dueLabel: "02 Aug",
      requestId: "request-electrical",
    },
  ],
  suppliers: [
    {
      id: "supplier-malabar-cements",
      name: "Malabar Build Supply",
      verified: true,
      location: "Kochi, Kerala",
      categories: "Cement, aggregate",
      completedOrders: 18,
      averageFulfilment: "2.4 days",
    },
    {
      id: "supplier-electroline",
      name: "Electroline Systems",
      verified: true,
      location: "Ernakulam, Kerala",
      categories: "Electrical, lighting",
      completedOrders: 11,
      averageFulfilment: "3.1 days",
    },
    {
      id: "supplier-steelcraft",
      name: "Steelcraft Traders",
      verified: true,
      location: "Thrissur, Kerala",
      categories: "TMT steel, structural",
      completedOrders: 9,
      averageFulfilment: "2.8 days",
    },
  ],
};

export async function getHubWorkspaceData(): Promise<HubWorkspaceData> {
  return HUB_MOCK_WORKSPACE_DATA;
}
