import {
  BudgetCategoryAllocation,
  CashFlowPoint,
  FinanceInvoice,
  FinanceVariation,
  PaymentMilestone,
  ProjectFinanceRecord,
  ProjectFinanceTransaction,
} from "../types/project-finance.types";
import { rupeesToPaise } from "../utils/format-inr";

const paise = rupeesToPaise;
const PROJECT_ID = "proj-001";

const variations: FinanceVariation[] = [
  {
    id: "variation-001",
    projectId: PROJECT_ID,
    title: "Approved facade material upgrade",
    amount: paise(200_000),
    status: "approved",
  },
  {
    id: "variation-002",
    projectId: PROJECT_ID,
    title: "Landscape lighting extension",
    amount: paise(150_000),
    status: "pending",
  },
  {
    id: "variation-003",
    projectId: PROJECT_ID,
    title: "Guest suite scope revision",
    amount: paise(75_000),
    status: "rejected",
  },
];

const milestones: PaymentMilestone[] = [
  {
    id: "milestone-advance",
    projectId: PROJECT_ID,
    title: "Advance Payment",
    plannedDate: "2025-09-12",
    amount: paise(1_000_000),
    invoicedAmount: paise(1_000_000),
    receivedAmount: paise(1_000_000),
    status: "paid",
  },
  {
    id: "milestone-concept",
    projectId: PROJECT_ID,
    title: "Concept Approval",
    plannedDate: "2025-12-18",
    amount: paise(500_000),
    invoicedAmount: paise(500_000),
    receivedAmount: paise(500_000),
    status: "paid",
  },
  {
    id: "milestone-foundation",
    projectId: PROJECT_ID,
    title: "Foundation Completion",
    plannedDate: "2026-04-18",
    amount: paise(1_000_000),
    invoicedAmount: paise(1_000_000),
    receivedAmount: paise(900_000),
    status: "partially_paid",
  },
  {
    id: "milestone-roof",
    projectId: PROJECT_ID,
    title: "Roof Slab Casting",
    plannedDate: "2026-07-30",
    amount: paise(750_000),
    invoicedAmount: 0,
    receivedAmount: 0,
    status: "invoice_ready",
  },
  {
    id: "milestone-finishing",
    projectId: PROJECT_ID,
    title: "Finishing Completion",
    plannedDate: "2026-11-15",
    amount: paise(1_000_000),
    invoicedAmount: 0,
    receivedAmount: 0,
    status: "upcoming",
  },
  {
    id: "milestone-handover",
    projectId: PROJECT_ID,
    title: "Final Handover",
    plannedDate: "2027-01-20",
    amount: paise(750_000),
    invoicedAmount: 0,
    receivedAmount: 0,
    status: "upcoming",
  },
];

const invoices: FinanceInvoice[] = [
  {
    id: "invoice-001",
    projectId: PROJECT_ID,
    invoiceNumber: "INV-2025-031",
    title: "Advance payment",
    issuedDate: "2025-09-05",
    dueDate: "2025-09-12",
    amount: paise(1_000_000),
    receivedAmount: paise(1_000_000),
    status: "paid",
    milestoneId: "milestone-advance",
  },
  {
    id: "invoice-002",
    projectId: PROJECT_ID,
    invoiceNumber: "INV-2025-052",
    title: "Concept approval",
    issuedDate: "2025-12-10",
    dueDate: "2025-12-18",
    amount: paise(500_000),
    receivedAmount: paise(500_000),
    status: "paid",
    milestoneId: "milestone-concept",
  },
  {
    id: "invoice-003",
    projectId: PROJECT_ID,
    invoiceNumber: "INV-2026-011",
    title: "Foundation completion",
    issuedDate: "2026-04-11",
    dueDate: "2026-04-18",
    amount: paise(1_000_000),
    receivedAmount: paise(900_000),
    status: "partially_paid",
    milestoneId: "milestone-foundation",
  },
  {
    id: "invoice-004",
    projectId: PROJECT_ID,
    invoiceNumber: "INV-2026-014",
    title: "Materials mobilisation",
    issuedDate: "2026-06-20",
    dueDate: "2026-07-20",
    amount: paise(150_000),
    receivedAmount: 0,
    status: "overdue",
    milestoneId: "milestone-foundation",
  },
];

function transaction(
  input: Omit<ProjectFinanceTransaction, "projectId" | "currency" | "createdAt">
): ProjectFinanceTransaction {
  return {
    ...input,
    projectId: PROJECT_ID,
    currency: "INR",
    createdAt: `${input.date}T09:30:00.000Z`,
  };
}

const transactions: ProjectFinanceTransaction[] = [
  transaction({
    id: "transaction-receipt-001",
    date: "2025-09-12",
    description: "Advance payment received",
    type: "client_receipt",
    status: "paid",
    category: "Client collections",
    counterparty: "Anoop Kumar",
    reference: "UTR92214831",
    milestoneId: "milestone-advance",
    invoiceId: "invoice-001",
    paymentMethod: "Bank transfer",
    amount: paise(1_000_000),
  }),
  transaction({
    id: "transaction-receipt-002",
    date: "2025-12-18",
    description: "Concept approval payment",
    type: "client_receipt",
    status: "paid",
    category: "Client collections",
    counterparty: "Anoop Kumar",
    reference: "UTR25120194",
    milestoneId: "milestone-concept",
    invoiceId: "invoice-002",
    paymentMethod: "Bank transfer",
    amount: paise(500_000),
  }),
  transaction({
    id: "transaction-receipt-003",
    date: "2026-04-18",
    description: "Foundation milestone part payment",
    type: "client_receipt",
    status: "paid",
    category: "Client collections",
    counterparty: "Anoop Kumar",
    reference: "UTR26041877",
    milestoneId: "milestone-foundation",
    invoiceId: "invoice-003",
    paymentMethod: "Bank transfer",
    amount: paise(900_000),
  }),
  transaction({
    id: "transaction-expense-material",
    date: "2026-05-30",
    description: "Structural steel and cement",
    type: "expense",
    status: "paid",
    category: "Materials",
    counterparty: "Malabar Building Supplies",
    reference: "MBS-7821",
    paymentMethod: "Bank transfer",
    amount: paise(800_000),
  }),
  transaction({
    id: "transaction-expense-labour",
    date: "2026-07-24",
    description: "Site labour payment, July cycle",
    type: "expense",
    status: "paid",
    category: "Labour",
    counterparty: "Nila Site Workforce",
    reference: "PAY-0724",
    paymentMethod: "Bank transfer",
    amount: paise(550_000),
  }),
  transaction({
    id: "transaction-expense-consultant",
    date: "2026-06-14",
    description: "Structural consultancy fee",
    type: "expense",
    status: "paid",
    category: "Design and consultancy",
    counterparty: "Vertex Structural Consultants",
    reference: "VSC-1048",
    paymentMethod: "Bank transfer",
    amount: paise(360_000),
  }),
  transaction({
    id: "transaction-expense-subcontract",
    date: "2026-07-18",
    description: "Electrical rough-in work",
    type: "expense",
    status: "paid",
    category: "Subcontractors",
    counterparty: "Sparkline Electricals",
    reference: "SE-2290",
    paymentMethod: "Bank transfer",
    amount: paise(320_000),
  }),
  transaction({
    id: "transaction-expense-logistics",
    date: "2026-07-08",
    description: "Material transport and crane hire",
    type: "expense",
    status: "paid",
    category: "Logistics",
    counterparty: "Kerala Site Logistics",
    reference: "KSL-447",
    paymentMethod: "Bank transfer",
    amount: paise(150_000),
  }),
  transaction({
    id: "transaction-expense-other",
    date: "2026-06-28",
    description: "Site safety and temporary utilities",
    type: "expense",
    status: "paid",
    category: "Other expenses",
    counterparty: "Buildsafe Services",
    reference: "BSS-112",
    paymentMethod: "UPI",
    amount: paise(80_000),
  }),
  transaction({
    id: "transaction-commitment-material",
    date: "2026-07-20",
    description: "Roof slab concrete supply order",
    type: "commitment",
    status: "approved",
    category: "Materials",
    counterparty: "ReadyMix Kerala",
    reference: "PO-2618",
    paymentMethod: "Purchase order",
    amount: paise(420_000),
  }),
  transaction({
    id: "transaction-commitment-subcontract",
    date: "2026-07-23",
    description: "Waterproofing package",
    type: "commitment",
    status: "approved",
    category: "Subcontractors",
    counterparty: "AquaSeal Projects",
    reference: "PO-2624",
    paymentMethod: "Purchase order",
    amount: paise(250_000),
  }),
  transaction({
    id: "transaction-commitment-labour",
    date: "2026-07-19",
    description: "Roof slab labour allocation",
    type: "commitment",
    status: "approved",
    category: "Labour",
    counterparty: "Nila Site Workforce",
    reference: "WO-0719",
    paymentMethod: "Work order",
    amount: paise(110_000),
  }),
  transaction({
    id: "transaction-commitment-logistics",
    date: "2026-07-17",
    description: "Roof slab pump and lifting equipment",
    type: "commitment",
    status: "approved",
    category: "Logistics",
    counterparty: "Kerala Site Logistics",
    reference: "PO-2609",
    paymentMethod: "Purchase order",
    amount: paise(100_000),
  }),
  transaction({
    id: "transaction-pending-001",
    date: "2026-07-26",
    description: "Electrical conduit material claim",
    type: "expense",
    status: "pending",
    category: "Materials",
    counterparty: "Sparkline Electricals",
    reference: "CLM-228",
    paymentMethod: "Bank transfer",
    amount: paise(64_000),
  }),
  transaction({
    id: "transaction-pending-002",
    date: "2026-07-25",
    description: "Site survey support expense",
    type: "expense",
    status: "pending",
    category: "Design and consultancy",
    counterparty: "GeoMark Surveys",
    reference: "GMS-719",
    paymentMethod: "Bank transfer",
    amount: paise(28_000),
  }),
];

const budgetCategories: BudgetCategoryAllocation[] = [
  {
    id: "budget-design",
    projectId: PROJECT_ID,
    name: "Design and consultancy",
    approvedAmount: paise(600_000),
  },
  {
    id: "budget-materials",
    projectId: PROJECT_ID,
    name: "Materials",
    approvedAmount: paise(1_650_000),
  },
  {
    id: "budget-labour",
    projectId: PROJECT_ID,
    name: "Labour",
    approvedAmount: paise(1_000_000),
  },
  {
    id: "budget-subcontractors",
    projectId: PROJECT_ID,
    name: "Subcontractors",
    approvedAmount: paise(900_000),
  },
  {
    id: "budget-logistics",
    projectId: PROJECT_ID,
    name: "Logistics",
    approvedAmount: paise(300_000),
  },
  {
    id: "budget-other",
    projectId: PROJECT_ID,
    name: "Other expenses",
    approvedAmount: paise(550_000),
  },
];

const flowSeed: Array<Omit<CashFlowPoint, "id" | "projectId">> = [
  { periodLabel: "Aug", periodStart: "2025-08-01", clientInflow: 0, projectOutflow: paise(60_000), netCashPosition: paise(-60_000) },
  { periodLabel: "Sep", periodStart: "2025-09-01", clientInflow: paise(1_000_000), projectOutflow: paise(120_000), netCashPosition: paise(820_000) },
  { periodLabel: "Oct", periodStart: "2025-10-01", clientInflow: 0, projectOutflow: paise(170_000), netCashPosition: paise(650_000) },
  { periodLabel: "Nov", periodStart: "2025-11-01", clientInflow: 0, projectOutflow: paise(220_000), netCashPosition: paise(430_000) },
  { periodLabel: "Dec", periodStart: "2025-12-01", clientInflow: paise(500_000), projectOutflow: paise(180_000), netCashPosition: paise(750_000) },
  { periodLabel: "Jan", periodStart: "2026-01-01", clientInflow: 0, projectOutflow: paise(150_000), netCashPosition: paise(600_000) },
  { periodLabel: "Feb", periodStart: "2026-02-01", clientInflow: 0, projectOutflow: paise(190_000), netCashPosition: paise(410_000) },
  { periodLabel: "Mar", periodStart: "2026-03-01", clientInflow: 0, projectOutflow: paise(220_000), netCashPosition: paise(190_000) },
  { periodLabel: "Apr", periodStart: "2026-04-01", clientInflow: paise(900_000), projectOutflow: paise(250_000), netCashPosition: paise(840_000) },
  { periodLabel: "May", periodStart: "2026-05-01", clientInflow: 0, projectOutflow: paise(240_000), netCashPosition: paise(600_000) },
  { periodLabel: "Jun", periodStart: "2026-06-01", clientInflow: 0, projectOutflow: paise(210_000), netCashPosition: paise(390_000) },
  { periodLabel: "Jul", periodStart: "2026-07-01", clientInflow: 0, projectOutflow: paise(250_000), netCashPosition: paise(140_000) },
];

const cashFlow: CashFlowPoint[] = flowSeed.map((point, index) => ({
  ...point,
  id: `cash-flow-${index + 1}`,
  projectId: PROJECT_ID,
}));

export function createMockProjectFinanceRecord(
  projectId = PROJECT_ID,
  projectName = "Nila Residence",
  projectCode = "KAL-2024-001"
): ProjectFinanceRecord {
  const replaceProjectId = <T extends { projectId: string }>(item: T): T => ({
    ...item,
    projectId,
  });

  return {
    projectId,
    projectName,
    projectCode,
    baseContractValue: paise(4_800_000),
    currency: "INR",
    variations: variations.map(replaceProjectId),
    invoices: invoices.map(replaceProjectId),
    milestones: milestones.map(replaceProjectId),
    transactions: transactions.map(replaceProjectId),
    budgetCategories: budgetCategories.map(replaceProjectId),
    cashFlow: cashFlow.map(replaceProjectId),
    updatedAt: "2026-07-27T08:30:00.000Z",
  };
}
