import { PageReadinessManifest } from "../types/developerConsole.types";

export const virtualOfficeManifest: PageReadinessManifest = {
  pageId: "virtual-office-overview",
  pageName: "Virtual Office Overview",
  routePattern: /^\/virtual-office(?:\/.*)?$/,
  requiredRoles: ["developer", "super_admin", "qa"],
  manifestVersion: "1.0.0",
  backendActions: [
    {
      actionId: "load_studio_data",
      actionName: "Load Studio Data",
      uiComponent: "VirtualOfficePage",
      eventHandler: "useEffect/onload",
      serviceMethod: "studioService.getOverviewData",
      apiEndpoint: "/api/studio/overview",
      databaseTarget: "studios/{studioId}",
      requiredPermission: "read:studio_overview",
      isRequired: true,
      notes: "Fetches active projects count, enquiry count, and team overview metrics.",
    },
    {
      actionId: "create_studio_action",
      actionName: "Create Studio Action",
      uiComponent: "RoutePageContainer",
      eventHandler: "onPrimaryAction",
      serviceMethod: "studioService.createActionItem",
      apiEndpoint: "/api/studio/actions",
      databaseTarget: "studio_actions",
      requiredPermission: "write:studio_actions",
      isRequired: false,
      notes: "Triggered by clicking the primary action 'New Studio Action' button.",
    },
  ],
  checklistRequirements: [
    {
      itemId: "auth_defined",
      category: "authentication",
      title: "Authentication requirement defined",
      description: "Ensure only authenticated users can load the dashboard layout.",
      isRequired: true,
      isAutomated: true,
      weight: 4,
      blockingLevel: "production",
    },
    {
      itemId: "role_enforced",
      category: "authentication",
      title: "Role-based access enforced",
      description: "Verify that access permissions are resolved from server roles, not client state.",
      isRequired: true,
      isAutomated: false,
      weight: 4,
      blockingLevel: "production",
    },
    {
      itemId: "data_loaded",
      category: "data_loading",
      title: "Correct provider data loaded",
      description: "Confirm loaded records belong strictly to the authenticated provider's studio.",
      isRequired: true,
      isAutomated: true,
      weight: 3,
      blockingLevel: "production",
    },
    {
      itemId: "loading_state_rendered",
      category: "data_loading",
      title: "Loading state implemented",
      description: "Verify visual skeleton displays during asynchronous content fetching.",
      isRequired: false,
      isAutomated: false,
      weight: 2,
      blockingLevel: "staging",
    },
    {
      itemId: "error_state_rendered",
      category: "data_loading",
      title: "API failure state handled",
      description: "Ensure network errors surface a clean error view with a retry action.",
      isRequired: false,
      isAutomated: false,
      weight: 2,
      blockingLevel: "staging",
    },
    {
      itemId: "double_submit_prevented",
      category: "mutations",
      title: "Double submission prevented",
      description: "Disable form buttons during active API write operations.",
      isRequired: true,
      isAutomated: false,
      weight: 3,
      blockingLevel: "production",
    },
    {
      itemId: "no_client_secrets",
      category: "security",
      title: "No client-side secrets",
      description: "Verify that credentials, API private keys, and service tokens are kept server-side.",
      isRequired: true,
      isAutomated: true,
      weight: 4,
      blockingLevel: "production",
    },
    {
      itemId: "rate_limiting_configured",
      category: "security",
      title: "Abuse-sensitive actions rate-limited",
      description: "Check if the create action endpoint contains rate limiting protection.",
      isRequired: true,
      isAutomated: false,
      weight: 3,
      blockingLevel: "production",
    },
    {
      itemId: "network_failures_handled",
      category: "reliability",
      title: "Network failures handled",
      description: "Ensure the UI doesn't crash when offline or experiencing transient failures.",
      isRequired: false,
      isAutomated: false,
      weight: 2,
      blockingLevel: "staging",
    },
    {
      itemId: "env_variables_documented",
      category: "deployment",
      title: "Required environment variables documented",
      description: "Verify all required env keys are documented in local and staging configs.",
      isRequired: true,
      isAutomated: false,
      weight: 1,
      blockingLevel: "production",
    },
  ],
  diagnostics: [
    {
      key: "auth_context",
      label: "Authentication Context",
      description: "Checks if Firebase Auth user is initialized.",
      trustLevel: "client_observed",
    },
    {
      key: "user_role",
      label: "Current User Role",
      description: "Verifies authenticated role claims on server.",
      trustLevel: "server_verified",
    },
    {
      key: "provider_access",
      label: "Provider Ownership",
      description: "Validates provider studio resource ownership.",
      trustLevel: "server_verified",
    },
    {
      key: "firestore_read",
      label: "Firestore Availability",
      description: "Runs a read check query on a test collection.",
      trustLevel: "server_verified",
    },
    {
      key: "storage_health",
      label: "Storage Availability",
      description: "Verifies storage bucket configurations.",
      trustLevel: "server_verified",
    },
    {
      key: "api_endpoint_health",
      label: "API Connectivity",
      description: "Verifies the studio overview API route returns 200.",
      trustLevel: "client_observed",
    },
    {
      key: "env_keys_present",
      label: "Environment Keys Configuration",
      description: "Verifies presence of Firebase configuration keys in environment variables.",
      trustLevel: "server_verified",
    },
  ],
  requiredTests: ["VirtualOfficePage component tests", "Studio actions permissions test"],
};
