import { EnquiryRecord } from "../types/enquiry.types";

export const CLIENT_PORTAL_ENQUIRIES: EnquiryRecord[] = [
  {
    id: "prj-9",
    title: "Cedar Valley Studio & Residence",
    requirementSummary: "A 2,800 sq.ft artistic retreat in Wayanad utilizing exposed rammed earth walls and north skylights.",
    clientName: "Kavita Pillai",
    location: "Wayanad, Kerala",
    thumbnailUrl: "/assets/nila-hero-modern.jpg",
    source: "website",
    status: "active",
    stage: "clarification",
    projectType: "residential",
    budgetMin: 9500000,
    budgetMax: 9500000,
    budget: "₹95L",
    receivedAt: "2026-08-05T12:00:00.000Z",
    clientStatus: "Revision Requested",
    nextAction: {
      type: "request_clarification",
      label: "Reviewing with Architect",
    },
  },
  {
    id: "prj-8",
    title: "Palm Grove Boutique Suites",
    requirementSummary: "A 4,900 sq.ft contemporary backwater retreat in Alappuzha featuring private boat docking.",
    clientName: "Siddharth Nair",
    location: "Alappuzha, Kerala",
    thumbnailUrl: "/assets/nila-hero.jpg",
    source: "website",
    status: "active",
    stage: "proposal",
    projectType: "hospitality",
    budgetMin: 21000000,
    budgetMax: 21000000,
    budget: "₹2.1Cr",
    receivedAt: "2026-08-01T10:00:00.000Z",
    clientStatus: "Proposal Received",
    nextAction: {
      type: "prepare_proposal",
      label: "Proposal in Preparation",
    },
  },
  {
    id: "prj-11",
    title: "Malabar Heritage Courtyard Villa",
    requirementSummary: "A 3,600 sq.ft heritage-inspired estate in Calicut featuring an open central courtyard and laterite masonry.",
    clientName: "Deepak Nambiar",
    location: "Calicut, Kerala",
    thumbnailUrl: "/assets/nila-hero-modern.jpg",
    source: "referral",
    status: "active",
    stage: "proposal",
    projectType: "residential",
    budgetMin: 18000000,
    budgetMax: 18000000,
    budget: "₹1.8Cr",
    receivedAt: "2026-07-28T10:30:00.000Z",
    clientStatus: "Proposal Received",
    nextAction: {
      type: "prepare_proposal",
      label: "Proposal in Preparation",
    },
  },
  {
    id: "prj-12",
    title: "Emerald Heights Luxury Penthouse",
    requirementSummary: "A 4,100 sq.ft duplex penthouse fitout in Kochi with private terrace plunge pool and smart automation.",
    clientName: "Meera Krishnan",
    location: "Kochi, Kerala",
    thumbnailUrl: "/assets/project-banner.jpg",
    source: "direct",
    status: "active",
    stage: "new",
    projectType: "residential",
    budgetMin: 8500000,
    budgetMax: 8500000,
    budget: "₹85L",
    receivedAt: "2026-07-25T14:15:00.000Z",
    clientStatus: "Sent",
    nextAction: {
      type: "review_enquiry",
      label: "Reviewing with Architect",
    },
  },
  {
    id: "prj-13",
    title: "Serenity Wellness & Ayurvedic Spa",
    requirementSummary: "A 6,800 sq.ft Ayurvedic resort facility in Munnar featuring bio-climatic stone pavilions and reflection ponds.",
    clientName: "Dr. Radhakrishnan Varma",
    location: "Munnar, Kerala",
    thumbnailUrl: "/assets/nila-hero.jpg",
    source: "partner",
    status: "active",
    stage: "proposal",
    projectType: "commercial",
    budgetMin: 34000000,
    budgetMax: 34000000,
    budget: "₹3.4Cr",
    receivedAt: "2026-07-20T09:00:00.000Z",
    clientStatus: "Proposal Received",
    nextAction: {
      type: "prepare_proposal",
      label: "Proposal in Preparation",
    },
  },

  {
    id: "prj-15",
    title: "Greenfield Sustainable Farmhouse",
    requirementSummary: "A 2,400 sq.ft regenerative farmhouse in Palakkad utilizing compressed earth blocks and off-grid solar.",
    clientName: "Sunil & Divya Warrier",
    location: "Palakkad, Kerala",
    thumbnailUrl: "/assets/nila-thumb1.jpg",
    source: "referral",
    status: "active",
    stage: "new",
    projectType: "landscape",
    budgetMin: 11000000,
    budgetMax: 11000000,
    budget: "₹1.1Cr",
    receivedAt: "2026-07-12T08:20:00.000Z",
    clientStatus: "Sent",
    nextAction: {
      type: "schedule_consultation",
      label: "Consultation Scheduled",
    },
  },
  {
    id: "prj-16",
    title: "Metro Commercial Plaza Fitout",
    requirementSummary: "A 9,500 sq.ft retail promenade in Thrissur with industrial glass facade and commercial kitchen exhaust risers.",
    clientName: "Apex Retail Group",
    location: "Thrissur, Kerala",
    thumbnailUrl: "/assets/project-banner.jpg",
    source: "direct",
    status: "archived",
    stage: "rejected",
    projectType: "retail",
    budgetMin: 42000000,
    budgetMax: 42000000,
    budget: "₹4.2Cr",
    receivedAt: "2026-06-28T15:00:00.000Z",
    clientStatus: "Rejected",
    nextAction: {
      type: "mark_as_lost",
      label: "Enquiry Closed",
    },
  },
  {
    id: "prj-17",
    title: "Skyline High-Tech Co-Working Hub",
    requirementSummary: "A modern collaborative commercial interior for emerging technology startups in Infopark Kochi.",
    clientName: "Kochi Co-Work Space",
    location: "Kochi, Kerala",
    thumbnailUrl: "/assets/studio/visualisations-flatlay.jpg",
    source: "partner",
    status: "active",
    stage: "new",
    projectType: "commercial",
    budgetMin: 15000000,
    budgetMax: 15000000,
    budget: "₹1.5Cr",
    receivedAt: "2026-06-20T09:30:00.000Z",
    clientStatus: "Sent",
    nextAction: {
      type: "review_enquiry",
      label: "Reviewing with Architect",
    },
  },
  {
    id: "prj-18",
    title: "The Whispering Pines Eco Cabin",
    requirementSummary: "An off-grid hillside pinewood timber lodge designed with biophilic passive ventilation.",
    clientName: "Praveen & Rohini Mohan",
    location: "Idukki, Kerala",
    thumbnailUrl: "/assets/projects/greenfield-villa.png",
    source: "website",
    status: "active",
    stage: "proposal",
    projectType: "residential",
    budgetMin: 7000000,
    budgetMax: 7000000,
    budget: "₹70L",
    receivedAt: "2026-06-14T16:00:00.000Z",
    clientStatus: "Proposal Received",
    nextAction: {
      type: "prepare_proposal",
      label: "Proposal in Preparation",
    },
  },
  {
    id: "prj-19",
    title: "Monsoon Breeze Waterfront Villa",
    requirementSummary: "A 3,200 sq.ft lakeside private villa in Kumarakom with timber decking and sloped traditional tile roof.",
    clientName: "Sunitha Menon",
    location: "Kottayam, Kerala",
    thumbnailUrl: "/assets/nila-hero.jpg",
    source: "website",
    status: "archived",
    stage: "rejected",
    projectType: "residential",
    budgetMin: 14000000,
    budgetMax: 14000000,
    budget: "₹1.4Cr",
    receivedAt: "2026-05-18T11:00:00.000Z",
    clientStatus: "Rejected",
    nextAction: {
      type: "mark_as_lost",
      label: "Proposal Rejected",
    },
  },
  {
    id: "prj-20",
    title: "Highland Tea Plantation Bungalow",
    requirementSummary: "A 3,400 sq.ft colonial bungalow restoration in Munnar requiring timber structural stabilization.",
    clientName: "Rohan & Tara Varghese",
    location: "Munnar, Kerala",
    thumbnailUrl: "/assets/nila-thumb1.jpg",
    source: "website",
    status: "active",
    stage: "lost",
    projectType: "residential",
    budgetMin: 16000000,
    budgetMax: 16000000,
    budget: "₹1.6Cr",
    receivedAt: "2026-07-10T14:30:00.000Z",
    clientStatus: "Declined",
    declineReason: "Current studio team capacity is fully booked for Q3/Q4. Unable to commit to the requested site supervision schedule in Munnar.",
    nextAction: {
      type: "mark_as_lost",
      label: "Specialist Declined",
    },
  },
  {
    id: "prj-21",
    title: "Kovalam Sea Breeze Penthouse",
    requirementSummary: "A 2,900 sq.ft coastal duplex interior renovation with marine-grade joinery.",
    clientName: "Anoop Kurian",
    location: "Kovalam, Kerala",
    thumbnailUrl: "/assets/projectbg.webp",
    source: "direct",
    status: "active",
    stage: "lost",
    projectType: "residential",
    budgetMin: 7500000,
    budgetMax: 7500000,
    budget: "₹75L",
    receivedAt: "2026-05-02T10:00:00.000Z",
    clientStatus: "Expired",
    expiredAt: "2026-05-16T10:00:00.000Z",
    nextAction: {
      type: "mark_as_lost",
      label: "Response Window Expired",
    },
  },
];

export function updateClientPortalEnquiry(id: string, updates: Partial<EnquiryRecord>): void {
  const index = CLIENT_PORTAL_ENQUIRIES.findIndex(
    (e) => e.id === id || e.id === `prj-${id}` || e.id.replace("prj-", "") === id
  );
  if (index !== -1) {
    CLIENT_PORTAL_ENQUIRIES[index] = {
      ...CLIENT_PORTAL_ENQUIRIES[index],
      ...updates,
    };
  }
}

