import { EnquiryRecord } from "../types/enquiry.types";

export const MOCK_ENQUIRIES: EnquiryRecord[] = [
  {
    id: "enq-1",
    title: "Villa Design Consultation",
    requirementSummary: "Needs high-end luxury villa design with modern amenities and sustainable materials.",
    clientName: "Ananya Builders",
    location: "Kochi",
    thumbnailUrl: "/assets/projects/greenfield-villa.png",
    source: "website",
    status: "needs_attention",
    stage: "new",
    projectType: "residential",
    budgetMin: 1800000,
    budgetMax: 2500000,
    receivedAt: "2026-07-23T10:45:00.000Z",
    nextAction: {
      type: "review_enquiry",
      label: "Review enquiry",
      dueAt: "2026-07-23T18:00:00.000Z",
      state: "urgent",
    },
    isNew: true,
  },
  {
    id: "enq-2",
    title: "Office Interior Fit-out",
    requirementSummary: "A modern commercial workspace design aiming for collaborative spaces and ergonomic seating.",
    clientName: "Greenleaf Spaces",
    location: "Bengaluru",
    thumbnailUrl: "/assets/studio/visualisations-flatlay.jpg",
    source: "referral",
    status: "needs_attention",
    stage: "clarification",
    projectType: "commercial",
    budgetMin: 4000000,
    budgetMax: 6000000,
    receivedAt: "2026-07-23T09:12:00.000Z",
    nextAction: {
      type: "request_clarification",
      label: "Request clarification",
      dueAt: "2026-07-23T17:00:00.000Z",
      state: "urgent",
    },
    enquiryRef: "ENQ-2026-0486",
    priority: "high",
    owner: "Anjali",
    tags: ["fitout", "commercial", "bengaluru"],
    lastUpdatedAt: "2026-08-03T17:12:00.000Z",
  },
  {
    id: "enq-3",
    title: "Renovation & Extension",
    requirementSummary: "Adding a rear extension and renovating existing rooms in a historic residential building.",
    clientName: "Fathima Nawas",
    location: "Trivandrum",
    thumbnailUrl: "/assets/projects/oak-house.png",
    source: "partner",
    status: "active",
    stage: "consultation",
    projectType: "residential",
    budgetMin: 2200000,
    budgetMax: 3000000,
    receivedAt: "2026-07-22T16:30:00.000Z",
    nextAction: {
      type: "schedule_consultation",
      label: "Schedule consultation",
      dueAt: "2026-07-24T10:00:00.000Z",
      state: "scheduled",
    },
  },
  {
    id: "enq-4",
    title: "Café Concept Proposal",
    requirementSummary: "Boutique cafe interior proposal focusing on industrial chic aesthetic and layout optimization.",
    clientName: "Brew District",
    location: "Kochi",
    thumbnailUrl: "/assets/studio/boq-rate-analysis-flatlay.jpg",
    source: "direct",
    status: "active",
    stage: "qualified",
    projectType: "hospitality",
    budgetMin: 1200000,
    budgetMax: 1800000,
    receivedAt: "2026-07-22T11:20:00.000Z",
    nextAction: {
      type: "consultation",
      label: "Consultation",
      dueAt: "2026-05-23T11:00:00.000Z",
      state: "scheduled",
    },
  },
  {
    id: "enq-5",
    title: "Apartment Block Planning",
    requirementSummary: "Structural planning and design layout for a new multi-family housing development project.",
    clientName: "Meridian Developers",
    location: "Calicut",
    thumbnailUrl: "/assets/projects/residence-24.png",
    source: "franchise",
    status: "active",
    stage: "qualified",
    projectType: "multi_family",
    budgetMin: 5500000,
    budgetMax: 8000000,
    receivedAt: "2026-05-18T10:00:00.000Z",
    nextAction: {
      type: "follow_up",
      label: "Follow up",
      dueAt: "2026-07-25T15:00:00.000Z",
      state: "scheduled",
    },
  },
  {
    id: "enq-6",
    title: "Landscape & Exterior Upgrade",
    requirementSummary: "Complete redesign of outdoor green spaces, water bodies, and patio decks.",
    clientName: "Lakeside Villas",
    location: "Thrissur",
    thumbnailUrl: "/assets/projects/anitha-menon-residence.png",
    source: "website",
    status: "active",
    stage: "won",
    projectType: "landscape",
    budgetMin: 800000,
    budgetMax: 1500000,
    receivedAt: "2026-05-17T12:00:00.000Z",
    nextAction: {
      type: "convert_to_project",
      label: "Convert to project",
      state: "ready",
    },
  },
  {
    id: "enq-7",
    title: "Retail Store Design",
    requirementSummary: "Creating a premium retail space concept layout for high-end boutique apparel.",
    clientName: "Urban Thread",
    location: "Chennai",
    thumbnailUrl: "/assets/studio/project-estimates-flatlay.jpg",
    source: "referral",
    status: "completed",
    stage: "lost",
    projectType: "retail",
    budgetMin: 1600000,
    budgetMax: 2400000,
    receivedAt: "2026-05-16T14:00:00.000Z",
    nextAction: {
      type: "mark_as_lost",
      label: "Mark as lost",
      state: "completed",
    },
  },
  {
    id: "enq-8",
    title: "Site Feasibility Review",
    requirementSummary: "On-site soil checking and structural feasibility study for building permit approval.",
    clientName: "Arun Thomas",
    location: "Kottayam",
    thumbnailUrl: "/assets/studio/drawing-analysis-flatlay.jpg",
    source: "website",
    status: "needs_attention",
    stage: "consultation",
    projectType: "residential",
    budgetMin: 1000000,
    budgetMax: 1500000,
    receivedAt: "2026-05-15T09:00:00.000Z",
    nextAction: {
      type: "schedule_consultation",
      label: "Schedule consultation",
      dueAt: "2026-07-24T16:00:00.000Z",
      state: "scheduled",
    },
    isNew: true,
  },
  {
    id: "enq-9",
    title: "Resort Masterplan Enquiry",
    requirementSummary: "Comprehensive luxury ecotourism resort layout plan including cabins, paths, and central lobby.",
    clientName: "West Coast Retreats",
    location: "Wayanad",
    thumbnailUrl: "/assets/studio/proposals-flatlay.jpg",
    source: "partner",
    status: "active",
    stage: "proposal",
    projectType: "hospitality",
    budgetMin: 6000000,
    budgetMax: 10000000,
    receivedAt: "2026-05-14T11:00:00.000Z",
    nextAction: {
      type: "prepare_proposal",
      label: "Prepare proposal",
      dueAt: "2026-07-26T12:00:00.000Z",
      state: "scheduled",
    },
  },
  {
    id: "enq-10",
    title: "Co-working Space Expansion",
    requirementSummary: "Flexible office interior layout with soundproof booths and lounge areas.",
    clientName: "FlexiWork Hub",
    location: "Hyderabad",
    thumbnailUrl: "/assets/studio/visualisations-flatlay.jpg",
    source: "website",
    status: "active",
    stage: "new",
    projectType: "commercial",
    budgetMin: 3500000,
    budgetMax: 5000000,
    receivedAt: "2026-05-13T15:30:00.000Z",
    nextAction: {
      type: "review_enquiry",
      label: "Review enquiry",
      dueAt: "2026-07-27T10:00:00.000Z",
      state: "scheduled",
    },
  },
  {
    id: "enq-11",
    title: "Beachside Restaurant Fit-out",
    requirementSummary: "Open-air restaurant dining layout with weather-resistant timber finishes.",
    clientName: "Ocean Breeze Hospitality",
    location: "Goa",
    thumbnailUrl: "/assets/studio/boq-rate-analysis-flatlay.jpg",
    source: "referral",
    status: "active",
    stage: "clarification",
    projectType: "hospitality",
    budgetMin: 2800000,
    budgetMax: 4200000,
    receivedAt: "2026-05-12T08:45:00.000Z",
    nextAction: {
      type: "request_clarification",
      label: "Request clarification",
      dueAt: "2026-07-27T14:00:00.000Z",
      state: "scheduled",
    },
  },
  {
    id: "enq-12",
    title: "Penthouse Interior Architecture",
    requirementSummary: "Bespoke interior design with custom millwork and smart home integration.",
    clientName: "Rajesh Varma",
    location: "Mumbai",
    thumbnailUrl: "/assets/projects/greenfield-villa.png",
    source: "direct",
    status: "active",
    stage: "consultation",
    projectType: "residential",
    budgetMin: 7500000,
    budgetMax: 12000000,
    receivedAt: "2026-05-11T13:20:00.000Z",
    nextAction: {
      type: "schedule_consultation",
      label: "Schedule consultation",
      dueAt: "2026-07-28T11:00:00.000Z",
      state: "scheduled",
    },
  },
  {
    id: "enq-13",
    title: "Boutique Hotel Lobby Redesign",
    requirementSummary: "Luxurious reception lobby overhaul with marble accents and decorative lighting.",
    clientName: "Heritage Stay",
    location: "Jaipur",
    thumbnailUrl: "/assets/studio/project-estimates-flatlay.jpg",
    source: "partner",
    status: "needs_attention",
    stage: "proposal",
    projectType: "hospitality",
    budgetMin: 4500000,
    budgetMax: 6500000,
    receivedAt: "2026-05-10T16:10:00.000Z",
    nextAction: {
      type: "prepare_proposal",
      label: "Prepare proposal",
      dueAt: "2026-07-24T09:00:00.000Z",
      state: "urgent",
    },
  },
  {
    id: "enq-14",
    title: "Gated Community Clubhouse",
    requirementSummary: "Multi-purpose community center planning including pool area and indoor gym.",
    clientName: "Palm Grove Estates",
    location: "Coimbatore",
    thumbnailUrl: "/assets/projects/residence-24.png",
    source: "franchise",
    status: "active",
    stage: "qualified",
    projectType: "multi_family",
    budgetMin: 8500000,
    budgetMax: 13000000,
    receivedAt: "2026-05-09T10:00:00.000Z",
    nextAction: {
      type: "follow_up",
      label: "Follow up",
      dueAt: "2026-07-29T16:00:00.000Z",
      state: "scheduled",
    },
  },
  {
    id: "enq-15",
    title: "Tech Campus Cafeteria",
    requirementSummary: "High-capacity dining hall and food court spatial arrangement for 500 employees.",
    clientName: "InfoPark Systems",
    location: "Kochi",
    thumbnailUrl: "/assets/studio/visualisations-flatlay.jpg",
    source: "website",
    status: "active",
    stage: "new",
    projectType: "commercial",
    budgetMin: 3200000,
    budgetMax: 4800000,
    receivedAt: "2026-05-08T14:15:00.000Z",
    nextAction: {
      type: "review_enquiry",
      label: "Review enquiry",
      dueAt: "2026-07-30T10:00:00.000Z",
      state: "scheduled",
    },
  },
  {
    id: "enq-16",
    title: "Luxury Duplex Renovation",
    requirementSummary: "Complete modern redesign of a 3500 sq ft duplex apartment.",
    clientName: "Priya Nair",
    location: "Trivandrum",
    thumbnailUrl: "/assets/projects/oak-house.png",
    source: "referral",
    status: "active",
    stage: "consultation",
    projectType: "residential",
    budgetMin: 2800000,
    budgetMax: 3800000,
    receivedAt: "2026-05-07T11:50:00.000Z",
    nextAction: {
      type: "schedule_consultation",
      label: "Schedule consultation",
      dueAt: "2026-07-30T15:00:00.000Z",
      state: "scheduled",
    },
  },
  {
    id: "enq-17",
    title: "Eco-Lodge Courtyard Design",
    requirementSummary: "Native plant landscaping and permeable paving layout for eco-resort grounds.",
    clientName: "Green Canopy Resorts",
    location: "Munnar",
    thumbnailUrl: "/assets/projects/anitha-menon-residence.png",
    source: "website",
    status: "active",
    stage: "proposal",
    projectType: "landscape",
    budgetMin: 1500000,
    budgetMax: 2200000,
    receivedAt: "2026-05-06T09:30:00.000Z",
    nextAction: {
      type: "prepare_proposal",
      label: "Prepare proposal",
      dueAt: "2026-07-31T12:00:00.000Z",
      state: "scheduled",
    },
  },
  {
    id: "enq-18",
    title: "Flagship Jewelry Showroom",
    requirementSummary: "High-security luxury jewelry retail layout with bespoke display cases and private salon.",
    clientName: "Aurum Fine Jewelry",
    location: "Bangalore",
    thumbnailUrl: "/assets/studio/project-estimates-flatlay.jpg",
    source: "direct",
    status: "needs_attention",
    stage: "clarification",
    projectType: "retail",
    budgetMin: 5000000,
    budgetMax: 7500000,
    receivedAt: "2026-05-05T16:45:00.000Z",
    nextAction: {
      type: "request_clarification",
      label: "Request clarification",
      dueAt: "2026-07-24T11:00:00.000Z",
      state: "urgent",
    },
  },
  {
    id: "enq-19",
    title: "Urban Townhouse Architecture",
    requirementSummary: "Multi-level contemporary urban residence design on a narrow plot.",
    clientName: "Sanjay Menon",
    location: "Kochi",
    thumbnailUrl: "/assets/projects/greenfield-villa.png",
    source: "partner",
    status: "active",
    stage: "qualified",
    projectType: "residential",
    budgetMin: 3800000,
    budgetMax: 5200000,
    receivedAt: "2026-05-04T12:10:00.000Z",
    nextAction: {
      type: "follow_up",
      label: "Follow up",
      dueAt: "2026-08-01T10:00:00.000Z",
      state: "scheduled",
    },
  },
  {
    id: "enq-20",
    title: "Medical Clinic Interior Layout",
    requirementSummary: "Sterile, patient-friendly outpatient clinic design with reception and 4 consultation suites.",
    clientName: "CarePlus Clinics",
    location: "Calicut",
    thumbnailUrl: "/assets/studio/drawing-analysis-flatlay.jpg",
    source: "website",
    status: "active",
    stage: "new",
    projectType: "commercial",
    budgetMin: 2000000,
    budgetMax: 3000000,
    receivedAt: "2026-05-03T09:00:00.000Z",
    nextAction: {
      type: "review_enquiry",
      label: "Review enquiry",
      dueAt: "2026-08-01T14:00:00.000Z",
      state: "scheduled",
    },
  },
];
