import type { DeploymentActivityTask } from "@/features/hands/types/hands.types";

/**
 * Authoritative labour & construction work tasks for Partner Hands Assignment ASG-101.
 * Focuses exclusively on direct trade execution, workmanship, crew allocation, and site works.
 * Contains NO material procurement, truck deliveries, or supply logistics.
 */
export const PARTNER_LABOUR_TASKS: DeploymentActivityTask[] = [
  {
    id: "task-1",
    title: "Perimeter brick masonry & plumb line verification",
    status: "in-progress",
    date: "2026-09-08",
    time: "8:00 AM – 1:30 PM",
    trade: "6 Masons",
    workersCount: 6,
    contractorName: "Apex Integrated Civil",
    description: "North wing 230mm solid block alignment, vertical plumb trueing, and raking bed joints for mortar adhesion.",
    boqItemCode: "BOQ-04.1",
    boqItemName: "230mm Solid Block Masonry in CM 1:6 (Labour)",
    boqQuantity: "450 / 1,200 sq ft",
    ganttPhaseId: "phase-2",
    ganttPhaseName: "Phase 2: Superstructure Masonry & Lintel Level",
    serviceCategory: "Block Masonry & Structural Works",
  },
  {
    id: "task-2",
    title: "Scaffolding staging adjustment & masonry working platform",
    status: "in-progress",
    date: "2026-09-08",
    time: "8:00 AM – 1:30 PM",
    trade: "4 Helpers",
    workersCount: 4,
    contractorName: "Malabar Site Crew",
    description: "Raising working deck boards, installing safety guardrails, and repositioning toe-boards along gridlines 3 to 6.",
    boqItemCode: "BOQ-02.1",
    boqItemName: "Heavy-Duty Scaffolding Rigging & Staging (Labour)",
    boqQuantity: "1,200 sq ft",
    ganttPhaseId: "phase-2",
    ganttPhaseName: "Phase 2: Superstructure Masonry & Lintel Level",
    serviceCategory: "Scaffolding & Working Platforms",
  },
  {
    id: "task-3",
    title: "Lintel rebar placement check with site engineer",
    status: "pending",
    date: "2026-09-08",
    time: "3:30 PM – 4:30 PM",
    trade: "Lead Mason & Site Supervisor",
    workersCount: 2,
    contractorName: "Site Supervision",
    description: "Checking 12mm Fe-500 rebar reinforcement spacing, stirrups hook anchorage, and cover block integrity over window openings.",
    boqItemCode: "BOQ-06.1",
    boqItemName: "Rebar Reinforcement Tying for Lintel & Chajja (Labour)",
    boqQuantity: "38 of 42 lin m",
    ganttPhaseId: "phase-2",
    ganttPhaseName: "Phase 2: Superstructure Masonry & Lintel Level",
    serviceCategory: "Structural Quality Assurance",
  },
  {
    id: "task-4",
    title: "Ground floor column curing & surface finish verification",
    status: "completed",
    date: "2026-09-07",
    time: "8:00 AM – 12:00 PM",
    trade: "4 Masons",
    workersCount: 4,
    contractorName: "Apex Integrated Civil",
    description: "Water ponding and wet hessian wrapping for 16 ground floor columns; structural plumbness verified with engineer.",
    boqItemCode: "BOQ-03.2",
    boqItemName: "Column Concrete Curing & Plumb Verification (Labour)",
    boqQuantity: "16 of 16 Columns",
    ganttPhaseId: "phase-1",
    ganttPhaseName: "Phase 1: Substructure & Foundation",
    serviceCategory: "Concrete Curing & QA",
  },
  {
    id: "task-5",
    title: "North facade tubular scaffolding erection & safety staging",
    status: "completed",
    date: "2026-09-07",
    time: "1:00 PM – 5:00 PM",
    trade: "6 Helpers & Riggers",
    workersCount: 6,
    contractorName: "Malabar Site Crew",
    description: "Erected 2-tier scaffolding on north elevation, toe boards fixed, and green safety tag issued.",
    boqItemCode: "BOQ-02.1",
    boqItemName: "Heavy-Duty Scaffolding Rigging & Safety Netting (Labour)",
    boqQuantity: "1,800 sq ft",
    ganttPhaseId: "phase-2",
    ganttPhaseName: "Phase 2: Superstructure Masonry & Lintel Level",
    serviceCategory: "Site Staging & Safety",
  },
  {
    id: "task-6",
    title: "Lintel shuttering fabrication & heavy prop erection",
    status: "scheduled",
    date: "2026-09-09",
    time: "8:00 AM – 2:00 PM",
    trade: "6 Masons & Carpenters",
    workersCount: 6,
    contractorName: "Apex Integrated Civil",
    description: "Fabricating marine plywood bottom boards and adjustable steel props under door and window openings.",
    boqItemCode: "BOQ-06.2",
    boqItemName: "Lintel Shuttering Fabrication & Heavy Prop Erection",
    boqQuantity: "38 lin m",
    ganttPhaseId: "phase-2",
    ganttPhaseName: "Phase 2: Superstructure Masonry & Lintel Level",
    serviceCategory: "Formwork & Support Engineering",
  },
  {
    id: "task-7",
    title: "Lintel beam concrete casting, vibrator compaction & leveling",
    status: "scheduled",
    date: "2026-09-09",
    time: "9:00 AM – 4:00 PM",
    trade: "2 Masons · 4 Helpers",
    workersCount: 6,
    contractorName: "Malabar Site Crew",
    description: "Pouring M25 grade concrete in lintel bands with mechanical needle vibrator compaction and trowel finishing.",
    boqItemCode: "BOQ-05.1",
    boqItemName: "In-situ Lintel Concrete Casting & Compaction (Labour)",
    boqQuantity: "38 lin m",
    ganttPhaseId: "phase-2",
    ganttPhaseName: "Phase 2: Superstructure Masonry & Lintel Level",
    serviceCategory: "Concrete Pouring & Compaction",
  },
  {
    id: "task-8",
    title: "Level 2 datum line transfer & masonry setting out",
    status: "completed",
    date: "2026-09-05",
    time: "8:00 AM – 4:30 PM",
    trade: "6 Masons · 2 Helpers",
    workersCount: 8,
    contractorName: "Apex Integrated Civil",
    description: "Transferring benchmark levels with dumpy level, snapping grid chalk lines, and laying dry corner block bonds.",
    boqItemCode: "BOQ-04.1",
    boqItemName: "Masonry Setting Out & Benchmark Datum (Labour)",
    boqQuantity: "Full Floor Plate",
    ganttPhaseId: "phase-2",
    ganttPhaseName: "Phase 2: Superstructure Masonry & Lintel Level",
    serviceCategory: "Block Masonry & Setting Out",
  },
  {
    id: "task-9",
    title: "South elevation external block wall laying up to sill",
    status: "completed",
    date: "2026-09-06",
    time: "8:00 AM – 5:00 PM",
    trade: "8 Masons · 4 Helpers",
    workersCount: 12,
    contractorName: "Apex Integrated Civil",
    description: "Raised 230mm solid block walls to 900mm sill height across gridlines 1 to 4 with level stringline checks.",
    boqItemCode: "BOQ-04.1",
    boqItemName: "230mm Solid Block Masonry Execution (Labour)",
    boqQuantity: "350 sq ft",
    ganttPhaseId: "phase-2",
    ganttPhaseName: "Phase 2: Superstructure Masonry & Lintel Level",
    serviceCategory: "Block Masonry Works",
  },
  {
    id: "task-10",
    title: "100mm interior dividing wall blockwork & joint raking",
    status: "scheduled",
    date: "2026-09-10",
    time: "8:00 AM – 5:00 PM",
    trade: "6 Masons · 4 Helpers",
    workersCount: 10,
    contractorName: "Apex Integrated Civil",
    description: "Laying 100mm partition walls between residential units with galvanized wire reinforcing in every 3rd course.",
    boqItemCode: "BOQ-04.2",
    boqItemName: "100mm Partition Blockwork & Bed Joint Raking (Labour)",
    boqQuantity: "420 sq ft",
    ganttPhaseId: "phase-2",
    ganttPhaseName: "Phase 2: Superstructure Masonry & Lintel Level",
    serviceCategory: "Interior Partition Masonry",
  },
  {
    id: "task-11",
    title: "Door frame holdfast grouting & partition wall raising",
    status: "scheduled",
    date: "2026-09-11",
    time: "8:00 AM – 4:30 PM",
    trade: "6 Masons · 2 Helpers",
    workersCount: 8,
    contractorName: "Apex Integrated Civil",
    description: "Trueing timber door bucks with spirit levels, grouting steel holdfasts into block joints, and raising jamb blocks.",
    boqItemCode: "BOQ-04.2",
    boqItemName: "Door Buck Anchoring & Jamb Masonry (Labour)",
    boqQuantity: "8 Openings",
    ganttPhaseId: "phase-2",
    ganttPhaseName: "Phase 2: Superstructure Masonry & Lintel Level",
    serviceCategory: "Interior Partition Masonry",
  },
  {
    id: "task-12",
    title: "Masonry joint deep raking & surface prep for plastering",
    status: "scheduled",
    date: "2026-09-15",
    time: "8:00 AM – 3:00 PM",
    trade: "4 Masons · 2 Helpers",
    workersCount: 6,
    contractorName: "Apex Integrated Civil",
    description: "Raking all mortar joints to 12mm depth, brushing off loose mortar, and washing brickwork for plaster bonding.",
    boqItemCode: "BOQ-08.1",
    boqItemName: "Joint Raking & Surface Preparation (Labour)",
    boqQuantity: "1,200 sq ft",
    ganttPhaseId: "phase-2",
    ganttPhaseName: "Phase 2: Superstructure Masonry & Lintel Level",
    serviceCategory: "Surface Finishing Preparation",
  },
  {
    id: "task-13",
    title: "12mm internal cement plastering with wood float finish",
    status: "scheduled",
    date: "2026-09-22",
    time: "8:00 AM – 5:00 PM",
    trade: "8 Masons · 4 Helpers",
    workersCount: 12,
    contractorName: "Apex Integrated Civil",
    description: "Applying 12mm base coat and fine float finish on bedroom walls; plumb, right-angle, and surface level checked.",
    boqItemCode: "BOQ-09.1",
    boqItemName: "Internal Cement Plastering 12mm Thick (Labour)",
    boqQuantity: "850 sq ft",
    ganttPhaseId: "phase-2",
    ganttPhaseName: "Phase 2: Superstructure Masonry & Lintel Level",
    serviceCategory: "Plastering & Surface Finishing",
  },
];
