import { ProjectScheduleActivity, ProjectSchedulePhase } from "./project-schedule.types";

export interface ProjectScheduleRepository {
  getPhasesByProjectId(projectId: string): Promise<ProjectSchedulePhase[]>;
  getActivitiesByProjectId(projectId: string): Promise<ProjectScheduleActivity[]>;
  saveActivity(activity: ProjectScheduleActivity): Promise<ProjectScheduleActivity>;
  deleteActivity(activityId: string): Promise<void>;
}

// Default mock phases and activities
export const DEFAULT_MOCK_PHASES: ProjectSchedulePhase[] = [
  { id: "phase-1", projectId: "ws-default", name: "Pre-design", wbsCode: "1.0", order: 1, status: "completed", weight: 5 },
  { id: "phase-2", projectId: "ws-default", name: "Design and approvals", wbsCode: "2.0", order: 2, status: "completed", weight: 10 },
  { id: "phase-3", projectId: "ws-default", name: "Documentation and BOQ", wbsCode: "3.0", order: 3, status: "completed", weight: 10 },
  { id: "phase-4", projectId: "ws-default", name: "Procurement", wbsCode: "4.0", order: 4, status: "completed", weight: 15 },
  { id: "phase-5", projectId: "ws-default", name: "Site mobilisation", wbsCode: "5.0", order: 5, status: "completed", weight: 10 },
  { id: "phase-6", projectId: "ws-default", name: "Structure", wbsCode: "6.0", order: 6, status: "active", weight: 30 },
  { id: "phase-7", projectId: "ws-default", name: "MEP", wbsCode: "7.0", order: 7, status: "not_started", weight: 10 },
  { id: "phase-8", projectId: "ws-default", name: "Finishes", wbsCode: "8.0", order: 8, status: "not_started", weight: 8 },
  { id: "phase-9", projectId: "ws-default", name: "Testing and handover", wbsCode: "9.0", order: 9, status: "not_started", weight: 2 },
];

export const DEFAULT_MOCK_ACTIVITIES: ProjectScheduleActivity[] = [
  {
    id: "task-1.1",
    projectId: "ws-default",
    phaseId: "phase-1",
    parentId: null,
    wbsCode: "1.1",
    title: "Site feasibility & soil testing report",
    description: "Geotechnical investigation and soil bearing capacity analysis.",
    type: "site_activity",
    status: "completed",
    plannedStartDate: "2026-07-01",
    plannedEndDate: "2026-07-07",
    baselineStartDate: "2026-07-01",
    baselineEndDate: "2026-07-07",
    actualStartDate: "2026-07-01",
    actualEndDate: "2026-07-07",
    completedAt: "2026-07-07",
    progressPercent: 100,
    weight: 2.5,
    ownerId: "usr-rahul",
    assigneeName: "Rahul Sharma",
    dependencies: [],
    visibility: "project",
    approvalStatus: "approved",
  },
  {
    id: "task-1.2",
    projectId: "ws-default",
    phaseId: "phase-1",
    parentId: null,
    wbsCode: "1.2",
    title: "Topographical & boundary survey",
    description: "Contour mapping and total station boundary verification.",
    type: "site_activity",
    status: "completed",
    plannedStartDate: "2026-07-05",
    plannedEndDate: "2026-07-10",
    baselineStartDate: "2026-07-05",
    baselineEndDate: "2026-07-10",
    actualStartDate: "2026-07-05",
    actualEndDate: "2026-07-10",
    completedAt: "2026-07-10",
    progressPercent: 100,
    weight: 2.5,
    ownerId: "usr-rahul",
    assigneeName: "Rahul Sharma",
    dependencies: [{ predecessorActivityId: "task-1.1", type: "finish_to_start", lagDays: 0 }],
    visibility: "project",
    approvalStatus: "approved",
  },
  {
    id: "task-2.1",
    projectId: "ws-default",
    phaseId: "phase-2",
    parentId: null,
    wbsCode: "2.1",
    title: "Architectural concept design sign-off",
    description: "Client review and sign-off on 3D floor plan layout.",
    type: "milestone",
    status: "completed",
    plannedStartDate: "2026-07-12",
    plannedEndDate: "2026-07-12",
    baselineStartDate: "2026-07-12",
    baselineEndDate: "2026-07-12",
    actualStartDate: "2026-07-12",
    actualEndDate: "2026-07-12",
    completedAt: "2026-07-12",
    progressPercent: 100,
    weight: 5,
    ownerId: "usr-arjun",
    assigneeName: "Arjun Mehta",
    dependencies: [],
    visibility: "project",
    approvalStatus: "approved",
    isMilestone: true,
  },
  {
    id: "task-2.2",
    projectId: "ws-default",
    phaseId: "phase-2",
    parentId: null,
    wbsCode: "2.2",
    title: "Statutory municipal permit submission",
    description: "Submission of structural drawings to BBMP authority.",
    type: "approval",
    status: "completed",
    plannedStartDate: "2026-07-14",
    plannedEndDate: "2026-07-20",
    baselineStartDate: "2026-07-14",
    baselineEndDate: "2026-07-20",
    actualStartDate: "2026-07-14",
    actualEndDate: "2026-07-20",
    completedAt: "2026-07-20",
    progressPercent: 100,
    weight: 5,
    ownerId: "usr-anil",
    assigneeName: "Anil Kumar",
    dependencies: [{ predecessorActivityId: "task-2.1", type: "finish_to_start", lagDays: 0 }],
    visibility: "project",
    approvalStatus: "approved",
  },
  {
    id: "task-3.1",
    projectId: "ws-default",
    phaseId: "phase-3",
    parentId: null,
    wbsCode: "3.1",
    title: "Detailed structural & MEP working drawings",
    description: "Column schedule, beam reinforcement details, and plumbing layout.",
    type: "activity",
    status: "completed",
    plannedStartDate: "2026-07-18",
    plannedEndDate: "2026-07-24",
    baselineStartDate: "2026-07-18",
    baselineEndDate: "2026-07-24",
    actualStartDate: "2026-07-18",
    actualEndDate: "2026-07-24",
    completedAt: "2026-07-24",
    progressPercent: 100,
    weight: 5,
    ownerId: "usr-priya",
    assigneeName: "Priya Patel",
    dependencies: [],
    visibility: "project",
    approvalStatus: "approved",
  },
  {
    id: "task-3.2",
    projectId: "ws-default",
    phaseId: "phase-3",
    parentId: null,
    wbsCode: "3.2",
    title: "BOQ rate verification & approval",
    description: "Itemized material estimate rate audit.",
    type: "milestone",
    status: "completed",
    plannedStartDate: "2026-07-22",
    plannedEndDate: "2026-07-22",
    baselineStartDate: "2026-07-22",
    baselineEndDate: "2026-07-22",
    actualStartDate: "2026-07-22",
    actualEndDate: "2026-07-22",
    completedAt: "2026-07-22",
    progressPercent: 100,
    weight: 5,
    ownerId: "usr-arjun",
    assigneeName: "Arjun Mehta",
    dependencies: [],
    visibility: "project",
    approvalStatus: "approved",
    isMilestone: true,
  },
  {
    id: "task-4.1",
    projectId: "ws-default",
    phaseId: "phase-4",
    parentId: null,
    wbsCode: "4.1",
    title: "TMT Steel & Ready-Mix Concrete PO issue",
    description: "Purchase order release for Fe550D grade steel and M30 concrete.",
    type: "activity",
    status: "completed",
    plannedStartDate: "2026-07-21",
    plannedEndDate: "2026-07-25",
    baselineStartDate: "2026-07-21",
    baselineEndDate: "2026-07-25",
    actualStartDate: "2026-07-21",
    actualEndDate: "2026-07-25",
    completedAt: "2026-07-25",
    progressPercent: 100,
    weight: 7.5,
    ownerId: "usr-rahul",
    assigneeName: "Rahul Sharma",
    dependencies: [],
    visibility: "project",
    approvalStatus: "approved",
  },
  {
    id: "task-4.2",
    projectId: "ws-default",
    phaseId: "phase-4",
    parentId: null,
    wbsCode: "4.2",
    title: "Revised electrical layout approval",
    description: "Client approval required for modified DB routing.",
    type: "approval",
    status: "in_progress",
    plannedStartDate: "2026-07-28",
    plannedEndDate: "2026-07-30",
    baselineStartDate: "2026-07-28",
    baselineEndDate: "2026-07-30",
    actualStartDate: "2026-07-28",
    actualEndDate: null,
    completedAt: null,
    progressPercent: 50,
    weight: 7.5,
    ownerId: "usr-anil",
    assigneeName: "Anil Kumar",
    dependencies: [],
    visibility: "project",
    approvalStatus: "pending",
  },
  {
    id: "task-6.1",
    projectId: "ws-default",
    phaseId: "phase-6",
    parentId: null,
    wbsCode: "6.1",
    title: "Foundation excavation & PCC footing",
    description: "Earth excavation down to 3m depth and M15 PCC levelling.",
    type: "site_activity",
    status: "in_progress",
    plannedStartDate: "2026-07-25",
    plannedEndDate: "2026-08-05",
    baselineStartDate: "2026-07-24",
    baselineEndDate: "2026-08-02",
    actualStartDate: "2026-07-25",
    actualEndDate: null,
    completedAt: null,
    progressPercent: 68,
    weight: 15,
    ownerId: "usr-rahul",
    assigneeName: "Rahul Sharma",
    dependencies: [],
    visibility: "project",
    approvalStatus: "approved",
    criticalPath: true,
  },
  {
    id: "task-6.2",
    projectId: "ws-default",
    phaseId: "phase-6",
    parentId: null,
    wbsCode: "6.2",
    title: "Roof Slab Casting",
    description: "RMC pour and shuttering vibration inspection for first floor slab.",
    type: "milestone",
    status: "in_progress",
    plannedStartDate: "2026-07-28",
    plannedEndDate: "2026-07-28",
    baselineStartDate: "2026-07-28",
    baselineEndDate: "2026-07-28",
    actualStartDate: "2026-07-28",
    actualEndDate: null,
    completedAt: null,
    progressPercent: 40,
    weight: 15,
    ownerId: "usr-arjun",
    assigneeName: "Arjun Mehta",
    dependencies: [{ predecessorActivityId: "task-6.1", type: "finish_to_start", lagDays: 0 }],
    visibility: "project",
    approvalStatus: "approved",
    isMilestone: true,
    criticalPath: true,
  },
  {
    id: "task-6.3",
    projectId: "ws-default",
    phaseId: "phase-6",
    parentId: null,
    wbsCode: "6.3",
    title: "First floor column shuttering & steel fixings",
    description: "Vertical rebar tying and ply shuttering box alignment.",
    type: "activity",
    status: "not_started",
    plannedStartDate: "2026-08-06",
    plannedEndDate: "2026-08-18",
    baselineStartDate: "2026-08-05",
    baselineEndDate: "2026-08-15",
    actualStartDate: null,
    actualEndDate: null,
    completedAt: null,
    progressPercent: 0,
    weight: 10,
    ownerId: "usr-priya",
    assigneeName: "Priya Patel",
    dependencies: [{ predecessorActivityId: "task-6.2", type: "finish_to_start", lagDays: 0 }],
    visibility: "project",
    approvalStatus: "not_required",
  },
  {
    id: "task-7.1",
    projectId: "ws-default",
    phaseId: "phase-7",
    parentId: null,
    wbsCode: "7.1",
    title: "Conduit piping & electrical wall chasing",
    description: "PVC conduit insertion into brickwork slots.",
    type: "activity",
    status: "not_started",
    plannedStartDate: "2026-08-15",
    plannedEndDate: "2026-08-30",
    baselineStartDate: "2026-08-15",
    baselineEndDate: "2026-08-30",
    actualStartDate: null,
    actualEndDate: null,
    completedAt: null,
    progressPercent: 0,
    weight: 5,
    ownerId: "usr-anil",
    assigneeName: "Anil Kumar",
    dependencies: [{ predecessorActivityId: "task-6.3", type: "finish_to_start", lagDays: 0 }],
    visibility: "project",
    approvalStatus: "not_required",
  },
];

export class MockProjectScheduleRepository implements ProjectScheduleRepository {
  async getPhasesByProjectId(projectId: string): Promise<ProjectSchedulePhase[]> {
    const matched = DEFAULT_MOCK_PHASES.filter((p) => p.projectId === projectId);
    if (matched.length > 0) return matched;
    return DEFAULT_MOCK_PHASES.map((p) => ({ ...p, projectId }));
  }

  async getActivitiesByProjectId(projectId: string): Promise<ProjectScheduleActivity[]> {
    const matched = DEFAULT_MOCK_ACTIVITIES.filter((a) => a.projectId === projectId);
    if (matched.length > 0) return matched;
    return DEFAULT_MOCK_ACTIVITIES.map((a) => ({ ...a, projectId }));
  }

  async saveActivity(activity: ProjectScheduleActivity): Promise<ProjectScheduleActivity> {
    const idx = DEFAULT_MOCK_ACTIVITIES.findIndex((a) => a.id === activity.id);
    if (idx >= 0) {
      DEFAULT_MOCK_ACTIVITIES[idx] = activity;
    } else {
      DEFAULT_MOCK_ACTIVITIES.push(activity);
    }
    return activity;
  }

  async deleteActivity(activityId: string): Promise<void> {
    const idx = DEFAULT_MOCK_ACTIVITIES.findIndex((a) => a.id === activityId);
    if (idx >= 0) {
      DEFAULT_MOCK_ACTIVITIES.splice(idx, 1);
    }
  }
}

export const projectScheduleRepository = new MockProjectScheduleRepository();
