export const WORKSPACE_CONFIG = {
  brandName: "Kallisto",
  currentWorkspaceName: "Arjun Architects",
  workspaceType: "Virtual Office",
  navigationLabel: "Hive Studio",
  studioRoute: "/studio",
  currency: "INR",
} as const;

export interface BreadcrumbMeta {
  parent: string;
  current: string;
}

export const ROUTE_BREADCRUMBS: Record<string, BreadcrumbMeta> = {
  "/": { parent: WORKSPACE_CONFIG.workspaceType, current: WORKSPACE_CONFIG.navigationLabel },
  "/home": { parent: WORKSPACE_CONFIG.workspaceType, current: WORKSPACE_CONFIG.navigationLabel },
  "/studio": { parent: WORKSPACE_CONFIG.workspaceType, current: WORKSPACE_CONFIG.navigationLabel },
  "/studio/boq": { parent: WORKSPACE_CONFIG.navigationLabel, current: "BOQ Engine" },
  "/studio/ai-plans": { parent: WORKSPACE_CONFIG.navigationLabel, current: "AI Plans" },
  "/studio/proposals": { parent: WORKSPACE_CONFIG.navigationLabel, current: "Proposals" },
  "/virtual-office": { parent: WORKSPACE_CONFIG.workspaceType, current: WORKSPACE_CONFIG.navigationLabel },
  "/enquiries": { parent: WORKSPACE_CONFIG.workspaceType, current: "Enquiries" },
  "/projects": { parent: WORKSPACE_CONFIG.workspaceType, current: "Projects" },
  "/team": { parent: WORKSPACE_CONFIG.workspaceType, current: "Team" },
  "/clients": { parent: WORKSPACE_CONFIG.workspaceType, current: "Clients" },
  "/public-profile": { parent: WORKSPACE_CONFIG.workspaceType, current: "Public Profile" },
  "/portfolio": { parent: WORKSPACE_CONFIG.workspaceType, current: "Portfolio" },
  "/documents": { parent: WORKSPACE_CONFIG.workspaceType, current: "Documents" },
  "/calendar": { parent: WORKSPACE_CONFIG.workspaceType, current: "Calendar" },
  "/payments": { parent: WORKSPACE_CONFIG.workspaceType, current: "Payments" },
  "/analytics": { parent: WORKSPACE_CONFIG.workspaceType, current: "Analytics" },
  "/hub": { parent: WORKSPACE_CONFIG.workspaceType, current: "Hub" },
  "/hands": { parent: WORKSPACE_CONFIG.workspaceType, current: "Hands" },
  "/hands/trades": { parent: "Hands", current: "Find Trades" },
  "/basics": { parent: WORKSPACE_CONFIG.workspaceType, current: "Basics" },
  "/basics/experts": { parent: "Basics", current: "Find Experts" },
  "/basics/requirements": { parent: "Basics", current: "Requirements" },
  "/basics/proposals": { parent: "Basics", current: "Proposals" },
  "/basics/engagements": { parent: "Basics", current: "Engagements" },
  "/tools": { parent: WORKSPACE_CONFIG.workspaceType, current: "More Tools" },
  "/client": { parent: "Client Portal", current: "Ask Odin" },
  "/client/overview": { parent: "Client Portal", current: "Ask Odin" },
  "/client/projects": { parent: "Client Portal", current: "Projects" },
  "/client/enquiries": { parent: "Client Portal", current: "Enquiries" },
  "/client/payments": { parent: "Client Portal", current: "Payments" },
  "/client/providers": { parent: "Client Portal", current: "Providers" },
  "/client/settings": { parent: "Client Portal", current: "Settings" },
  "/client/settings/profile": { parent: "Settings", current: "Profile" },
  "/client/settings/security": { parent: "Settings", current: "Security & Login" },
  "/client/settings/project-preferences": { parent: "Settings", current: "Project Preferences" },
  "/client/settings/project-access": { parent: "Settings", current: "Project Access" },
  "/client/settings/notifications": { parent: "Settings", current: "Notifications" },
  "/client/settings/communication": { parent: "Settings", current: "Communication Preferences" },
  "/client/settings/payment-methods": { parent: "Settings", current: "Payment Methods" },
  "/client/settings/billing": { parent: "Settings", current: "Billing & Invoices" },
  "/client/settings/appearance": { parent: "Settings", current: "Appearance" },
  "/client/settings/language-region": { parent: "Settings", current: "Language & Region" },
  "/client/settings/privacy": { parent: "Settings", current: "Privacy & Data" },
  "/client/help": { parent: "Client Portal", current: "Help & Support" },
};
