import type { DeploymentActivityTask } from "../types/hands.types";

export interface BoqReferenceItem {
  code: string;
  name: string;
  trade: string;
  unitScope: string;
  serviceCategory: string;
}

export interface GanttPhaseReference {
  id: string;
  name: string;
  dateRange: string;
  status: "completed" | "in-progress" | "upcoming";
  dayProgress: string;
}

export const NILA_BOQ_ITEMS: BoqReferenceItem[] = [
  {
    code: "BOQ-04.1",
    name: "230mm Wire-Cut Red Clay Brickwork in CM 1:6",
    trade: "Masons",
    unitScope: "450 / 1,200 sq ft",
    serviceCategory: "Civil & Masonry Works",
  },
  {
    code: "BOQ-04.2",
    name: "Mortar Batch Mixing & Scaffolding Staging",
    trade: "Helpers",
    unitScope: "12 of 28 Batches",
    serviceCategory: "Material Preparation & Logistics",
  },
  {
    code: "BOQ-06.1",
    name: "Rebar Reinforcement Inspection for Lintel & Chajja",
    trade: "Site Supervisor",
    unitScope: "38 of 42 lin m",
    serviceCategory: "Structural Quality Assurance",
  },
  {
    code: "BOQ-06.2",
    name: "Lintel Shuttering Fabrication & Heavy Prop Erection",
    trade: "Masons & Carpenters",
    unitScope: "38 lin m",
    serviceCategory: "Formwork & Support Engineering",
  },
  {
    code: "BOQ-06.3",
    name: "M-25 Grade Lintel Beam Concrete Casting & Compaction",
    trade: "Masons & Concrete Crew",
    unitScope: "4.5 cu m",
    serviceCategory: "Concrete & Structural Works",
  },
  {
    code: "BOQ-06.4",
    name: "Lintel De-shuttering & Structural Quality Audit",
    trade: "Site Supervisor",
    unitScope: "38 lin m verified",
    serviceCategory: "Structural Quality Assurance",
  },
  {
    code: "BOQ-03.2",
    name: "Ground Floor Column Concrete Curing & Strength Test",
    trade: "Masons",
    unitScope: "16 of 16 Columns",
    serviceCategory: "Concrete Curing & Testing",
  },
  {
    code: "BOQ-02.1",
    name: "Heavy-Duty Tubular Scaffolding Erection & Safety Netting",
    trade: "Helpers & Riggers",
    unitScope: "1,800 sq ft",
    serviceCategory: "Site Logistics & Safety",
  },
  {
    code: "BOQ-01.3",
    name: "Coarse Aggregate & OPC-53 Cement Unloading & Staging",
    trade: "Helpers",
    unitScope: "40 Bags / 3,000 Bricks",
    serviceCategory: "Material Preparation & Logistics",
  },
  {
    code: "BOQ-08.1",
    name: "Exterior Cement Plastering (1:4) with Waterproofer",
    trade: "Masons",
    unitScope: "350 sq ft",
    serviceCategory: "Finishing & Plastering",
  },
];

export const NILA_GANTT_PHASES: GanttPhaseReference[] = [
  {
    id: "phase-1",
    name: "Phase 1: Substructure & Foundation",
    dateRange: "Aug 15 – Sep 02, 2026",
    status: "completed",
    dayProgress: "Day 18 of 18 · Completed",
  },
  {
    id: "phase-2",
    name: "Phase 2: Superstructure Masonry & Lintel Level",
    dateRange: "Sep 03 – Sep 28, 2026",
    status: "in-progress",
    dayProgress: "Day 6 of 26 · In progress",
  },
  {
    id: "phase-3",
    name: "Phase 3: Roof Slab Shuttering & Casting",
    dateRange: "Sep 29 – Oct 18, 2026",
    status: "upcoming",
    dayProgress: "20 Days · Starts Sep 29",
  },
  {
    id: "phase-4",
    name: "Phase 4: MEP Rough-in & Plastering",
    dateRange: "Oct 19 – Nov 12, 2026",
    status: "upcoming",
    dayProgress: "25 Days · Starts Oct 19",
  },
  {
    id: "phase-5",
    name: "Phase 5: Flooring & Final Handover",
    dateRange: "Nov 13 – Dec 05, 2026",
    status: "upcoming",
    dayProgress: "23 Days · Starts Nov 13",
  },
];

export const INITIAL_DEPLOYMENT_TASKS: DeploymentActivityTask[] = [
  {
    id: "task-1",
    title: "Perimeter brick masonry & plumb line verification",
    status: "in-progress",
    date: "2026-09-08",
    time: "8:00 AM – 1:30 PM",
    trade: "6 Masons",
    contractorName: "Apex Integrated Civil",
    description: "North wing 9-inch wall alignment, plumb line verification, and bed joint thickness check (10-12mm).",
    boqItemCode: "BOQ-04.1",
    boqItemName: "230mm Wire-Cut Red Clay Brickwork in CM 1:6",
    boqQuantity: "450 / 1,200 sq ft",
    ganttPhaseId: "phase-2",
    ganttPhaseName: "Phase 2: Superstructure Masonry & Lintel Level",
    serviceCategory: "Civil & Masonry Works",
    workersCount: 6,
  },
  {
    id: "task-2",
    title: "Mortar preparation & material staging to scaffolding",
    status: "in-progress",
    date: "2026-09-08",
    time: "8:00 AM – 4:30 PM",
    trade: "6 Helpers (2 absent)",
    contractorName: "Malabar Site Crew",
    description: "Batch mixing 1:4 cement-sand mortar, hoisting bricks to first floor platform, and scaffolding barrier check.",
    boqItemCode: "BOQ-04.2",
    boqItemName: "Mortar Batch Mixing & Scaffolding Staging",
    boqQuantity: "12 of 28 Batches",
    ganttPhaseId: "phase-2",
    ganttPhaseName: "Phase 2: Superstructure Masonry & Lintel Level",
    serviceCategory: "Material Preparation & Logistics",
    workersCount: 6,
  },
  {
    id: "task-3",
    title: "Lintel rebar placement check with site engineer",
    status: "pending",
    date: "2026-09-08",
    time: "3:30 PM – 4:30 PM",
    trade: "Site Supervisor Rajeev K.",
    contractorName: "Site Supervision",
    description: "Physical inspection of 12mm Fe-500 rebar reinforcement spacing, stirrups hook anchorage, and cover block integrity.",
    boqItemCode: "BOQ-06.1",
    boqItemName: "Rebar Reinforcement Inspection for Lintel & Chajja",
    boqQuantity: "38 of 42 lin m",
    ganttPhaseId: "phase-2",
    ganttPhaseName: "Phase 2: Superstructure Masonry & Lintel Level",
    serviceCategory: "Structural Quality Assurance",
    workersCount: 1,
  },
  {
    id: "task-4",
    title: "Ground floor column curing & QA cube testing",
    status: "completed",
    date: "2026-09-07",
    time: "8:00 AM – 12:00 PM",
    trade: "4 Masons",
    contractorName: "Apex Integrated Civil",
    description: "Water ponding and wet hessian wrapping for 16 ground floor columns; 7-day cube compression test verified with engineer.",
    boqItemCode: "BOQ-03.2",
    boqItemName: "Ground Floor Column Concrete Curing & Strength Test",
    boqQuantity: "16 of 16 Columns",
    ganttPhaseId: "phase-1",
    ganttPhaseName: "Phase 1: Substructure & Foundation",
    serviceCategory: "Concrete Curing & Testing",
    workersCount: 4,
  },
  {
    id: "task-5",
    title: "North facade tubular scaffolding erection & safety guard",
    status: "completed",
    date: "2026-09-07",
    time: "1:00 PM – 5:00 PM",
    trade: "6 Helpers & Riggers",
    contractorName: "Malabar Site Crew",
    description: "Completed erection of 2-tier scaffolding on north elevation, toe boards fixed, and green safety tag issued.",
    boqItemCode: "BOQ-02.1",
    boqItemName: "Heavy-Duty Tubular Scaffolding Erection & Safety Netting",
    boqQuantity: "1,800 sq ft",
    ganttPhaseId: "phase-2",
    ganttPhaseName: "Phase 2: Superstructure Masonry & Lintel Level",
    serviceCategory: "Site Logistics & Safety",
    workersCount: 6,
  },
  {
    id: "task-6",
    title: "Lintel shuttering fabrication & heavy prop erection",
    status: "scheduled",
    date: "2026-09-09",
    time: "8:00 AM – 2:00 PM",
    trade: "6 Masons & Carpenters",
    contractorName: "Apex Integrated Civil",
    description: "Fabricating marine plywood bottom boards and adjustable steel props under door and window openings.",
    boqItemCode: "BOQ-06.2",
    boqItemName: "Lintel Shuttering Fabrication & Heavy Prop Erection",
    boqQuantity: "38 lin m",
    ganttPhaseId: "phase-2",
    ganttPhaseName: "Phase 2: Superstructure Masonry & Lintel Level",
    serviceCategory: "Formwork & Support Engineering",
    workersCount: 6,
  },
  {
    id: "task-7",
    title: "Coarse aggregate & OPC-53 cement transport to mixer",
    status: "scheduled",
    date: "2026-09-09",
    time: "9:00 AM – 4:00 PM",
    trade: "4 Helpers",
    contractorName: "Malabar Site Crew",
    description: "Transfer 20mm aggregate and 40 cement bags from staging bay 2 to concrete mixer station ahead of lintel pour.",
    boqItemCode: "BOQ-01.3",
    boqItemName: "Coarse Aggregate & OPC-53 Cement Unloading & Staging",
    boqQuantity: "40 Bags / 3,000 Bricks",
    ganttPhaseId: "phase-2",
    ganttPhaseName: "Phase 2: Superstructure Masonry & Lintel Level",
    serviceCategory: "Material Preparation & Logistics",
    workersCount: 4,
  },
  {
    id: "task-8",
    title: "M-25 concrete pour & mechanical vibrator compaction",
    status: "scheduled",
    date: "2026-09-10",
    time: "8:30 AM – 3:30 PM",
    trade: "8 Masons & Concrete Crew",
    contractorName: "Apex Integrated Civil",
    description: "Continuous pour for 38 lin m lintel beams with needle vibrator compaction to eliminate honeycomb voids.",
    boqItemCode: "BOQ-06.3",
    boqItemName: "M-25 Grade Lintel Beam Concrete Casting & Compaction",
    boqQuantity: "4.5 cu m",
    ganttPhaseId: "phase-2",
    ganttPhaseName: "Phase 2: Superstructure Masonry & Lintel Level",
    serviceCategory: "Concrete & Structural Works",
    workersCount: 8,
  },
  {
    id: "task-9",
    title: "Lintel de-shuttering & structural QA sign-off",
    status: "scheduled",
    date: "2026-09-12",
    time: "10:00 AM – 1:00 PM",
    trade: "Site Supervisor Rajeev K.",
    contractorName: "Site Supervision",
    description: "Formwork stripping inspection, surface line verification, and client milestone sign-off documentation.",
    boqItemCode: "BOQ-06.4",
    boqItemName: "Lintel De-shuttering & Structural Quality Audit",
    boqQuantity: "38 lin m verified",
    ganttPhaseId: "phase-2",
    ganttPhaseName: "Phase 2: Superstructure Masonry & Lintel Level",
    serviceCategory: "Structural Quality Assurance",
    workersCount: 1,
  },
  {
    id: "task-10",
    title: "Exterior plastering trial patch & waterproofing coat",
    status: "cancelled",
    date: "2026-09-05",
    time: "9:00 AM – 1:00 PM",
    trade: "2 Masons",
    contractorName: "Apex Integrated Civil",
    description: "Test patch of 1:4 cement sand plaster with integral waterproofer on external boundary wall.",
    boqItemCode: "BOQ-08.1",
    boqItemName: "Exterior Cement Plastering (1:4) with Waterproofer",
    boqQuantity: "350 sq ft",
    ganttPhaseId: "phase-2",
    ganttPhaseName: "Phase 2: Superstructure Masonry & Lintel Level",
    serviceCategory: "Finishing & Plastering",
    cancellationReason: "Heavy unseasonal monsoon rainfall; rescheduled to post-lintel phase to avoid wash-out.",
    cancelledAt: "Sep 05, 2026 · 08:15 AM",
    cancelledBy: "Service Provider (Rajeev K.)",
    workersCount: 2,
  },
];
