import type {
  HandsOverviewData,
  WorkforceRequest,
  WorkforceRequestDraft,
  WorkforceRequestSubmission,
} from "../types/hands.types";

const overviewData: HandsOverviewData = {
  metrics: [
    {
      id: "workers-today",
      label: "Workers on site today",
      value: 34,
      valueFormat: "number",
      supportingText: "Across 4 active sites",
      tone: "neutral",
      icon: "workers",
    },
    {
      id: "active-deployments",
      label: "Active deployments",
      value: 4,
      valueFormat: "number",
      supportingText: "1 ending this week",
      tone: "warning",
      icon: "deployments",
    },
    {
      id: "open-positions",
      label: "Open positions",
      value: 8,
      valueFormat: "number",
      supportingText: "Across 3 requests",
      tone: "neutral",
      icon: "positions",
    },
    {
      id: "weekly-cost",
      label: "Labour cost this week",
      value: 182400,
      valueFormat: "currency",
      supportingText: "12% above last week",
      tone: "warning",
      icon: "cost",
    },
  ],
  deployments: [
    {
      id: "deployment-nila",
      projectId: "proj-001",
      projectName: "Nila Residence",
      location: "Thiruvananthapuram, Kerala",
      workforce: "8 masons · 10 helpers",
      shift: "8:00 AM – 5:00 PM",
      attendance: { state: "recorded", present: 16, total: 18 },
      supervisor: "Rajeev K.",
      dailyCost: 19800,
      status: "Needs attention",
      startDate: "22 Jul 2026",
      endDate: "08 Aug 2026",
      coverImage: "/assets/projectbg.webp",
      category: "Construction & Structural",
      overallProgress: 70,
      dueLabel: "Due in 3d",
      workerUpdate: "8 masons · 10 helpers (16/18 checked in • 2 absent)",
      activeWorkers: 16,
      onLeaveWorkers: 2,
      workerTypes: "8 Masons · 10 Helpers",
      contractors: [
        {
          id: "contractor-apex",
          name: "Apex Integrated Civil",
          trade: "Masonry",
          workerCount: 8,
          crewId: "crew-masons-01",
          rating: 4.9,
          reviewCount: 42,
          leadName: "Rajan K.",
          experienceYears: 14,
          verified: true,
          badge: "Kallisto Civil Guild",
          specialization: "Structural Brickwork & AAC Blockwork",
        },
        {
          id: "contractor-malabar",
          name: "Malabar Site Crew",
          trade: "Helpers",
          workerCount: 10,
          crewId: "crew-helpers-01",
          rating: 4.8,
          reviewCount: 54,
          leadName: "Gireesh Kumar",
          experienceYears: 7,
          verified: true,
          badge: "Verified Site Workforce",
          specialization: "Material Staging & Site Handling",
        },
      ],
      todayActivity: {
        headline: "First-floor brick masonry & lintel level preparation",
        description:
          "Laying 9-inch perimeter brick walls and setting shuttering supports along the eastern residential wing.",
        tasks: [
          {
            id: "act-1",
            title: "Perimeter brick masonry & plumb line verification",
            status: "in-progress",
            time: "8:00 AM – 1:30 PM",
            trade: "8 Masons",
          },
          {
            id: "act-2",
            title: "Mortar preparation & material staging to scaffolding",
            status: "in-progress",
            time: "8:00 AM – 4:30 PM",
            trade: "8 Helpers (2 absent)",
          },
          {
            id: "act-3",
            title: "Lintel rebar placement check with site engineer",
            status: "pending",
            time: "3:30 PM – 4:30 PM",
            trade: "Supervisor Rajeev K.",
          },
        ],
        siteLog:
          "Supervisor Rajeev K. logged: Shift underway at 8:00 AM. Two helper absences noted in crew muster; masonry line 1 running at reduced staging pace until replacement workers are assigned.",
        loggedAt: "Today, 10:45 AM",
      },
    },
    {
      id: "deployment-arjun",
      projectId: "proj-002",
      projectName: "Arjun Villa",
      location: "Kochi, Kerala",
      workforce: "6 painters",
      shift: "8:30 AM – 5:30 PM",
      attendance: { state: "recorded", present: 6, total: 6 },
      supervisor: "Manoj P.",
      dailyCost: 7200,
      status: "Active",
      startDate: "24 Jul 2026",
      endDate: "31 Jul 2026",
      coverImage:
        "https://images.unsplash.com/photo-1613977257363-707ba9348227?w=900&auto=format&fit=crop&q=80",
      category: "Interior Finishes",
      overallProgress: 85,
      dueLabel: "Due in 7d",
      workerUpdate: "6 painters (6/6 checked in • 2nd coat on track)",
      activeWorkers: 6,
      onLeaveWorkers: 0,
      workerTypes: "6 Painters",
      contractorName: "Chroma Finishes & Paint Crew",
      contractors: [
        {
          id: "contractor-chroma",
          name: "Chroma Finishes & Paint Crew",
          trade: "Painters",
          workerCount: 6,
          crewId: "crew-painters-01",
          rating: 4.85,
          reviewCount: 31,
          leadName: "Binoy George",
          experienceYears: 8,
          verified: true,
          badge: "Asian Paints Certified",
          specialization: "Weatherproof Primer & Exterior Finish",
        },
      ],
      todayActivity: {
        headline: "Exterior waterproof primer & surface smoothing",
        description:
          "Applying second coat acrylic exterior primer on North facade and finishing surface sanding.",
        tasks: [
          {
            id: "act-1",
            title: "Wall sanding & micro-crack putty application",
            status: "completed",
            time: "8:30 AM – 12:00 PM",
            trade: "3 Painters",
          },
          {
            id: "act-2",
            title: "Second coat acrylic primer rolling & edge cutting",
            status: "in-progress",
            time: "1:00 PM – 5:30 PM",
            trade: "3 Painters",
          },
        ],
        siteLog:
          "Supervisor Manoj P. logged: Weather dry and optimal. North elevation sanded and approved. All 6 painters checked in on time.",
        loggedAt: "Today, 11:30 AM",
      },
    },
    {
      id: "deployment-marina",
      projectId: "proj-003",
      projectName: "Marina Office",
      location: "Kozhikode, Kerala",
      workforce: "4 electricians",
      shift: "9:00 AM – 6:00 PM",
      attendance: { state: "recorded", present: 4, total: 4 },
      supervisor: "Shafeeq M.",
      dailyCost: 6000,
      status: "Active",
      startDate: "21 Jul 2026",
      endDate: "28 Jul 2026",
      coverImage:
        "https://images.unsplash.com/photo-1497366216548-37526070297c?w=900&auto=format&fit=crop&q=80",
      category: "MEP & Electrical",
      overallProgress: 90,
      dueLabel: "Ends Tomorrow",
      workerUpdate: "4 electricians (4/4 checked in • Final rough-in)",
      activeWorkers: 4,
      onLeaveWorkers: 0,
      workerTypes: "4 Electricians",
      contractorName: "Circuit MEP Solutions",
      contractors: [
        {
          id: "contractor-circuit",
          name: "Circuit MEP Solutions",
          trade: "Electricians",
          workerCount: 4,
          crewId: "crew-electricians-01",
          rating: 4.95,
          reviewCount: 58,
          leadName: "Shaji Mathew",
          experienceYears: 12,
          verified: true,
          badge: "Class-B Electrical Guild",
          specialization: "Distribution Board & Conduit Cabling",
        },
      ],
      todayActivity: {
        headline: "Conduit wiring & DB distribution board termination",
        description:
          "Pulling 4 sq.mm copper circuit cables through ceiling conduits and testing load distribution.",
        tasks: [
          {
            id: "act-1",
            title: "Main feeder line pulling to Distribution Board 2",
            status: "completed",
            time: "9:00 AM – 1:00 PM",
            trade: "2 Electricians",
          },
          {
            id: "act-2",
            title: "Circuit loop testing and breaker tagging",
            status: "in-progress",
            time: "2:00 PM – 5:30 PM",
            trade: "2 Electricians",
          },
        ],
        siteLog:
          "Supervisor Shafeeq M. logged: Main feeder cable pulled without obstruction. Insulation resistance test scheduled before 5:00 PM.",
        loggedAt: "Today, 01:15 PM",
      },
    },
    {
      id: "deployment-green",
      projectId: "proj-004",
      projectName: "Green Courtyard",
      location: "Thrissur, Kerala",
      workforce: "5 carpenters",
      shift: "8:00 AM – 5:00 PM",
      attendance: { state: "pending" },
      supervisor: "Arun S.",
      dailyCost: 7500,
      status: "Awaiting check-in",
      startDate: "27 Jul 2026",
      endDate: "04 Aug 2026",
      coverImage:
        "https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=900&auto=format&fit=crop&q=80",
      category: "Carpentry & Joinery",
      overallProgress: 45,
      dueLabel: "Due in 8d",
      workerUpdate: "5 carpenters (Shift 8:00 AM • Awaiting check-in)",
      activeWorkers: 5,
      onLeaveWorkers: 0,
      workerTypes: "5 Carpenters",
      contractors: [
        {
          id: "contractor-forma",
          name: "Forma Woodworks",
          trade: "Carpentry",
          workerCount: 3,
          crewId: "crew-carpenters-01",
          rating: 4.9,
          reviewCount: 48,
          leadName: "Manoj V.",
          experienceYears: 13,
          verified: true,
          badge: "Master Joinery Guild",
          specialization: "Hardwood Door Framing & Shuttering",
        },
        {
          id: "contractor-heritage",
          name: "Heritage Joinery",
          trade: "Joinery",
          workerCount: 2,
          crewId: "crew-carpenters-01",
          rating: 4.8,
          reviewCount: 26,
          leadName: "Arun S.",
          experienceYears: 9,
          verified: true,
          badge: "Kallisto Verified",
          specialization: "Window Joinery & Brass Alignment",
        },
      ],
      todayActivity: {
        headline: "Hardwood door frame fixing & window joinery alignment",
        description:
          "Positioning teak door frames across ground floor rooms and anchoring frame brackets.",
        tasks: [
          {
            id: "act-1",
            title: "Main entrance & bed 1 teak wood frame fixing",
            status: "pending",
            time: "8:00 AM – 1:00 PM",
            trade: "3 Carpenters",
          },
          {
            id: "act-2",
            title: "Window shutter alignment and brass fitting check",
            status: "pending",
            time: "1:30 PM – 5:00 PM",
            trade: "2 Carpenters",
          },
        ],
        siteLog:
          "Shift scheduled to begin at 8:00 AM. Supervisor Arun S. to confirm muster and tool handover upon arrival.",
        loggedAt: "Pending shift start",
      },
    },
  ],
  requests: [
    {
      id: "request-apex-multitrade",
      projectId: "proj-001",
      projectName: "Nila Residence",
      location: "Thiruvananthapuram, Kerala",
      trade: "Multi-Trade Squad",
      requiredDate: "Tomorrow",
      quantity: 10,
      fulfilled: 7,
      status: "Partially assigned",
      contractorName: "Apex Integrated Civil & Finishing Crew",
      contractorBrand: "apex",
      contractorRating: 4.9,
      contractorExperienceYears: 12,
      dailyRate: 920,
      skillLevel: "Multi-disciplinary trade crew",
      shiftTiming: "8:00 AM – 5:00 PM",
      duration: "3 weeks",
      isMultiTrade: true,
      tradesBreakdown: [
        {
          trade: "Masons",
          quantity: 4,
          fulfilled: 2,
          skillLevel: "Lead brick masons",
          dailyRate: 950,
        },
        {
          trade: "Electricians",
          quantity: 2,
          fulfilled: 1,
          skillLevel: "Certified wiring electricians",
          dailyRate: 1100,
        },
        {
          trade: "Helpers",
          quantity: 4,
          fulfilled: 4,
          skillLevel: "Material staging helpers",
          dailyRate: 650,
        },
      ],
      contractorCoverImage:
        "https://images.unsplash.com/photo-1541888946425-d0fbb180c5f5?w=900&auto=format&fit=crop&q=80",
    },
    {
      id: "request-forma-multitrade",
      projectId: "proj-004",
      projectName: "Green Courtyard",
      location: "Thrissur, Kerala",
      trade: "Multi-Trade Squad",
      requiredDate: "30 Jul",
      quantity: 7,
      fulfilled: 3,
      status: "Partially assigned",
      contractorName: "Forma MEP & Woodworks Contractor",
      contractorBrand: "forma",
      contractorRating: 4.8,
      contractorExperienceYears: 11,
      dailyRate: 980,
      skillLevel: "Joiners & MEP wiremen",
      shiftTiming: "8:30 AM – 5:30 PM",
      duration: "2 weeks",
      isMultiTrade: true,
      tradesBreakdown: [
        {
          trade: "Carpenters",
          quantity: 4,
          fulfilled: 2,
          skillLevel: "Hardwood finish joiners",
          dailyRate: 950,
        },
        {
          trade: "Electricians",
          quantity: 3,
          fulfilled: 1,
          skillLevel: "DB switchgear wiremen",
          dailyRate: 1050,
        },
      ],
      contractorCoverImage:
        "https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=900&auto=format&fit=crop&q=80",
    },
    {
      id: "request-helpers",
      projectId: "proj-003",
      projectName: "Marina Office",
      location: "Kozhikode, Kerala",
      trade: "Helpers",
      requiredDate: "02 Aug",
      quantity: 8,
      fulfilled: 6,
      status: "Partially assigned",
      contractorName: "Apex Material Staging & Site Labour Crew",
      contractorBrand: "apex",
      contractorRating: 4.9,
      contractorExperienceYears: 8,
      dailyRate: 650,
      skillLevel: "General helpers",
      shiftTiming: "9:00 AM – 6:00 PM",
      duration: "3 weeks",
      contractorCoverImage:
        "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=900&auto=format&fit=crop&q=80",
    },
    {
      id: "request-masons",
      projectId: "proj-002",
      projectName: "Arjun Villa",
      location: "Kochi, Kerala",
      trade: "Masons",
      requiredDate: "05 Aug",
      quantity: 4,
      fulfilled: 0,
      status: "Open",
      contractorName: "Master Masons & Brickwork Team",
      contractorBrand: "apex",
      contractorRating: 4.9,
      contractorExperienceYears: 14,
      dailyRate: 950,
      skillLevel: "Lead brick masons",
      shiftTiming: "8:00 AM – 5:00 PM",
      duration: "2 weeks",
      contractorCoverImage:
        "https://images.unsplash.com/photo-1590381105924-c72589b9ef3f?w=900&auto=format&fit=crop&q=80",
    },
  ],
  attentionItems: [
    {
      id: "attention-nila-absence",
      title: "Two workers are absent at Nila Residence",
      detail: "Today · 16 of 18 workers checked in",
      actionLabel: "Review attendance",
      actionTab: "attendance",
      severity: "critical",
    },
    {
      id: "attention-carpenter-shortfall",
      title: "Carpenter request is short by two workers",
      detail: "Nila Residence · Required tomorrow",
      actionLabel: "Update request",
      actionTab: "requests",
      severity: "warning",
    },
    {
      id: "attention-green-approval",
      title: "Attendance approval is pending for Green Courtyard",
      detail: "Today · Supervisor check-in not confirmed",
      actionLabel: "Approve attendance",
      actionTab: "attendance",
      severity: "warning",
    },
    {
      id: "attention-marina-ending",
      title: "Marina Office deployment ends tomorrow",
      detail: "4 electricians · Review extension or completion",
      actionLabel: "Review deployment",
      actionTab: "deployments",
      severity: "info",
    },
  ],
  demand: [
    {
      id: "demand-today",
      dateLabel: "Today",
      projectName: "Nila Residence",
      trade: "Masons",
      quantity: 8,
      state: "Confirmed",
    },
    {
      id: "demand-tomorrow",
      dateLabel: "Tomorrow",
      projectName: "Nila Residence",
      trade: "Carpenters",
      quantity: 5,
      state: "Request pending",
    },
    {
      id: "demand-30-jul",
      dateLabel: "30 Jul",
      projectName: "Green Courtyard",
      trade: "Electricians",
      quantity: 3,
      state: "Request pending",
    },
    {
      id: "demand-31-jul",
      dateLabel: "31 Jul",
      projectName: "Arjun Villa",
      trade: "Painters",
      quantity: 6,
      state: "Confirmed",
    },
    {
      id: "demand-01-aug",
      dateLabel: "01 Aug",
      projectName: "Green Courtyard",
      trade: "Carpenters",
      quantity: 5,
      state: "Confirmed",
    },
    {
      id: "demand-02-aug",
      dateLabel: "02 Aug",
      projectName: "Marina Office",
      trade: "Helpers",
      quantity: 8,
      state: "Request pending",
    },
    {
      id: "demand-03-aug",
      dateLabel: "03 Aug",
      projectName: "Nila Residence",
      trade: "Tile workers",
      quantity: 4,
      state: "Not requested",
    },
  ],
};

function wait(duration: number): Promise<void> {
  return new Promise((resolve) => window.setTimeout(resolve, duration));
}

export async function loadHandsOverview(): Promise<HandsOverviewData> {
  await wait(320);
  return overviewData;
}

export async function saveWorkforceRequestDraft(
  draft: WorkforceRequestDraft,
): Promise<{ draftId: string }> {
  await wait(450);

  if (draft.notes.trim().toLowerCase() === "simulate error") {
    throw new Error("The draft could not be saved. Try again.");
  }

  return { draftId: `hands-draft-${Date.now()}` };
}

export async function submitWorkforceRequest(
  submission: WorkforceRequestSubmission,
): Promise<WorkforceRequest> {
  await wait(700);

  if (submission.notes.trim().toLowerCase() === "simulate error") {
    throw new Error("The request could not be submitted. Try again.");
  }

  return {
    id: `hands-request-${Date.now()}`,
    projectId: submission.projectId,
    projectName: "Selected project",
    trade: submission.trade,
    requiredDate: submission.startDate,
    quantity: submission.workerCount,
    fulfilled: 0,
    status: "Open",
    isMultiTrade: submission.isMultiTrade,
    tradesBreakdown: submission.tradesBreakdown,
  };
}
