import {
  BuildingDuotoneIcon,
  DrawingsDuotoneIcon,
  EnergyDuotoneIcon,
  ExploreDuotoneIcon,
  LayersDuotoneIcon,
  ResolveDuotoneIcon,
  SiteDuotoneIcon,
  UserDuotoneIcon,
} from "@/components/layout/sidebar-icons";

export interface TradeCrew {
  id: string;
  name: string;
  trade: string;
  category: string;
  leadName: string;
  leadRole: string;
  verified: boolean;
  rating: number;
  reviewCount: number;
  completedJobs: number;
  experienceYears: number;
  crewSizeMin: number;
  crewSizeMax: number;
  dailyRate: number; // in INR
  rateUnit: string;
  availability: "immediate" | "this_week" | "next_week";
  availabilityLabel: string;
  location: string;
  state: string;
  skills: string[];
  certifications: string[];
  safetyCompliant: boolean;
  icon: typeof BuildingDuotoneIcon;
  accentColor: string;
  bgTint: string;
}

export const MOCK_TRADE_CREWS: TradeCrew[] = [
  {
    id: "crew-masons-01",
    name: "Master Masons & Brickwork Team",
    trade: "Masons",
    category: "Civil & Masonry",
    leadName: "Rajan K.",
    leadRole: "Master Mason & Site Lead",
    verified: true,
    rating: 4.9,
    reviewCount: 42,
    completedJobs: 64,
    experienceYears: 14,
    crewSizeMin: 4,
    crewSizeMax: 12,
    dailyRate: 950,
    rateUnit: "per worker / day",
    availability: "immediate",
    availabilityLabel: "Available Tomorrow",
    location: "Kochi, Ernakulam",
    state: "Kerala",
    skills: ["RCC Brickwork", "Plastering", "Foundation", "AAC Block Work", "Stone Masonry"],
    certifications: ["Kallisto Certified Civil Guild", "Site Safety Level 2"],
    safetyCompliant: true,
    icon: BuildingDuotoneIcon,
    accentColor: "#16a34a",
    bgTint: "#f0fdf4",
  },
  {
    id: "crew-electricians-01",
    name: "Certified MEP & Electrical Gang",
    trade: "Electricians",
    category: "Electrical & MEP",
    leadName: "Shaji Mathew",
    leadRole: "Licensed Electrical Supervisor",
    verified: true,
    rating: 4.95,
    reviewCount: 58,
    completedJobs: 89,
    experienceYears: 12,
    crewSizeMin: 2,
    crewSizeMax: 8,
    dailyRate: 1100,
    rateUnit: "per worker / day",
    availability: "immediate",
    availabilityLabel: "Available Today",
    location: "Trivandrum",
    state: "Kerala",
    skills: ["Conduit Piping", "DB Dressing", "HT/LT Cabling", "Earthing Grid", "Smart Automation"],
    certifications: ["Kerala Wireman / Supervisor License B", "Kallisto Verified MEP"],
    safetyCompliant: true,
    icon: EnergyDuotoneIcon,
    accentColor: "#0284c7",
    bgTint: "#f0f9ff",
  },
  {
    id: "crew-plumbers-01",
    name: "Plumbing & Drainage Specialists",
    trade: "Plumbers",
    category: "Plumbing & Sanitary",
    leadName: "Sudheesh P.",
    leadRole: "Master Sanitary Technician",
    verified: true,
    rating: 4.85,
    reviewCount: 36,
    completedJobs: 52,
    experienceYears: 9,
    crewSizeMin: 2,
    crewSizeMax: 6,
    dailyRate: 1050,
    rateUnit: "per worker / day",
    availability: "immediate",
    availabilityLabel: "Immediate Deployment",
    location: "Ernakulam",
    state: "Kerala",
    skills: ["CPVC/UPVC Piping", "Pressure Testing", "Overhead Tank Piping", "Sanitary Ware Fitting", "Sewage Lines"],
    certifications: ["Kallisto Plumbing Guild Certificate"],
    safetyCompliant: true,
    icon: ResolveDuotoneIcon,
    accentColor: "#0891b2",
    bgTint: "#ecfeff",
  },
  {
    id: "crew-carpenters-01",
    name: "Formwork & Shuttering Carpenters",
    trade: "Carpenters",
    category: "Woodwork & Formwork",
    leadName: "Manoj V.",
    leadRole: "Senior Formwork Foreman",
    verified: true,
    rating: 4.9,
    reviewCount: 48,
    completedJobs: 71,
    experienceYears: 13,
    crewSizeMin: 4,
    crewSizeMax: 10,
    dailyRate: 1150,
    rateUnit: "per worker / day",
    availability: "this_week",
    availabilityLabel: "Available in 2 days",
    location: "Kochi, Ernakulam",
    state: "Kerala",
    skills: ["Mivan Formwork", "Plywood Shuttering", "Scaffolding Rigging", "Deck Leveling", "Column Boxes"],
    certifications: ["Structural Formwork Safety Certified"],
    safetyCompliant: true,
    icon: LayersDuotoneIcon,
    accentColor: "#d97706",
    bgTint: "#fffbeb",
  },
  {
    id: "crew-steel-01",
    name: "Rebar & Structural Steel Fixers",
    trade: "Steel Fixers",
    category: "Reinforcement & Steel",
    leadName: "Azeez Rahman",
    leadRole: "BBS & Rebar Foreman",
    verified: true,
    rating: 4.88,
    reviewCount: 39,
    completedJobs: 63,
    experienceYears: 10,
    crewSizeMin: 4,
    crewSizeMax: 16,
    dailyRate: 1000,
    rateUnit: "per worker / day",
    availability: "immediate",
    availabilityLabel: "Available Tomorrow",
    location: "Calicut",
    state: "Kerala",
    skills: ["Bar Bending Schedule (BBS)", "Footing Reinforcement", "Column Rings / Ties", "Slab Mesh Binding", "Coupler Fitting"],
    certifications: ["IS 2502 Rebar Standards Certified"],
    safetyCompliant: true,
    icon: SiteDuotoneIcon,
    accentColor: "#64748b",
    bgTint: "#f8fafc",
  },
  {
    id: "crew-painters-01",
    name: "Commercial Painting & Finishers",
    trade: "Painters",
    category: "Finishing & Coating",
    leadName: "Binoy George",
    leadRole: "Finishing Supervisor",
    verified: true,
    rating: 4.82,
    reviewCount: 31,
    completedJobs: 46,
    experienceYears: 8,
    crewSizeMin: 3,
    crewSizeMax: 8,
    dailyRate: 900,
    rateUnit: "per worker / day",
    availability: "immediate",
    availabilityLabel: "Instant Booking",
    location: "Kottayam",
    state: "Kerala",
    skills: ["Putty Application", "Airless Spray Painting", "Texture Wall Finishes", "Exterior Weatherproof", "PU Wood Polishing"],
    certifications: ["Asian Paints / Berger Certified Applicator"],
    safetyCompliant: true,
    icon: DrawingsDuotoneIcon,
    accentColor: "#e11d48",
    bgTint: "#fff1f2",
  },
  {
    id: "crew-supervisors-01",
    name: "Site QA & Daily Shift Supervisors",
    trade: "Supervisors",
    category: "Site Management & QA",
    leadName: "K. N. Sreekumar",
    leadRole: "Civil Site Engineer & Inspector",
    verified: true,
    rating: 4.96,
    reviewCount: 64,
    completedJobs: 112,
    experienceYears: 16,
    crewSizeMin: 1,
    crewSizeMax: 3,
    dailyRate: 1600,
    rateUnit: "per supervisor / day",
    availability: "immediate",
    availabilityLabel: "Available Tomorrow",
    location: "Kochi, Ernakulam",
    state: "Kerala",
    skills: ["Daily Shift DPR", "Material Inward QA", "Concrete Cube Testing", "Safety Compliance", "Labour Log Management"],
    certifications: ["B.Tech Civil", "Kallisto Verified Site Inspector", "NEBOSH IGC"],
    safetyCompliant: true,
    icon: UserDuotoneIcon,
    accentColor: "#9333ea",
    bgTint: "#faf5ff",
  },
  {
    id: "crew-surveyors-01",
    name: "Total Station Land Surveyors & QS",
    trade: "Surveyors",
    category: "Surveying & QS",
    leadName: "Vipin Das",
    leadRole: "Senior Geodetic Surveyor",
    verified: true,
    rating: 4.92,
    reviewCount: 29,
    completedJobs: 48,
    experienceYears: 11,
    crewSizeMin: 2,
    crewSizeMax: 4,
    dailyRate: 1800,
    rateUnit: "per surveyor / day",
    availability: "immediate",
    availabilityLabel: "Available Tomorrow",
    location: "Thrissur",
    state: "Kerala",
    skills: ["Total Station Survey", "AutoCAD Plotting", "Topographical Mapping", "Boundary Demarcation", "Earthwork Cut & Fill"],
    certifications: ["Diploma in Civil / Surveying", "Kallisto Certified Field Surveyor"],
    safetyCompliant: true,
    icon: ExploreDuotoneIcon,
    accentColor: "#ea580c",
    bgTint: "#fff7ed",
  },
  {
    id: "crew-tiles-01",
    name: "Precision Tile & Granite Craftsmen",
    trade: "Tile Layers",
    category: "Civil & Masonry",
    leadName: "Pradeep Menon",
    leadRole: "Master Tile Artisan",
    verified: true,
    rating: 4.9,
    reviewCount: 45,
    completedJobs: 73,
    experienceYears: 13,
    crewSizeMin: 3,
    crewSizeMax: 8,
    dailyRate: 1100,
    rateUnit: "per worker / day",
    availability: "this_week",
    availabilityLabel: "Available in 3 days",
    location: "Kochi, Ernakulam",
    state: "Kerala",
    skills: ["Vitrified Tile Laying", "Italian Marble Polishing", "Epoxy Grouting", "Granite Steps & Cladding", "Laser Level Alignment"],
    certifications: ["Kallisto Fine Finishing Guild"],
    safetyCompliant: true,
    icon: BuildingDuotoneIcon,
    accentColor: "#16a34a",
    bgTint: "#f0fdf4",
  },
  {
    id: "crew-welders-01",
    name: "Structural Welders & Fabricators",
    trade: "Welders",
    category: "Reinforcement & Steel",
    leadName: "Antony Varghese",
    leadRole: "Certified Structural Fabricator",
    verified: true,
    rating: 4.86,
    reviewCount: 28,
    completedJobs: 41,
    experienceYears: 11,
    crewSizeMin: 2,
    crewSizeMax: 6,
    dailyRate: 1250,
    rateUnit: "per worker / day",
    availability: "immediate",
    availabilityLabel: "Available Tomorrow",
    location: "Alappuzha",
    state: "Kerala",
    skills: ["MIG/TIG Welding", "Truss Fabrication", "MS Staircase & Railing", "Canopy Structure", "On-site Rigging"],
    certifications: ["ASME Section IX Welder Qualification"],
    safetyCompliant: true,
    icon: SiteDuotoneIcon,
    accentColor: "#64748b",
    bgTint: "#f8fafc",
  },
  {
    id: "crew-helpers-01",
    name: "Site Helpers & Labourers Pool",
    trade: "Helpers",
    category: "General Site Labour",
    leadName: "Gireesh Kumar",
    leadRole: "Labour Supervisor",
    verified: true,
    rating: 4.78,
    reviewCount: 54,
    completedJobs: 95,
    experienceYears: 7,
    crewSizeMin: 5,
    crewSizeMax: 25,
    dailyRate: 800,
    rateUnit: "per worker / day",
    availability: "immediate",
    availabilityLabel: "Instant Deployment",
    location: "Kochi, Ernakulam",
    state: "Kerala",
    skills: ["Concrete Mixing Support", "Material Handling", "Site Cleaning & Debris Removal", "Curing Water Spray", "Excavation Assistance"],
    certifications: ["Verified Identity & Background Checked"],
    safetyCompliant: true,
    icon: UserDuotoneIcon,
    accentColor: "#9333ea",
    bgTint: "#faf5ff",
  },
];
